### ISSUE TITLE
Neo CoolCam door sensor  not working stable

### ISSUE THREAD

**Issue by Paragon1337** [mruiter/com.neo#100]
I have 4 Neo CoolCam door sensors:

NEO COOLCAM 4PCS/lot NAS-DS01Z Z-wave Door Window Sensor Compatible with Z wave 300 500 series Magnet Lock Door Sensor Alarm

SPECIFICATIONS

Z-Wave Signal Frequency: 868.4MHz EU Version
Power: 1 CR2 battery (included)
Power Consumption: 0.13W
Wireless Range: Up to 100 feet
Operating Temperature: 32° - 104°F (0°- 40°C)
Installation and Use: Indoor only
Dimensions: 2.75 x 0.75 inches
Weight: 0.5 oz

I can add them to Homey, but when I install them at the doors everything is unstable.
Is there a minimal distance needed, between the sensor and Homey?
How can I troubleshoot zwave network?

**Comment by diaemiel** [comment]
My Neo COOLCam DOOR sensors(4x) are not working at all. And my Z-wave plus 1CH EU Wall light switch(3x) does not recognize/not working. Even if I have my homey 1 meter next to the sensors!!!
How can i troubleshoot z-wave sensors? Are there alternative apps or are all my sensors broken ?????

**Comment by mruiter** [comment]
Send in the zwave logs filteren on the devices that dont work . There are no other reports so you either have a new version ot paired them with a fail 

Verstuurd vanaf mijn iPhone
