### ISSUE TITLE
after installing beta version and switched back to stable all devices are gone

### ISSUE THREAD

**Issue by newatschoen** [mruiter/com.neo#101]
after installing beta version and switched back to stable all devices are gone

**Comment by newatschoen** [comment]
how can I bring my devices back?

**Comment by mruiter** [comment]
When switching to beta there is a warning you can’t go back to stable lower version without loosing all you’re neo devices .
This is with all homey apps .

To get them back you will have to remove them in setting zwave and do a re-pair again 


Verstuurd vanaf mijn iPhone
