### ISSUE TITLE
869.2 mhz. Russian frequency

### ISSUE THREAD

**Issue by Tuhulka** [mruiter/com.neo#102]
Hey. Good afternoon. Me again. My devices are 869.2 mhz. Russian frequency has arrived. Please add them to the plugin. Thank you in advance for your help.

NAS-WS02Z Flood Water
Settings
Key Value
zw_node_id "13"
zw_manufacturer_id "600"
zw_product_type_id "3"
zw_product_id "8325"

[NAS-PD02Z Z-wave Plus PIR Motion Sensor Detector+Temperature Sensor Z wave Alarm System Motion Sensor [https://ru.aliexpress.com/item/32856082375.html?spm=a2g0o.detail.1000016.1.38f943eaG8s3bX&isOrigTitle=true](url)
First the motion sensor was V2 case V1. When connected to RUBETEK it shows the temperature. In Homey the temperature is not showing, because it is added as NAS-PD01Z.
Settings
Key Value
zw_node_id "12"
zw_manufacturer_id "600"
zw_product_type_id "3"
zw_product_id "8333"

Touch Switch Dual 
Settings
Key Value
zw_node_id "16"
zw_manufacturer_id "600"
zw_product_type_id "3"
zw_product_id "8331"

NAS-WR01Z connected correctly as Power Plug
Settings
Key Value
zw_node_id "15"
zw_manufacturer_id "600"
zw_product_type_id "3"
zw_product_id "8327"

**Comment by mruiter** [comment]
All devices are added into the next beta
