### ISSUE TITLE
Neo v2 PIR

### ISSUE THREAD

**Issue by Sejkooz** [mruiter/com.neo#103]
I have issues with Neo v2 motion sensor.
I have 2 Neo PIR sensors that worked fine for about a week and after that, the status of motion alarm stays ON and does not reset it self to OFF when it should. Temperatur and Lux is still reporting as it should.. And yes i have checked detection time and blind time.
![Screenshot_20190601-223640_Homey](https://user-images.githubusercontent.com/48295110/58753332-c0369a00-84bd-11e9-8127-00d9018d76a6.jpg)

**Comment by mruiter** [comment]
This is a common homey core issue and a missed report . See the community forums for solutions and to upgrade you’re mesh network quality . You can also try a wake up of the device as in the manual 

Verstuurd vanaf mijn iPhone
