### ISSUE TITLE
Neo coolcam flood sensor not working

### ISSUE THREAD

**Issue by smartlivingAU** [mruiter/com.neo#104]
The AU frequency of the Neo Coolcam flood sensor doesn’t work even if the app is installed.  Tried it on the Beta version too but it always comes up with no compatible app installed. Can you please add support for it ? The model is NAS-FS01Z.

**Comment by mruiter** [comment]
Please send me the manufacturer, product and device id of the device as found in advanced settings of the device and I will add it next version

Verstuurd vanaf mijn iPhone

**Comment by smartlivingAU** [comment]
Hi

Thanks for the quick response. Here are the details as requested.

Is there an ETA when the next version is out ?

 

 

 

 

David

**Comment by mruiter** [comment]
can you send in the ids ? github isnt showing anything and i think you tried to send something in

**Comment by smartlivingAU** [comment]
This is what I emailed through last time. Is there something else you need ?




Regards
David

**Comment by mruiter** [comment]
Github isnt showing anything . can you please post the id's in plain text here ?

**Comment by smartlivingAU** [comment]
Hi

Device ID 8
Manufacturer ID 600
Product Type ID 3
Product ID 24709

Thanks

**Comment by mruiter** [comment]
Added in version 2.1.1 in the future 

Verstuurd vanaf mijn iPhone
