### ISSUE TITLE
NEO Coolcam Smart Home Z Wave Plus Smart Gordijn Schakelaar voor Elektrische Gemotoriseerde Gordijn Blind Rolluik

### ISSUE THREAD

**Issue by dwgreven** [mruiter/com.neo#105]
Hey Marco,
Is there a chance to get the new zwave coolcam curtain switch working with Homey?

![B013F53E-9F0C-4B01-9B44-353A1B7DE2AA](https://user-images.githubusercontent.com/52658446/60804412-c8998900-a17d-11e9-914f-33da4e53e306.png)

Thanks in advance and greetings,
Wilfred

**Comment by elwinekker** [comment]
Yes, is there a chance You will?

**Comment by rgobyn** [comment]
Was planning on using Fibaro but then I found this. It is a very nice looking switch! I already use the touch switches in my home - working great with homey pro (2019) 2.5.2.

Please add the curtain switch to the homey app ! 
There are very little possibilities on the market for curtain shutters working with homey....

**Comment by Lansuper** [comment]
Now using a complicated setup with smart plugs and ralais, would be fantastic to operate the curtains with the NAS-CS01ZE

**Comment by mruiter** [comment]
Will close this issue since we are working on it in : https://github.com/mruiter/com.neo/issues/115
