### ISSUE TITLE
Low Battery-Alarm sends Motion-Alarm

### ISSUE THREAD

**Issue by CyberSponk** [mruiter/com.neo#106]
Homey 2.4.0-Exp
Neo Coolcam App 2.0.21 Beta

If a Batterie goes end of life Homey sends Motion-Alarms instead of Low-Battery-Alarms/Battery-Alarms. Got this on two Motion-Sensors.

**Comment by mruiter** [comment]
strange .. Do you have v1 or v2 motion sensors ?

**Comment by CyberSponk** [comment]
Have only V2 Motion Sensors.

**Comment by Lansuper** [comment]
I have the same issue on v1 and v2 motion sensors. Had to disable the intruder alarm for all of my 10 sensors have this problem. Where they control the lighting, this gives me an indication of what sensor battery is running low. The battery status always gives 100%, the lie battery flows never fire...

**Comment by mruiter** [comment]
Not app related issue but hardware and zwave protocol issues . Please open a ticket at either sigma , coolcam neo or athom if you want something done about it .
