### ISSUE TITLE
Option to invert alarm for door sensor

### ISSUE THREAD

**Issue by macfreek** [mruiter/com.neo#107]
I have a few sensors that are "on" by default and "off" in case of a exceptional state.
Would it be possible to add an advanced option to door/window sensors that invert the logic (so magnet nearby = alarm; magnet at a distance = no alarm).

Before I just changed the flow to get the right state, but with the new zone activity, the logic of the "active"/"inactive" state is also inverted, and I like to correct that.

I hope it is possible to fix in this app.

**Comment by mruiter** [comment]
I cant fix this in the app. It just looks at a alarm report and will trigger active on it. Logic is the only way to go or invert the signal that you use to trigger the contact on the Doorsensor with reversed logic IC

**Comment by macfreek** [comment]
Too bad. FYI, I put in request for enhancement with the Homey developers, but am not holding my breath.

Thanks for looking into this and reporting back!
