### ISSUE TITLE
negative nummer energie meter

### ISSUE THREAD

**Issue by satbopper** [mruiter/com.neo#108]
neo version 2.0.21 homey version 2.5.2
i have four plugs and randomly there are giving a negative nummer of -21474836.46
i can reset those plugs with a flow but a few hours further it is again a negative nummer
the working of the plugs is good,they are switching ok,only the info is not right

**Comment by mruiter** [comment]
Duplicate issue .there is already a GitHub issue running for this. This is a firmware error in the neo plug itself
