### ISSUE TITLE
Motiondetection ON time goes not lower then 30sec

### ISSUE THREAD

**Issue by Marc1979** [mruiter/com.neo#11]
I cannot set the Motiondetection On time to 15sec. With another Neo sensor it works well.
Maybe not a app problem but a sensor problem?

**Comment by TedTolboom** [comment]
Hi Marc,
Just saw your issue on Slack.. On slack you indicated that you have re-paired the sensor to Homey.

Can you add which settings you are currently using and which app version?

In the recent app / driver I don't see any restrictions that could cause this issue... specifically device specific.

Currently updating settings is quite troublesome with battery powered Z-wave devices.
After the re-pair, did you update other settings (in parallel! to this setting) that show to be effective while only this one is not?

Most reliable way to update battery powered motion sensors (Fibaro or Neo) 
- Place the sensor near Homey (< 1 meter)
- Change the settings to the values you want
- Wake up the sensor (triple click the button)
- **During the blinking of the LED** (indicating connection to Homey) press "save settings"

If problems persist, temporarely disable other Z-wave apps, change the setting to another value with above steps, check if effective and retry to the desired value.

Can you try if above steps are able to resolve your issue?

**Comment by Marc1979** [comment]
I just re-add the device. Have the settings set as I want using you're methode and it is working! Thanks! You're the neo-meister!

**Comment by TedTolboom** [comment]
Good to hear and thanks for the fast feedback!
