### ISSUE TITLE
Lux report only when Motion sensor is activated

### ISSUE THREAD

**Issue by henkbart** [mruiter/com.neo#110]
Hello,
I am using version 2.0.19 form you,
I have setup the PIR V2 settings to report every 60 sec the LUX value.
But that does not work.
The LUX value is only send to the Homey when the motion sensor is triggered.

I already try to Unpaired and then paired but that does not solve the problem.

Can you help???

**Comment by mruiter** [comment]
should be solved now. if not reset the pir to factory defaults after you removed it from homey and then re-pair
