### ISSUE TITLE
New device add NAS-SC03ZE - NAS-SW01ZE, Touch Wall Switch Triple

### ISSUE THREAD

**Issue by thaserge** [mruiter/com.neo#111]
Hello! 
Good triple switches appeared on sale. 
How can I help to add them to the plugin?

https://szneo.com/en/products/show.php?id=237

**Comment by robkoetsier** [comment]
Hi Thaserge! Thanks for posting this request, I just bought one too, can't wait to make them available for Homey!

**Comment by chrhinna** [comment]
I got one as well but cant figure out how to add it. If any information is required to add it please ask and I will help as much as I can.

**Comment by mruiter** [comment]
Could you please supply me with the product device and manufactures id that you find in settings when the devices is added as a generic devices. Without that info i cant add it

**Comment by chrhinna** [comment]
Hi,  here are the information.
Device ID: 19
Manufactor ID: 600
Product Type ID: 512
Product ID: 4139

**Comment by mruiter** [comment]
I have added the devices to the latest version of the app that’s available on my GitHub for the app.

Could you please test / sideload it to see if it works ?

Verstuurd vanaf mijn iPhone

**Comment by chrhinna** [comment]
I can't installe the app. due to a error popping up during installation.
>athom app install
✓ Pre-processing app...
✓ Validating app...
✓ Homey App validated successfully against level `debug`
✓ Packing Homey App...
 — App size: 4.73 MB
✓ Installing Homey App on `Homey Pro ` (http://xxx.xxx.xxx:80)...
× Invalid driver battery: CR3032. Allowed values: LS14250, AA, AAA, A23, A27, PP3, CR123A, CR2, CR1632, CR2032, CR2450, CR2477, INTERNAL, OTHER

**Comment by mruiter** [comment]
You need to updat athom cli and node.js libs since it uses the latest version with added battery types 

Verstuurd vanaf mijn iPhone

**Comment by chrhinna** [comment]
Ok, thanks I will do that and try again.

**Comment by chrhinna** [comment]
Hi, Homey finde the switch ok, but every time I toggle either the middle or the right switch homey toggle the left or Touch switch Tripple as as well, but nothing happens to the physical left switch. I have to click the lfet (Touch Switch Triple) 2 times to turn the physical switch on, except for this issue   it works great. Thank you.

**Comment by mruiter** [comment]
I don’t exactly get what you are trying to tell me what’s not working could you be more specific? If you’re Dutch in Dutch is also ok

Verstuurd vanaf mijn iPhone

**Comment by chrhinna** [comment]
Hi, I found the problem. I just had to rename the switches in Homey. I just put 1 2 3 infront of the names and everything worked. Can the issue be that to many letters in the swich name are identical?
Thanks for all the help. The switch works great now that i renamed them. I tried to send you 2 videos of the issue. 1 with the problem and one where I just changed the switch name and problem solved.

**Comment by chrhinna** [comment]
I uploaded the videos to my dropbox. here are the link.
Here’s a link to “Whit problem.MOV” in my Dropbox:
[https://www.dropbox.com/s/k3mlw6k3zvgq4yc/Whit%20problem.MOV?dl=0](url)
Here’s a link to Problem Fixed.MOV” in my Dropbox:
[https://www.dropbox.com/s/d277ph92ahq8djo/Problem%20fixed.MOV?dl=0](url)

**Comment by mruiter** [comment]
Great . I will change the name of the device components that create the homey device icon so it will be different from the first letter . Thanks for you’re feedback. 

Now I’m only looking for someone with the curtain controller for some info and device ids so I can add that one too before new release 

Verstuurd vanaf mijn iPhone

**Comment by chrhinna** [comment]
I have done more testing. I have tested with 2 different switches and 1 homey and 1 homey pro. After a while i get the same problem even with using 1 2 3 in front of switch name. The left swich will toggel in the software but not the switch if either of the other switches are toggeled in the homey software. Exactly as the video show. I can figure ut whay it worked during my first test. There must be some other issue in the program.

**Comment by dwgreven** [comment]
Hey Marco,
I have added the info to the curtain switch manual (included the id’s).

Thanks in advance,
Wilfred

**Comment by mruiter** [comment]
The v2.1 version is now pending the appstore approval . Will continue on the curtain now for v2.1.1 version. Will close this issue and continue in the dedicated issue for the curtain controller
