### ISSUE TITLE
Wallplug not visable after adding

### ISSUE THREAD

**Issue by Raycokes2000** [mruiter/com.neo#112]
I added a wallplug but it is not visable, can not re-add, says already added. Or after homey reboot I got one plug added. Second one says first adding device... Waiting... Waiting.... Then no zwave device found 🤔😒😬
After second reboot no more device can be added, all ready added but stil not visuable as device

4e2ae34d-a76e-4394-abf9-a3834c3c76ce

**Comment by mruiter** [comment]
Please go to the community forum to see how to remove stuck zwave devices.
