### ISSUE TITLE
NAS-DS01ZE, Door Sensor - NC vs NO

### ISSUE THREAD

**Issue by elfrigo** [mruiter/com.neo#114]
This door sensor is configured as NC (e.g. with the magnet near the device alarm is OFF).
Can you please add the possibility to change the state from NC to NO.
Reason: You can solder 2 wires on the magnetic relay and use it as a binary sensor (doorbell). But most of those are NO.
It is a bit weird to constantly have an Alarm state ON when it should be OFF.

I hope this is not to much asked for. Unfortunately my programming skills are to limited to do this myself or help you with it.
It would though greatly improve the uses of this already very nice sensor.

Thank you very much!

**Comment by mruiter** [comment]
I cant invert the alarm invert from app with a setting. The way to solve this is by filling a homey logic to invert the response
