### ISSUE TITLE
Neo coolcam power plug

### ISSUE THREAD

**Issue by Nakika** [mruiter/com.neo#116]

**Comment by Nakika** [comment]
Waarden worden niet geüpdatet. Plug is secured. Met een lid van forum geprobeerd naar unsecured te zetten. PetervdK is dit gelukt. Ik heb zijn aanwijzingen gevolgd maar mij lukt het niet. 
https://community.athom.com/t/hihome-slimme-stekker/14130/20

**Comment by mruiter** [comment]
Homey core issue should be fixed latest version s
