### ISSUE TITLE
Kan er een software lock op icoon power plug komen?

### ISSUE THREAD

**Issue by Zcooby** [mruiter/com.neo#117]
Hallo,
Is het mogelijk een software lock op het homey icoontje van de Power Plug te plaatsen zodat in vervolg de desbetreffende apparaat NIET wordt uitgeschakelt. 
Ik vind het vervelend dat als ik door het icoontje scrolled (kWh, Volt ect) dat ik deze uitschakelt, bijv mijn PC?

**Comment by mruiter** [comment]
Helaas staat athom het niet toe dit soort locks op de icoon te zetten . Fibaro is dan op deze plekken een betere keuze want deze heeft de opties in de settings om de aan uit optie uit te zetten
