### ISSUE TITLE
Wake-up reporting does not seem to be done on door sensor NAS-DS01ZE

### ISSUE THREAD

**Issue by cjvs** [mruiter/com.neo#122]
Hi,
I have 10 door sensors and none of them seems to be reporting to homey with the wake-up interval. When using Heimdall, all sensors not used for more than 24 hours are flagged as not reporting.

I am quite sure that the settings are received and correctly set by the sensor (or at least the most of them). However, reporting (once every hour in my case) does not work.

Please let me know if I can help in resolving this.

**Comment by mruiter** [comment]
Still cant be fixed in SDKv3 since this is a homey zwave core issue and the new SDK doesnt provide any enhancements on zwave.
