### ISSUE TITLE
No power usage read out after V2.1.0

### ISSUE THREAD

**Issue by pjmpessers** [mruiter/com.neo#124]
Also installing V2.1.1 didn't help. My powerplug still has no readout for current, powerusage, etc. I set the  "meter reportage interval" on 60s and "current change" on 10%. 
when i switch the powerplug off and on by homey i get a readout. But only then. I can easily switch the powerplug on and off. So i don't think it is a range isue.

**Comment by mruiter** [comment]
Guess then the only option is 2 unpair the plug . Do the reset 2 default on the plug and then pair again with the new 2.1 app . 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
And , nice to know . Is it a v1 or V2 plug ?

Verstuurd vanaf mijn iPhone

**Comment by pjmpessers** [comment]
Hoi Marco.

Het product_type_id is 3. Is dat een v2?


-------- Oorspronkelijk bericht --------
Van: Marco Ruiter <notifications@github.com>
Datum: 04-12-19 17:29 (GMT+01:00)
Aan: "mruiter/com.neo" <com.neo@noreply.github.com>
Cc: Pieter <pieterpessers@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [mruiter/com.neo] No power usage read out after V2.1.0 (#124)

And , nice to know . Is it a v1 or V2 plug ?

Verstuurd vanaf mijn iPhone

**Comment by pjmpessers** [comment]
Hoi Marco.

Het heeft niet geholpen om de powerplug in homey te verwijderen, resetten op de powerplug met meer dan 10 seconden en weer aan te sluiten. Hij leest het stroomverbruik maar een keer uit en dan niet meer. Sommige powerplugs geven geen problemen. Het maakt niet uit waar de powerplug geplaatst is (afstand) of welke type(Product id 3 of 512.

Met vriendelijke groeten: Pieter.


Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

**Comment by mruiter** [comment]
I made some corrections since they now ship with a new manual and some setting changes.
Could you test with my latest version of the app ? Just uploaded it 2 github.

**Comment by mruiter** [comment]
V 2.1.1 has corrections on the settings of the plug v2 . Should fix that. Pending appstore release

**Comment by pjmpessers** [comment]
Thank you, Marco. That did help. everything is running great again.

**Comment by mruiter** [comment]
Thx for the feedback
