### ISSUE TITLE
Neo Coolcam Uppdate 2.11

### ISSUE THREAD

**Issue by Tordjohnsson** [mruiter/com.neo#126]

**Comment by rgobyn** [comment]
The double wall switches are not recognised by Homey pro since this update !!!
They were working perfectly before the update. As they are installed in the whole house this is very ennoying !!!
Rebooting,  unplugging for 15 minutes give no result. What now ???

**Comment by mruiter** [comment]
As mentioned in the changelog it has a breaking change on the dual switch . That one has to be removed and paired again.

I am sorry this isn’t clear but that’s just the way athom wants it in its new AppStore

Bèta’s are now a mystery and these breaking changes are now pushed to stable without a clear changelog that the user sees

Verstuurd vanaf mijn iPhone
