### ISSUE TITLE
Touch switches  (double) issues with update 2.1.1

### ISSUE THREAD

**Issue by rgobyn** [mruiter/com.neo#127]
Hi,

My homey pro just updated to the latest neo update.  But since the update all my double touch switches give issues with homey !  The devices are not found ...  They were all working perfectly before the update.  I have rebooted Homey and also pulled it out of the outlet and waited for 15min. Still the results are the same.  How can this be fixed ?

The single switches still work ok.

How can this be helpt ? 

Robin

**Comment by mruiter** [comment]
As mentioned in the changelog it has a breaking change on the dual switch . That one has to be removed and paired again.

I am sorry this isn’t clear but that’s just the way athom wants it in its new AppStore 

Bèta’s are now a mystery and these breaking changes are now pushed to stable without a clear changelog that the user sees 

Verstuurd vanaf mijn iPhone

**Comment by BartMeulHome** [comment]
Hey  
I have the same issue
Created a diagnostics file 05764a36-61dd-489f-9c6a-f51385d92292
If i check the divices in developer site they are still reachable in the zwave network

**Comment by mruiter** [comment]
Did you already do a remove from zwave Ann re-pair again ? That should do it and is also mentioned in the changelog as breaking change for the wall switches 

Verstuurd vanaf mijn iPhone

**Comment by Emile86** [comment]
All of my double switches are gone :(

Athom is going wrong way last time with this crazy ideas

**Comment by fvanbeenen** [comment]
I have the same problem. i can/t remove it from mij apps (to install it from scratch.  Please help. Or downgrade.

**Comment by mruiter** [comment]
Remove can always be done . 

Verstuurd vanaf mijn iPhone

**Comment by Emile86** [comment]
![Screenshot_20191207-163032_Homey](https://user-images.githubusercontent.com/43245874/70376965-f4789080-190e-11ea-9b42-d2777e825f4c.jpg)

**Comment by fvanbeenen** [comment]
Thanks. But I don’t want to remove. I want it to work. So I thought about it to remove. Homey can’t seem to find the Neo switch.

**Comment by Emile86** [comment]
You have to remove them then add again.
That what I did yesterday.

**Comment by fvanbeenen** [comment]
Oke. Thanks. I will do this.

**Comment by p-2019-t** [comment]
Hi, i have the same problem and i want to delete the wall plug. 
But I’m not able to delete this. I can’t click on the wall plug because of he turning wheel in the upper right corner (see screenshot) 
Does anyone have a tip?

Thanks!

![FB04E239-B65F-4C69-8EF6-FE41FD404624](https://user-images.githubusercontent.com/58639724/70380161-31f11400-1937-11ea-9571-aca52552b10e.jpeg)

**Comment by fvanbeenen** [comment]
That is my problem to.

**Comment by Emile86** [comment]
As I told in my previous post:
Go to homey "settings > zwave>delete zwave device" and tap quickly 3x times on the wall switch.

**Comment by p-2019-t** [comment]
Thanks for your reply. I tried that also. De leds on the switch are blinking red, but i received the following message:
Cannot remove the device

![A199AC43-A31C-4B88-A9F7-37C0A77057F6](https://user-images.githubusercontent.com/58639724/70380794-d592f200-1940-11ea-8a2a-99b20e94fe9a.jpeg)

**Comment by Emile86** [comment]
Restart homey and try again?

**Comment by mruiter** [comment]
SInce no other users report about the question i guess most with trouble have done the re-pair of the device and will close this issue
