### ISSUE TITLE
Error power meter neo power plug update 2.1.1

### ISSUE THREAD

**Issue by johngrinders** [mruiter/com.neo#128]
After updating to 2.1.1, the Power meter shows a negative value of -21474834.81 on all neo coolcam power plug.
![72DDB705-D1F6-47A4-8B1B-2ABD0EF07D6A](https://user-images.githubusercontent.com/13437063/70379562-4507e200-193f-11ea-90b2-ef827d4bbfc0.png)

**Comment by PascalBu** [comment]
Power meter hasn't updated here since update 🙁

**Comment by mruiter** [comment]
There is a fix for the negative value in the v.2.1.2 version . reporting stops because of the low value and the newer homey mesh driver crashing. So this version should fix the negative and the not reporting in.
