### ISSUE TITLE
NEO Dual and Single switches stoped work

### ISSUE THREAD

**Issue by BoWahlden** [mruiter/com.neo#130]
All my switched both dual and single stopped work after the 2.1.1 version was updated and is not possible to edit the device
The icon is just showing an working rund circle up in right corner.
If i try to add an new switch it's not showing in main site

**Comment by mruiter** [comment]
There is already a issue for this so this one will close.
As stated in the changelog V2.1 series of the driver need a remove from zwave and re-pair to homey again since a big change in the driver.
