### ISSUE TITLE
Neo Coolcam Pir V2 keeps reporting movement

### ISSUE THREAD

**Issue by ICEHUB** [mruiter/com.neo#131]
Hi,

First of all thumbs up on the software you develop for Homey. I keep having problems with all my Neo Coolcam Pir V2's. They either not respond to movement and (most of the time) keep reporting movement. I am resetting, removing and re-pairing them all day long, it is driving me nuts. I know the issue is with Athom, but do you have any suggestions on the best settings to have the least issues? By2way I do have enough Qubino Zwave devices so a Zwave mesh is in place and the Pirs sometimes follow that route. Is it preferable to set them in the associate groups? If so what group(s)?

**Comment by mruiter** [comment]
Have you done a re-pair on the latest V2.1 versions of the app ? Because it now doesn’t get added secure anymore and should have less problems with the secure com problems homey has ?

Verstuurd vanaf mijn iPhone

**Comment by ICEHUB** [comment]
I think I did, when did you release your latest version? What is the best sequence? Remove all Pirs, Remove your app, re-install your app (do I need to wait a few minutes before re-pairing?) Factory reset them and than re-pair? With or without the Qubino devices turned on?

**Comment by ICEHUB** [comment]
Key | Value
-- | --
zw_node_id | "30"
zw_manufacturer_id | "600"
zw_product_type_id | "3"
zw_product_id | "4237"
zw_secure | "⨯"
zw_battery | "✓"
zw_device_class_basic | "BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic | "GENERIC_TYPE_SENSOR_NOTIFICATION"
zw_device_class_specific | "SPECIFIC_TYPE_NOTIFICATION_SENSOR"
zw_firmware_id | ""
zw_application_version | "3"
zw_application_sub_version | "80"
zw_hardware_version | "66"
zw_wakeup_interval | 21600
zw_wakeup_enabled | false
zw_group_1 | "1"
zw_group_2 | ""
zw_group_3 | ""
zw_group_4 | ""
enable_PIR_function | true
motion_blink | false
motion_sensor_sensitivity | "12"
re-trigger_interval | 8
illumination_polling_interval | 1000
illumination_report_threshold | 20
enable_illumination_trigger | false
day_night_treshold | 100
basic_set_level | 255
motion_off_delay | 500
zw_configuration_value | ""

**Comment by ICEHUB** [comment]
secure seems to be off

**Comment by mruiter** [comment]
mmmm........ ANd when you wake up the device (pushing 3 times fast on the button inside ) is the state then reacting again ? Guess yes it will go off on motion but does it go off then after the configured time ?

**Comment by ICEHUB** [comment]
Correct, new alert few seconds ago but than it stays on forever. I reboot your app and Homey, remove the flows etc. Still the alert is on...

**Comment by ICEHUB** [comment]
Temperature and Light are updating perfect on schedule by2way...

**Comment by mruiter** [comment]
You could give the latest github version a try when you run it in debug mode.

Do you know how to use athom clI ?

Please sideload the app to test by the command athom app run . I guess you need to remove 1 plug and then repair . I'm forcing a setting to it on pair.

Please let me know if this brings anything better and also let me know if there are any errors in de console log

**Comment by ICEHUB** [comment]
Do you know how to use athom clI ? No, can you tell me how?

**Comment by ICEHUB** [comment]
I see you pushed the latetst version, when do you think it will be available via Athom, saves me some trouble figuring out Node.js ;-)

**Comment by ICEHUB** [comment]
Hi, I adjusted the Z-wave antenna (as a lot of Homey users did) this improved issues with Zwave a lot, still the PIR's stay unreachable with alert on now and then but do restore after sometime totally random by the way....

**Comment by mruiter** [comment]
So this will stay an issue until athom perfects/corrects zwave core in the core .
Sorry it’s not something I can correct with the app .

Range issue differ from place to place also with the interference that you have locally by neighbors and other wireless signals 

I will close this issue then . Range problems are discussed on the community forums 

Verstuurd vanaf mijn iPhone
