### ISSUE TITLE
touch switches flow card : Stel touch switch led   does not work

### ISSUE THREAD

**Issue by rgobyn** [mruiter/com.neo#132]
Hi,

De kaart : stel touch switch led   die je bij de touch schakelaars in een flow kan bedienen werkt niet.
Dit werkt voor geen enkele van mijn touch schakelaars ( enkel en dubbel ). 
Bij de instellingen van de schakelaars rechtstreeks in de app werken deze functies wel. 

Zou je dit eens kunnen checken aub?

Alvast bedankt,
Met vriendelijke groeten,

Robin

**Comment by mruiter** [comment]
duplicate issue

https://github.com/mruiter/com.neo/issues/85
