### ISSUE TITLE
morza neo coolcam nas pd02z

### ISSUE THREAD

**Issue by manthey323** [mruiter/com.neo#133]
hy
I can not change the tone, etc. with a flow only in the app is it right
how can i donat 

Please don't wonder,  the text is curiously because I can only move my head. Thank you for your understanding.

Kind Regards
Jürgen Manthey
German

![Screenshot_02_01_20__11_00](https://user-images.githubusercontent.com/47304370/71666754-a1092f00-2d62-11ea-9f26-c10f2dc1f0ce.png)

**Comment by mruiter** [comment]
Fixed in upcomming SDKv3 Version
