### ISSUE TITLE
Reset power meter with METER_RESET

### ISSUE THREAD

**Issue by EricMuhren** [mruiter/com.neo#134]
Hi,

Is it possible to add a toggle switch to the settings part of the wall plug to make it possible to clear the accumulated energy?

In the user manual provided with the powerplug it says it has to be possible by using the METER_RESET command.

Thanks

**Comment by mruiter** [comment]
Should be a flow card for it . With virtual devices you could make a button for it

Verstuurd vanaf mijn iPhone

**Comment by EricMuhren** [comment]
Ah, that's a much better solution :-) It works perfectly, thank you!
