### ISSUE TITLE
NEO COOLCAM NAS-PD02ZT lightsensitive stops reporting.

### ISSUE THREAD

**Issue by pjmpessers** [mruiter/com.neo#135]
My motion sensor NEO COOLCAM NAS-PD02ZT stopped reporting the light sensitive for 4 days. After removing the battery it is back for a few times and then stops again. Motion detection and temperature read outs has no problems.

Could this be fixed?

**Comment by mruiter** [comment]
This is a homey core issue on there half backed zwave solution .

Please report issues like this At support@athom.com

This is not something I can fix in the App

Verstuurd vanaf mijn iPhone

**Comment by pjmpessers** [comment]
Thank you for your quick response. The issue is with the NEO COOLCAM NAS-PD02ZT. But i also have the NEO COOLCAM NAS-PD02Z that has no issues. Is it then still a homey z-wave core problem?


-------- Oorspronkelijk bericht --------
Van: Marco Ruiter <notifications@github.com>
Datum: 04-01-20 06:15 (GMT+01:00)
Aan: "mruiter/com.neo" <com.neo@noreply.github.com>
Cc: Pieter <pieterpessers@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [mruiter/com.neo] NEO COOLCAM NAS-PD02ZT lightsensitive stops reporting. (#135)

This is a homey core issue on there half backed zwave solution .

Please report issues like this At support@athom.com

This is not something I can fix in the App

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
You could try a reset to factory on the failing . Should be in the manual . It will delete all settings if one was incorrect 

But homey zwave core has a lot off issue and getting worse . At least you have the lux.
Lots of peeps report false motion triggers on there fibaro aeotec or neo pirs.

And ofc a lot of other zwave issues like no s2 security support that al new devices now have and no flirs support that makes zwave smartlocks and thermostats useless in combination with homey

Verstuurd vanaf mijn iPhone

**Comment by pjmpessers** [comment]
Thank you, Marco.

Then i waait for a update from homey. And hooguit the wil fix this quick.


-------- Oorspronkelijk bericht --------
Van: Marco Ruiter <notifications@github.com>
Datum: 04-01-20 06:29 (GMT+01:00)
Aan: "mruiter/com.neo" <com.neo@noreply.github.com>
Cc: Pieter <pieterpessers@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [mruiter/com.neo] NEO COOLCAM NAS-PD02ZT lightsensitive stops reporting. (#135)

You could try a reset to factory on the failing . Should be in the manual . It will delete all settings if one was incorrect

But homey zwave core has a lot off issue and getting worse . At least you have the lux.
Lots of peeps report false motion triggers on there fibaro aeotec or neo pirs.

And ofc a lot of other zwave issues like no s2 security support that al new devices now have and no flirs support that makes zwave smartlocks and thermostats useless in combination with homey

Verstuurd vanaf mijn iPhone
