### ISSUE TITLE
illumination report treshold (lux) of the NAS-PD02ZT won't change.

### ISSUE THREAD

**Issue by pjmpessers** [mruiter/com.neo#137]
My PIR isn't reporting it's illumination for almost a day. When i place the pir somewhere on a bright day it reports 140 or more lux in also less then a second. Placing it in the dark it goes to 0 lux in seconds. Bringing it back in daylight it goes back to 130 lux. So it seems big changes will be reported. In the advanced settings of the PIR i changed the illumination report treshold #9 from 100 to 1. When saving it says something like:"Settings will be saved the next wake up of the battery device.". But the illumination is still only reported when there is a big difference in illumination. Not small changes of a few lux. So it never does, because it's placed in a oom with very low lightning.

Do i do something wrong?   

P.S. Standard Illumination report treshold = 100 lux

**Comment by mruiter** [comment]
You need to wake up the device when you push setting by pushing the button inside 3 times and then push ok on the setting chance 

Verstuurd vanaf mijn iPhone

**Comment by pjmpessers** [comment]
Thank you.

It seems that this did the trick. I thought that "wake up" meant detecting something. Didn't know that this means pushing the button 3 times. But it worked.

Thanks again.


-------- Oorspronkelijk bericht --------
Van: Marco Ruiter <notifications@github.com>
Datum: 13-01-20 17:19 (GMT+01:00)
Aan: "mruiter/com.neo" <com.neo@noreply.github.com>
Cc: Pieter <pieterpessers@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [mruiter/com.neo] illumination report treshold (lux) of the NAS-PD02ZT won't change. (#137)

You need to wake up the device when you push setting by pushing the button inside 3 times and then push ok on the setting chance

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Zwave sometimes is a mystery . Nevertheless homey should have it ready when the devices wakes up for a second for let’s say a motion defect . But most of the time homey is 2 slow to push the settings in those short wake times 

The push 3 times wakes up the device for 30 seconds so time enough to push the settings 

Verstuurd vanaf mijn iPhone

**Comment by pjmpessers** [comment]
Thank you for explaining. Now i understand. Thanks. Did the trick.


-------- Oorspronkelijk bericht --------
Van: Marco Ruiter <notifications@github.com>
Datum: 13-01-20 18:32 (GMT+01:00)
Aan: "mruiter/com.neo" <com.neo@noreply.github.com>
Cc: Pieter <pieterpessers@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [mruiter/com.neo] illumination report treshold (lux) of the NAS-PD02ZT won't change. (#137)

Zwave sometimes is a mystery . Nevertheless homey should have it ready when the devices wakes up for a second for let’s say a motion defect . But most of the time homey is 2 slow to push the settings in those short wake times

The push 3 times wakes up the device for 30 seconds so time enough to push the settings

Verstuurd vanaf mijn iPhone
