### ISSUE TITLE
PIR v1 is added as PIR v2

### ISSUE THREAD

**Issue by macfreek** [mruiter/com.neo#138]
More of a question than a bugreport.

I have five Neo Coolcam PIT v1, from the looks of it (I can't find a product code or serial number on the outside). When I add the first, it is added as I selected, a PIR v1. However, when I add the other ones, even when I select a PIR v1 in the Homey "add device" menu, and I see a PIR v1 picture during the addition process, after pairing, the added device is a PIR v2(!), given from the picture, the name ("PIR V2") and different order or advanced settings (parameters).

My question, how does this happen, when I explicitly select a PIR v1 during addition?
And how can I enforce that I really add a device as a V1?

With the device that is added as a V1, I can change the settings in the advances parameters, but for the devices added as a V2, I get a timeout every time.

**Comment by mruiter** [comment]
No matter what you select in homeys apps and pictures it’s just for show .

The devices selection and addition by homey is done by its firmware ids .
So you can just select add device -> homey -> zwave and it will select the right app an devices for you



Verstuurd vanaf mijn iPhone
