### ISSUE TITLE
NAS-PD02ZE incorrect blind time window

### ISSUE THREAD

**Issue by JimKoene** [mruiter/com.neo#141]
Blind time setting #6 is limited in the app between 0-8 seconds. According to documentation the setting should be:

6. Re-trigger Interval Setting
This Parameter can be used to adjust the interval of being re-triggered after the PIR
detector has been triggered. No report will be sent during this interval if a movement
is presented. This Parameter value must be less than Parameter 2#

Function: Re-trigger Interval Setting.
Parameter Number : 6
Parameter Size：1 Byte
Available Settings：5 ~ 120(s)
Default Setting：10

**Comment by mruiter** [comment]
Should be fixed in the lastest version of the app
