### ISSUE TITLE
Neo Coolcam Plug 2500 W could be added as generic device only

### ISSUE THREAD

**Issue by Doublenik8** [mruiter/com.neo#142]
Tried to add in secure more and in insecure modes. All the way the same result: plug added as generic Homey device. Switched off other ZWave devices (3 Qubino dimmers) and tried again with no luck. Is there a possibility I have a device with different firmware compare to ones you plugin serves?
I attached device description out of Homey: 
![2251 7](https://user-images.githubusercontent.com/58573155/75119302-a44dd680-5692-11ea-898c-ce2a1f4c9964.jpeg)
￼

**Comment by mruiter** [comment]
I will add the new device ID's to the next app update.
Thx for reporting. Hope the app will hit appstore later this week

**Comment by mruiter** [comment]
Its already available for testing at:

https://homey.app/a/com.neo/test/

**Comment by Doublenik8** [comment]
Thank very much for the information. 
I shall certainly install the new app when I’ll return back home in several weeks time. 

Best regards,
Nikitin

**Comment by Doublenik8** [comment]
Hi,

Just installed the plug using the recommended software—works like Swiss clock, thank you.
The plus was recognized as ver 2 and has all nescessary details re power consumption.

Best regards,
Nikitin

**Comment by mruiter** [comment]
Thx for the feedback , great it works 👍

Verstuurd vanaf mijn iPhone

> Op 22 mrt. 2020 om 20:11 heeft Doublenik8 <notifications@github.com> het volgende geschreven:
> 
> ﻿
> Hi,
> 
> Just installed the plug using the recommended software—works like Swiss clock, thank you.
> The plus was recognized as ver 2 and has all nescessary details re power consumption.
> 
> Best regards,
> Nikitin
>
