### ISSUE TITLE
one issue 2 Enhancements PIR V2.

### ISSUE THREAD

**Issue by ronald2404** [mruiter/com.neo#144]
Hello Marco,

First of all thanks for your great work that you delivered so far.
I have an small issue on PIR V2.  The issue is after battery replacement the device still reports with empty battery after few days.

Then I also have some enhancements. 
1 Disable functions like light sensor and movement  sensor as i only use it for temperature. I tried the advanced options where you enable and disable some options but that didn't help.  (this will safe battery life)
2 Temperature calibration I would like to calibrate the tempature sensore with 0,5 or 1 Degree

Thanks for your support.

Regards
Ronald

**Comment by mruiter** [comment]
Added in the upcomming SDK V3 version
