### ISSUE TITLE
PIR v2 as generic device

### ISSUE THREAD

**Issue by gbone001** [mruiter/com.neo#147]
Hi

I have 2 of the PIR v2 and both will only register as a generic device, i have PTP, put the device close to Homey and tried dozens of times, still no luck. I have searched the forums and nothing has worked to date. Running homey on latest 4.1.

**Comment by mruiter** [comment]
You have new or missing device Ids

Could you send me the device , product and manufacture Ids that you see when it’s added as a generic device and open the properties of the device so I can add them in the next release ?

**Comment by gbone001** [comment]
of course!

**Z-Wave Motion Sensor(PIR)2**


https://szneo.com/en/products/show.php?id=197


Technical Data
Dimensions 45 x 45 x 48 mm
Weight 25.14 gr
Hardware Platform ZM5101
EAN 6924715906508
IP Class IP 20
Voltage 3V
Battery Type 1 * CR123A
Device Type Multilevel Sensor
Firmware Version 03.50
Z-Wave Version 04.26
Z-Wave Product Id 0x0258.0x0003.0x108d
Supported Command Classes
• Basic
• Sensor Binary
• Sensor Multilevel
• Association Grp Info
• Device Reset Locally
• Zwaveplus Info
• Configuration
• Alarm
• Manufacturer Specific
• Powerlevel
• Battery
• Wake Up
• Association
• Version

**Comment by gbone001** [comment]
Also this! Any idea when the update will happen?

**Comment by Nreall** [comment]
Hi! @mruiter unfortunately having the same issue as @gbone001 here are my id's

Device ID: 11
manufacture ID: 600
Product type ID: 512
Product ID: 4145

Hopefully you are able to add these to the next release.

With regards,

Wietse

**Comment by mruiter** [comment]
I will add them .next week I will have some free time to send it to the athom store .

The community store will have the release faster . It already has a newer release there 

Verstuurd vanaf mijn iPhone

**Comment by Nreall** [comment]
> I will add them .next week I will have some free time to send it to the athom store . The community store will have the release faster . It already has a newer release there Verstuurd vanaf mijn iPhone
> […](#)
> Op 3 jul. 2020 om 20:23 heeft Wietse Ouwerkerk ***@***.***> het volgende geschreven: ﻿ Hi! @mruiter unfortunately having the same issue as @gbone001 here are my id's Device ID: 11 manufacture ID: 600 Product type ID: 512 Product ID: 4145 Hopefully you are able to add these to the next release. With regards, Wietse — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Nice! Never knew that existed! https://store.homey.community/ 

Added the new version(2.1.4), but unfortunately the same issue.
Also tested a second PIRv2, with device ID: 13. The reset of the id's are the same.

Thanks for your support in advance!

**Comment by mruiter** [comment]
I think the new version with you’re ids will be available in the community store this weekend depending how fast I finish my girlfriends project 🙈

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Added and submitted for athom store release

**Comment by Nreall** [comment]
@mruiter is it also possible to put the latest version in the Community store? Athom store takes a while unfortunately.

**Comment by mruiter** [comment]
Its in the store if you put /test behind the url of the neo page in the AppStore of athom 

Verstuurd vanaf mijn iPhone
