### ISSUE TITLE
cant set parameter "alarm duration time" on NAS-WS01ZE Flood Sensor   

### ISSUE THREAD

**Issue by matrover** [mruiter/com.neo#148]
i want to set this parameter to 0, the text shows this is accepted by the device. but the input field in the app doesnt allow 0 as the minimal value is 1 

*sorry for the dutch text in the screenshot. 
![image](https://user-images.githubusercontent.com/18408057/79220617-9c214480-7e54-11ea-8189-fc0dcda095da.png)

**Comment by mruiter** [comment]
Will be fixed in next version
