### ISSUE TITLE
Does not connect to Wall Switch with SmartStart function 

### ISSUE THREAD

**Issue by xristiaan** [mruiter/com.neo#152]
I bought some new Neo Coolcam dual wall switches that have a smartstart function for easy inclusion. I found out that the normal inclusion method that worked for the older switches does not seem to work anymore. The model (of the pcb at least) is light_control_V11 20190107, so from last year I assume.

**Comment by mruiter** [comment]
Smart start isnt supported with the new way inclusion works on homey . You have to set the pair mode twice. First for a remove an second for a add. 

So you will have to put the switch into manual pair mode .. Homey will ask for this twice.
The manual should say how to put them into inclusion/pair mode
