### ISSUE TITLE
Neo Coolcam Wifi IR Remote

### ISSUE THREAD

**Issue by Prom0** [mruiter/com.neo#155]
Hey Marco,

I was wondering if this product will be added to the support list?

[#Aliexpress € 9,34  30%OFF | Neo Coolcam Wifi Ir Remot Controle Universal Smart Remote Controller Voor Airconditioner Tv Ondersteuning Echo Smart Home Automation https://a.aliexpress.com/_BPTTLS](Neo Coolcam Wifi IR Remote) 

Bart

**Comment by mruiter** [comment]
This app is for the z-wave versions of the Neo Coolcam products . I dont think it will be added to this app soon.
