### ISSUE TITLE
New Zigbee PIR Sensor

### ISSUE THREAD

**Issue by Patriciawa** [mruiter/com.neo#159]
Hi,

So I noticed Neo Coolcam has a new PIR Sensor based on Zigbee, can this be supported since it's Zigbee?
Here's the link on [Aliexpress](https://a.aliexpress.com/_BPJjn9) 
It has a temperature, motion and humidity sensor, also a 'anti dismantle' function.

Thanks,

Patrick

**Comment by mruiter** [comment]
We will have to wait until the new zigbee core rewrites comes out .

**Comment by mruiter** [comment]
I started on the new sdkv3 app .
When released it will have the zigbee devices 2
