### ISSUE TITLE
New Sensor not supported yet?

### ISSUE THREAD

**Issue by amuetste** [mruiter/com.neo#160]
Hi Marco, I'm the (currently not so happy) owner of what appears to be a new sensor generation by Neo. It is designated NAS-DS07Z1U. Also see link: https://www.robbshop.nl/raam-deursensor-z-wave-plus-met-usb-voeding-neocoolcam 

Any chance you are willing to produce an update for the Neo app for Homey so it works? 

Let me know if you desire additional info. 

Kind regards,

**Comment by mruiter** [comment]
You should be able with the test version of the app

Just put /test behind the url of the neo app webpage in athom store 

Or install it from the community App Store 

HTTPS://Store.homey.community 

Verstuurd vanaf mijn iPhone

**Comment by amuetste** [comment]
Hey Marco, 

can I just install that over the current version? I've got a lot of Neo sensors and I hate it to have them all deinstalled or something else. 

thanks!

**Comment by amuetste** [comment]
Never mind, hij doet 't al :)

**Comment by amuetste** [comment]
Just wanted to let you know: Up to now it works like a charm. No issues experienced.
