### ISSUE TITLE
Problems with PIR V2

### ISSUE THREAD

**Issue by henkbart** [mruiter/com.neo#161]
Hello,
I have some problems with the PIR V2 with Homey 4.2.0
I already have 8 of them working fine here, but i recently bought 2 more. And the problem started, that i could not add them with versie 2.1.3. I got NO apps available error.
I then installed version 2.1.8.
With this version i could install them.
But when i changed the settings (Detection On time) to 10 seconds and i update the device, no changes are working.
When checking the settings, the show alright, but the device keeps showing movement detected. That is for 60 seconds witch is the default value.
So i think something is going wrong somewhere.
Can you help me??
Henk

**Comment by mruiter** [comment]
Fixed in the new release that’s lending App Store release
