### ISSUE TITLE
Error connecting to new neo coolcam switches

### ISSUE THREAD

**Issue by xristiaan** [mruiter/com.neo#162]
I get an error message trying to connect to a newer model of the neo coolcam  dual switch (older ones work fine)

The error message is: status.missing_MultiChannelNodeId_3_on_node

**Comment by mruiter** [comment]
What version of the app are you using ?

**Comment by xristiaan** [comment]
Hi Marco,

Thanks for getting back to me. The version of the app is 6.1.0.633, that should be the latest

Chris

**Comment by mruiter** [comment]
I mean the version of the neo coolcam
App . That’s not it since i never released a version numbering like that for the app

**Comment by xristiaan** [comment]
I thought you meant the version of the homey App. The version of the Neo
Coolcam app is 2.1.9 just updated

Chris

Marco Ruiter <notifications@github.com> schrieb am Fr., 16. Okt. 2020,
22:47:
