### ISSUE TITLE
Neo Coolcam Motionsensor Z-Wave Plus 2 not working (NEO_PD03Z)

### ISSUE THREAD

**Issue by timdoup** [mruiter/com.neo#163]
Dear Marco,
My Neo Coolcam Motionsensor Z-Wave Plus 2 is not working in Homey. I bought them early July but they are not recognised. They are seen as a generic device. I noticed they have product code NEO_PD03Z, and you mention support for PD02Z. When will PD03Z be supported?

Kind regards,
Tim

**Comment by mruiter** [comment]
Already supported in the test version of the app . Put /test behind the url of the AppStore 

Am rewriting the app to sdkv3 homeycompose so new version should be available in next weeks in store 

Verstuurd vanaf mijn iPhone

**Comment by timdoup** [comment]
Thanks for the link to the test environment. I was now able to add the v2 motion sensors with the 2.1.8 app.
