### ISSUE TITLE
problem with neo siren and neo powerplug

### ISSUE THREAD

**Issue by pjmpessers** [mruiter/com.neo#164]
Thank you for updating this app to SDKv3. Most of the things work, but there is a problem with the neo siren (productid 4232) and the powerplug (productid 4231). All of this is not usable and get the message:  

"error. Please replace 'new flowCard()' with 'this.homey.flow.getCard()'

**Comment by mruiter** [comment]
Well who told you 2 install a half finished pile of code ? 😂

Verstuurd vanaf mijn iPhone

**Comment by pjmpessers** [comment]
your right. I always try to improve homey, But it is not smart from my side. Just wanted to let you know what bugs there are. But what i noticed right now is that you already now that there are some small problems and you didn't place this beta app to get information with the question: "Are there bugs in the app", but just placed it as a project in progress. 

My mistake.

**Comment by mruiter** [comment]
Most things are finished . Only the action and trigger cards still need to be updated to sdkv3

Verstuurd vanaf mijn iPhone

**Comment by pjmpessers** [comment]
Thank you for the app update. I understand the the conversion to SDKv3 is not easy. Especially with so many devices in one app. I will wait for the final release. Like i should done it before. Or leave a comment only when the app has reached his final.

**Comment by rlucian** [comment]
I see this was closed, but I am still getting the same error. see new issue #233 reporting by someone else...
