### ISSUE TITLE
Neo Coolcam Water sensor

### ISSUE THREAD

**Issue by Baronnetje** [mruiter/com.neo#165]
I can't connect the Neo Coolcam Z wave plus  water sensor. Homey 5.0 en app experimental. The app doesn't recognize the sensor at all.
Already resetted to default settings. Then triple push on the button en the red light blinks 5 times.

**Comment by mruiter** [comment]
It should show up as unknown generic devices . Does it do that ? 
If so I need the device product and manufacture Id to add the version of the product 

If it doesn’t add at all it’s a communication error between the device and zwave chip in homey . Did it ever work before . If so do a device reset 2 default like in the manual 

If it doesn’t do anything at all check that you have the right version . There are WiFi version out there . Also check that you have the rig he frequentie that corresponds to the zwave regio of you’re honey . Different parts of the world have different frequenties and you can’t mix 

Verstuurd vanaf mijn iPhone

**Comment by Baronnetje** [comment]
Hello Marco,

 

Thank you fort he quick response.

 

I have answered your questions below in red.

 

Yours sincerely,

Jacques

 

Van: Marco Ruiter <notifications@github.com> 
Verzonden: vrijdag 16 oktober 2020 16:32
Aan: mruiter/com.neo <com.neo@noreply.github.com>
CC: Baronnetje <jmmderks@ziggo.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [mruiter/com.neo] Neo Coolcam Water sensor (#165)

 

It should show up as unknown generic devices . Does it do that ? Unfortunately not.
If so I need the device product and manufacture Id to add the version of the product 

If it doesn’t add at all it’s a communication error between the device and zwave chip in homey . Did it ever work before .

It’s a new one.

If so do a device reset 2 default like in the manual 

 

Reset is pushing the black button for a long time till the red light flashes. I did, but no response.

If it doesn’t do anything at all check that you have the right version . There are WiFi version out there . Also check that you have the rig he frequentie that corresponds to the zwave regio of you’re honey . Different parts of the world have different frequenties and you can’t mix 

It’s Z Wave Plus 868,4 MgH Europe



Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Since it doesn’t even show up as generic device it seems that there is no communication between homey and the devices . 

If other zwave devices do pair with you’re homey it’s most likely broken 😞 


Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Since it doesn’t even show up as generic device it seems that there is no communication between homey and the devices . 

If other zwave devices do pair with you’re homey it’s most likely broken 😞 



Verstuurd vanaf mijn iPhone

**Comment by Baronnetje** [comment]
This is the flood sensor.
.https://nl.aliexpress.com/item/32787289062.html?spm=a2g0s.9042311.0.0.53344c4dosDofx

**Comment by Baronnetje** [comment]
Werkt inmiddels na het verwijderen van diverse z wave apparaten. Bedankt voor je medewerking.
