### ISSUE TITLE
Neo coolcam energy value update problem

### ISSUE THREAD

**Issue by whoop-agent** [mruiter/com.neo#169]
There seems to be a problem regarding the value update of the neo coolcam.
It is not updating the energie value.
The 10 hours is really strange, it is connected to my washing machine and it was used twice today
![05BD8D4A-70B9-4122-9030-6475605C19FC](https://user-images.githubusercontent.com/74026484/98305972-21bc3b80-1fc3-11eb-8d3b-f845a6f1e919.jpeg)
![C15C9EF5-3C36-40B6-B722-2092693E6274](https://user-images.githubusercontent.com/74026484/98305974-2254d200-1fc3-11eb-9e38-5636ebd3be79.jpeg)

**Comment by mruiter** [comment]
Reboot homey and reboot plug and wake up plug.
Most likely a zwave core bug in homey when this happens out of the blue or a range /signal jam problem 

Verstuurd vanaf mijn iPhone

**Comment by whoop-agent** [comment]
I tried it and it worked!
Thank you for quick response and solution.

Met vriendelijke groet,

Dave Teunisse

**Comment by mruiter** [comment]
Great thx for letting me know 👌

Verstuurd vanaf mijn iPhone
