### ISSUE TITLE
Neo Coolcam Smartplug recognized as „generic device“

### ISSUE THREAD

**Issue by Ranzkarl** [mruiter/com.neo#170]
Hi,
after just purchasing 2 new Neo Coolcam Smartplugs, they’re recognized as ZWave generic devices in Homey. Attached is the device information page of both plugs. 

Could you please check?

Thanks

Marc

![A3D0C841-3DF6-437F-B80D-40418DF8FAFD](https://user-images.githubusercontent.com/51332189/100613619-20a5d200-3315-11eb-9fff-d07660e96700.png)
![9C788B5B-F3E2-443C-836D-437A56F26D96](https://user-images.githubusercontent.com/51332189/100613625-226f9580-3315-11eb-914f-f25fa9bd8295.png)

**Comment by mruiter** [comment]
This is indeed a completely new device Id . I will add it to the app and publish a test version so you can see if they are working 

Verstuurd vanaf mijn iPhone

**Comment by erwinjong** [comment]
i have the same plugs , can you send me a test version as well ? thanks in advance

**Comment by MP-ICT-Diensten** [comment]
I have the same.

Downloaded the source code and added the numbers, this is now shown in my test Homey:

'''
Property	Value
ID	56518c5a-8b3f-4adc-a21e-6283ae61a2d8
Class	socket
Driver	homey:app:com.neo — NAS-WR02ZE
Ready	Yes
Available	Yes
Warning	No
Custom icon	No

Data
Key	Value
token	"fdda2e0f-f96d-457c-a7c1-f3e145e02d3d"

Settings
Key	Value
zw_node_id	"2"
zw_manufacturer_id	"1050"
zw_product_type_id	"512"
zw_product_id	"8"
zw_secure	"⨯"
zw_battery	"⨯"
zw_device_class_basic	"BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic	"GENERIC_TYPE_SWITCH_BINARY"
zw_device_class_specific	"SPECIFIC_TYPE_POWER_SWITCH_BINARY"
zw_firmware_id	""
zw_application_version	"2"
zw_application_sub_version	"23"
zw_hardware_version	"16"
zw_wakeup_interval	0
zw_wakeup_enabled	false
zw_group_1	"1"
zw_group_2	""
led_display	true
physical_button_enabled	true
meter_report	true
meter_report_interval	300
power_report_change	50
remember_state	true
over_load_current	16
alarm_current	13
time_switch_function	false
time_switch_period	120
energy_alwayson	false
zw_configuration_value	""

Capabilities
Capability	Type	Value	Edit value	Last Updated
onoff	boolean	true	
4 minutes ago
meter_power	number	0		4 minutes ago
measure_power	number	19.81		4 minutes ago
measure_current	number	0.08		4 minutes ago
measure_voltage	number	226.33		4 minutes ago
'''

**Comment by MP-ICT-Diensten** [comment]
This is the manual which comes with it.

[NEO Coolcam NAS-WR02ZE v3.pdf](https://github.com/mruiter/com.neo/files/5674626/NEO.Coolcam.NAS-WR02ZE.v3.pdf)

**Comment by bashuis** [comment]
> This is indeed a completely new device Id . I will add it to the app and publish a test version so you can see if they are working Verstuurd vanaf mijn iPhone
> […](#)
> Op 30 nov. 2020 om 14:06 heeft Ranzkarl ***@***.***> het volgende geschreven: ﻿ Hi, after just purchasing 2 new Neo Coolcam Smartplugs, they’re recognized as ZWave generic devices in Homey. Attached is the device information page of both plugs. Could you please check? Thanks Marc — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Could you please merge the edits from MP-ICT-Diensten, that fixes this problem.

Thnx!

**Comment by erwinjong** [comment]
plugs seem to work fine with the added id's so worth a test version :) . pairing works fast and energy and usage, power and voltage is measured.

i thought i saw a line missing for the german people on some places for both sdk v2 as v3

**Comment by mruiter** [comment]
Added to the new 2.1.10 test version

**Comment by Ranzkarl** [comment]
Hi Marco,

just tested it with the test version and it works like a charm! Thanks for the quick help and update!

Marc

**Comment by mruiter** [comment]
Trying to do the best I can when time is available 💪

Thx for the feedback and good to here al is working out ok 

Verstuurd vanaf mijn iPhone
