### ISSUE TITLE
Neo coolcam PIR V1 is conecting as PIR V3

### ISSUE THREAD

**Issue by bas60** [mruiter/com.neo#171]
My Neo Coolcam PIR V1 has been connected to my network through Homey succesfully for a long time. Because of malfunction I decided to disconnect and re connect the divice again.
Using the app in Homey I tried to connect the divice as PIR V1. Every time the app allows to connect but is connecting as PIR V3. Been connected as PIR V3 the divice does not work!
Please can anyone help me to connect the right device to my network.

**Comment by mruiter** [comment]
Send me the device Ids of the plug please 

Verstuurd vanaf mijn iPhone

**Comment by bas60** [comment]
Marco,

Where can I find  device Ids?

Met vriendelijke groet
Bas Koman

Verstuurd vanaf mijn iPad
