### ISSUE TITLE
Adding new id for neo plug

### ISSUE THREAD

**Issue by Fiek1** [mruiter/com.neo#175]
Dear Marco,

I ordered 2 neo plugs from Ali and they are added as basic device. Can you please add this id? Thank you and keep up the good work.
![IMG-20201211-WA0000](https://user-images.githubusercontent.com/18599711/101944281-bfbbab00-3bec-11eb-9530-f9a77bcb28f7.jpg)

**Comment by MP-ICT-Diensten** [comment]
Is the same issue as this issue:

https://github.com/mruiter/com.neo/issues/170

**Comment by mruiter** [comment]
Added 2 the 2.1.10 test version
