### ISSUE TITLE
PIR V2 seen as V3... config update times out

### ISSUE THREAD

**Issue by Ovide71** [mruiter/com.neo#181]
![35258D66-9EFB-49FA-9FE4-E95F0B2026FF](https://user-images.githubusercontent.com/78273187/106364245-f16c0b00-632d-11eb-9d5e-afc0236307ed.png)
Since the last update, my (new)  NAS-PD02 is seen as V3 and when I try to change the config settings like ‘Led’ or time active, I get a timeout. The PIR’s installed before the update give a message that it will update the sensor once’s it wil be active again.

**Comment by mruiter** [comment]
You need to wake up the sensor before pushing save on the settings . If you don’t do that you get a timeout .

Doesn’t matter if it shows as V2 or v3 .


Verstuurd vanaf mijn iPhone
