### ISSUE TITLE
Temperature on motion sensor intermittently reports 0 (zero)

### ISSUE THREAD

**Issue by Lansuper** [mruiter/com.neo#183]
Since Homey v5 my ‘frost’ flows trigger a couple of times a day for the motion sensor reports zero temperature. Communication and battery are ok and the majority of the time reporting is accurate. 
![154DE80B-BDB3-4CC5-A330-3DC000334F2A](https://user-images.githubusercontent.com/32201989/108962059-7e2d8e80-7678-11eb-98ba-a852582eaf36.jpeg)

**Comment by mruiter** [comment]
Should be fixed in the zwave core now that we are on V6
