### ISSUE TITLE
NAS-PD07 support

### ISSUE THREAD

**Issue by bastrianos** [mruiter/com.neo#186]
I would like to have support for NAS-PD07.
This PIR supports usb and double battery so will be a good add to your app I suppose.
I own several copies of this model and can send you one if you like. Thanks in advance.

**Comment by mruiter** [comment]
Please just supply the device manufactur and product Ids of the device that you can find when it’s added as a generic device in advanced properties

I created the driver already back in October last year but neo could not supply any product yet 

Verstuurd vanaf mijn iPhone

**Comment by bastrianos** [comment]
Hi Marco,

Ik ga het proberen. Dank voor de hulp.

Groeten,
Bas

Op zo 11 apr. 2021 11:41 schreef Marco Ruiter ***@***.***>:

**Comment by Peter-Celica** [comment]
Hoi Marco,
Ik heb sinds vandaag ook een NAS-PD07Z binnen gekregen en wilde hem aan mijn Homey Pro koppelen maar krijg hem alleen als Generic Z-wave device gekoppeld en kan dus geen data uitlezen van de sensor.
Ik begrijp dat je de de ID's wilt hebben, ga ze even voor je hier neerzetten. 
Groet, Peter.

**Comment by Peter-Celica** [comment]
![Screenshot_20210412-191828_Homey](https://user-images.githubusercontent.com/56304467/114434981-ebaf6300-9bc3-11eb-8179-78fe2df8b4ec.jpg)

**Comment by Peter-Celica** [comment]
Hi Marco,
Hopelijk heb je hier iets aan, mocht je nog iets meer willen hebben, laat maar ff weten. 
Alvast bedankt 
Groet Peter.

**Comment by Peter-Celica** [comment]
[Z-Wave_说明书80x80mm PIR07 5in1 S2-中性.pdf](https://github.com/mruiter/com.neo/files/6301835/Z-Wave_.80x80mm.PIR07.5in1.S2-.pdf)
Hierbij de gebruiksaanwijzing mocht je die eventueel nodig hebben. 
Groet Peter.

**Comment by mruiter** [comment]
Ik heb een versie in github staan bij de SDKv2 branche. Mogelijk dat je die kan testen met cli ?

https://github.com/mruiter/com.neo/tree/SDKv2

**Comment by Peter-Celica** [comment]
Hoi Marco,
Heel erg bedankt voor je ondersteuning en je snelle reactie.
Maar weet niet wat ik moet doen om het in mijn Homey app te krijgen en wat
CLI is, sorry daarvoor.

MvG,
Peter van Werkhoven

Verzonden van mijn Samsung Galaxy S8

Op di 13 apr. 2021 10:41 schreef Marco Ruiter ***@***.***>:

**Comment by bastrianos** [comment]
Hi Marco,

Zelfde probleem hier. Ik weet niet wat je bedoelt. Het mooiste zou
natuurlijk zijn als in de homey app deze PIR selecteerbaar is. Thanks
alvast voor jouw antwoord.

Groeten,
Bas


Op di 13 apr. 2021 12:44 schreef Peter-Celica ***@***.***>:

**Comment by mruiter** [comment]
Test version is available under 

https://homey.app/nl-nl/app/com.neo/NEO-Coolcam/test/

**Comment by bastrianos** [comment]
Hallo Marco,

Zojuist getest en het werkt super! Echt enorm bedankt!

Groeten,
Bas

Op di 13 apr. 2021 15:11 schreef Marco Ruiter ***@***.***>:

**Comment by Peter-Celica** [comment]
Hi Marco,

 

Geweldig bedankt hij werkt 😊

Alleen zou je even de tekst aan moeten passen voor het pairen moet je de knop binnenin 5 sec ingedrukt houden totdat de witte LED oplicht en dat 2 keer achter elkaar en niet zoals vermeld 3 x drukken.

Ga hem nu verder testen, zie alle waardes verschijnen tot nog toe.

 

Groet Peter.

 

Van: Marco Ruiter ***@***.***> 
Verzonden: dinsdag 13 april 2021 15:11
Aan: mruiter/com.neo ***@***.***>
CC: Peter-Celica ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [mruiter/com.neo] NAS-PD07 support (#186)

 

Test version is available under

https://homey.app/nl-nl/app/com.neo/NEO-Coolcam/test/

**Comment by Peter-Celica** [comment]
Hoi Marco goeiemorgen,
Even een update over de sensor waarden,
Hoe kan ik de trigger van het Sabotagealarm resetten want deze blijft in
alarmstatus nu al 17 uur na het sluiten van de behuizing ?
En hoe wijzig ik de interval tijd van de Lux en Luchtvochtigheid omdat het
nogal lang duurt voordat deze verversen, heb bij instellingende de interval
op 600 gezet dus verwachte dat hij om de 10 minuten zou verversen maar dat
doet hij niet.
En kan ik ergens een calibratie offset ingeven om de temperatuur en de
luchtvochtigheid bij te stellen.
Alvast bedankt.

MvG,
Peter van Werkhoven

Verzonden van mijn Samsung Galaxy S8

Op di 13 apr. 2021 15:11 schreef Marco Ruiter ***@***.***>:

**Comment by bastrianos** [comment]
Hallo Marco,

Wat Peter zegt, het sabotage alarm blijft geactiveerd en het zou top zijn
dat deze na een paar minuten weer op status "nee" komt. Het gaat slechts om
de trigger namelijk. Ook het lux probleem ervaar ik hetzelfde. De waarde
veranderd pas na 20 minuten ongeveer. In schemertijd is dit een te grote
interval voor flows. Dank alvast.

Groeten ,
Bas

Op wo 14 apr. 2021 10:09 schreef Peter-Celica ***@***.***>:

**Comment by bastrianos** [comment]
Hoi Marco,

Het lijkt erop dat de enige waarde die met regelmaat ververst wordt, de
bewegingssensor is. Zie screenshot voor impressie. Hopelijk lukt het  je
deze aan te passen. Alvast enorm bedankt!

Groeten,
Bas

Op wo 14 apr. 2021 10:09 schreef Peter-Celica ***@***.***>:

**Comment by Peter-Celica** [comment]
Hoi Marco,

Ik had met de Neo Coolcam Testversie app het volgende probleem dat ik een van mijn Scherm controllers niet meer gekoppeld kreeg aan de Homey, heb na heel veel keren proberen uiteindelijk de originele App weer teruggezet en de Controller gekoppeld, hierna kon ik uiteraard de nieuwe PIR sensor niet meer zien en heb de Testversie weer teruggezet en nu werkt alles weer Schermcontroller is wel gewoon blijven bestaan en te bedienen.

Groetjes,
Peter.

**Comment by mruiter** [comment]
Wat bedoel je met scherm controller ?

Verstuurd vanaf mijn iPhone

**Comment by Peter-Celica** [comment]
Hoi Marco,

 

Is de eerste optie in het apparatenscherm om de zonneschermen, Rolgordijnen of Rolluiken te bedienen.

 

MvG,

 

Peter.

 

Van: Marco Ruiter ***@***.***> 
Verzonden: woensdag 21 april 2021 18:06
Aan: mruiter/com.neo ***@***.***>
CC: Peter-Celica ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [mruiter/com.neo] NAS-PD07 support (#186)

 

Wat bedoel je met scherm controller ?

Verstuurd vanaf mijn iPhone

**Comment by bastrianos** [comment]
Hoi Marco,

Tot dusver ben ik erg blij met de mogelijkheden van deze PIR. Zie jij
echter nog een mogelijkheid om de ververs frequentie tussen de Lumen meting
te verkorten? Nu staat deze soms op 2 uur. Wat ik nu dus krijg is dat de
lamp in de gang uit blijft omdat de lichtsterkte hoger is dan de wat de PIR
aangeeft.

Dank je wel.

Groeten,
Bas

Op di 25 mei 2021 18:16 schreef Marco Ruiter ***@***.***>:

**Comment by bastrianos** [comment]
Hi Marco,

Ik heb e gisteren ook weer 1 binnen gekregen en heb het zelfde probleem.
Door de coolcam app wordt deze niet herkend.

En zou je de ververs tijd van de Lumen willen aanpassen naar een hogere
frequentie? Flows op basis van lichtsterkte zijn onbruikbaar.

Deel maar een crypto adres, dan maak ik wat over voor alle moeite.

Many thanks!!

Groeten,
Bas

Op do 27 mei 2021 16:29 schreef roelius01 ***@***.***>:

**Comment by Peter-Celica** [comment]
Hi Marco, hier ook nog hetzelfde verversings frequentie is nog steeds hetzelfde probleem en sabotage alarm knippert ook nog steeds, koppeling weet ik niet omdat de koppeling niet meer verbroken is na het vorige contact.

MvG Peter.
