### ISSUE TITLE
Range van de neo coolcam

### ISSUE THREAD

**Issue by eeckelaertyannick** [mruiter/com.neo#187]
De afstand van de pluggen gaat niet zo ver in huis. Ze verliezen heel vaak connectie. Ik weet niet of dit beter kan. Het hopen van het zwave signaal is ook niet altijd logisch. Ik je. Ook de fibaro plug deze lijkt daar wat beter in. Kan je ook ingeven om het verbruik van de stekker toe te voegen in zowel standbij of als hij aan staat. Bij fibaro is deze optie aanwezig. Dank! Voor de rest op app!

**Comment by mruiter** [comment]
Optie is firmware en niet mogelijk voor neo software bij bij schrijven .
Er zijn vele topics in het community forum over zwave en optimaliseren en mesh hopping .bij de een doet fibaro het slechter bij de.ander neo . Zit ook verschil in de gebruikte zwave chips van de v1,V2,v3 of v4 series van de neo pirs 

Verstuurd vanaf mijn iPhone
