### ISSUE TITLE
NAS-PD07 new ID's

### ISSUE THREAD

**Issue by roelius01** [mruiter/com.neo#190]
Hi Marco,

Today I received my new Neo Coolcam NAS-PD07.
I have already installed version 2.1.11 of your app in Homey Appstore.

After adding the device, it is listed as "Generic Device".
I have compared the ID versions as mentioned in case #186. My device has two other ID, so the solution might be to add them to the supported list of this app...

![NAS-PD07](https://user-images.githubusercontent.com/84919960/119845816-e145f000-bf09-11eb-840e-0adfb60573c2.jpg)

Would that be possible?
Many thanks in advance!

Kind regards,
Roel

**Comment by Rens-H** [comment]
Hi Marco i also have the zwave version now. Its also added as a generic zwave device.

![Screenshot_2021-05-27-19-34-28-046](https://user-images.githubusercontent.com/80253879/119872341-a486f280-bf23-11eb-8e66-69799f2f3a92.jpeg)

Homey diagnostic: 3597ce15-5e45-4caa-b7f5-dfd42cc37544

Can you have a look at this?

**Comment by mruiter** [comment]
Will add the new Ids to the app 

Verstuurd vanaf mijn iPhone

**Comment by roelius01** [comment]
Thanks Marco! 👌

**Comment by Rens-H** [comment]
Thx!

**Comment by bastrianos** [comment]
Hoi Marco,

Ik heb ook twee van deze PIR's met weer een andere ID. Zie screenshot. Zou je tevens de ververs frequentie van de lumens willen verhogen? Flows op basis van lichtsterkte zijn nu niet bruikbaar. Dank je wel!

Groeten,
Bas 
![Screenshot_20210531-135728](https://user-images.githubusercontent.com/82310363/120190807-633f5d00-c219-11eb-9cfb-de90fa23c954.png)

**Comment by mruiter** [comment]
Added in latest version, should be available under /test in 30 minutes

**Comment by bastrianos** [comment]
Hoi Marco,

Apparaat ID50 wordt helaas nog niet gevonden door de app. Zou je hier nog naar willen kijken aub? Een screenshot vind je in deze chat string. De ververs tijd van Lumen werkt nu wel goed bij mijn andere PD07's. Dank daarvoor.

Groeten,
Bas

**Comment by mruiter** [comment]
Dan zit je denk ik niet op firmware v7 en /of de laatste test versie ?
Anders was hij ook via S2 security gepaird en ik zie nu nog unsecure bij je device info staan

**Comment by bastrianos** [comment]
Hoi Marco,

Ik heb de test versie v2.1.11. Geinstalleerd. zie screenshot. Hoe kan ik
een andere versie downloaden? Moet ik hiervoor de huidige app deleten
waardoor mijn flows niet meer werken? Via de app store van homey kan ik
deze niet downloaden zonder conflict met mijn reeds geïnstalleerde versie
namelijk.

Groeten,
Bas

Op vr 4 jun. 2021 12:27 schreef Marco Ruiter ***@***.***>:

**Comment by mruiter** [comment]
Gewoon /test achter de url van de AppStore link

Verstuurd vanaf mijn iPhone

**Comment by roelius01** [comment]
Hi Marco,

Het lukt niet om de nieuwe test versie te installeren.

Als ik de versie erop wil zetten die beschikbaar is gesteld via [](https://homey.app/nl-nl/app/com.neo/NEO-Coolcam/test) dan verschijnt deze melding;
Er is een onbekende fout opgetreden [incompatible_app_version]

Toen ben ik terug gegaan nar versie 2.1.10, en toen weer de /test proberen te installeren, maar dezelfde melding.
Waar zou dat aan kunnen liggen?

**Comment by bastrianos** [comment]
Je moet met Homey naar firmware 7.0. ik ben er nog niet uit hoe dit werkt,
want deze staat niet bij de automatische updates omdat het nog
"experimental" is. Wie weet hoe je dit handmatig kan doen?

Groeten,
Bas

Op vr 4 jun. 2021 14:52 schreef roelius01 ***@***.***>:

**Comment by mruiter** [comment]
Dan zit je zoals gezegd niet op de firmware v7 van homey maar lager .

Lager doet het niet want de nieuwe pirs worden met s2 security gepaird

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Als je naar experimenteel gaat zou ik automatisch update uitzetten en gewoon een paar dagen nadat de versie is gereleased de update handmatig op doorvoeren drukken

Zoek even in de community forums daar staat precies hoe je experimenteel aan kan zetten.

Klinkt experimenteel maar deze versie is verder en vaak ook veel stabieler dan de stable versie . Hoewel je dat aan de benaming natuurlijk niet zou denken 

Verstuurd vanaf mijn iPhone

**Comment by bastrianos** [comment]
Dank je wel Marco,

Voor wie wil updaten. Updaten naar v7.0 kan via de onderstaande link.
 https://tools.developer.homey.app/tools/settings

Groeten,
Bas

Op vr 4 jun. 2021 16:06 schreef Marco Ruiter ***@***.***>:

**Comment by Rens-H** [comment]
Ik kan bevestigen dat het werkt

**Comment by roelius01** [comment]
Ik kan ook bevestigen dat het werkt, top!
Thanks Marco!!

**Comment by mruiter** [comment]
Top . Met s2 security dat met v7 firmware erin zit zou de reporting van Lux etc ook consequenter moeten worden verwerkt door homey .  

Verstuurd vanaf mijn iPhone
