### ISSUE TITLE
New Device Pir Motion Sensor 5in1

### ISSUE THREAD

**Issue by eeckelaertyannick** [mruiter/com.neo#192]
Hi,

i have just recived A new sensor from Ali.
But it not reconized in Homey. Can you add support for the device?

**Comment by mruiter** [comment]
You need to be on firmware v7 of homey and use the /test version of the app .

Can you confirm you are on these ?

Verstuurd vanaf mijn iPhone

**Comment by clipse2004** [comment]
Hi,
I have ordered a motion sensor, but I do not know which version it is. Is always recognized as V3 then it will probably be the ;)
However, I have a permanent motion alarm. 
Also already reconnected several times... no chance. The distance from the homey to the thing is not even a meter :/
i use your latest App Version and homey v7

**Comment by eeckelaertyannick** [comment]
I’m not on the test version of the app. I’m on homey version 7.00rc 15.
Also have problems adding a V2 plug ask me for a DSK but is not on the plug 

Met vriendelijke groet,

Yannick Eeckelaert

**Comment by mruiter** [comment]
That wil be a problem the since as of v7 of the firmware and when a device supports s2 security it needs the pin code to pair . 
Do you see a QR code anywhere on the plug ? Then you can scan it with you’re phone camera to find the pin code 
We can’t force disable secure pairing anymore on v7 if a device supports s2

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
And if you’re not on the test version then the device won’t be supported since athom doesn’t allow the v7 app yet to be published as stable since the v7 firmware is experimental .

Just put /test behind the AppStore url to always have the latest version of any app in the athom App Store 

Verstuurd vanaf mijn iPhone

**Comment by clipse2004** [comment]
> That wil be a problem the since as of v7 of the firmware and when a device supports s2 security it needs the pin code to pair . Do you see a QR code anywhere on the plug ? Then you can scan it with you’re phone camera to find the pin code We can’t force disable secure pairing anymore on v7 if a device supports s2 Verstuurd vanaf mijn iPhone
> […](#)

Yep homey asked for a Code But there is nothing in or on the Package :/ 
I thought the Motion sensor works with s2? :(

**Comment by mruiter** [comment]
Did you look inside ? Mine was there in the shell when you open the battery compartment

**Comment by eeckelaertyannick** [comment]
The pir device was no problem finding it.

But the power plug version 2 I dit not find it on that wane. Gone take a look again today.



Met vriendelijke groet,

Yannick Eeckelaert

**Comment by eeckelaertyannick** [comment]
Hi Marco,

I have ath the moment homey version 7.0.0-RC.15 en de neo app version 2.1.8 downloaded from community store. The powerplug’s work now I put the in he asks the dsk but no dsk on the power plug. So I cancelt the installation but after renuwing the app the plugs ware install… so it works but strange tat he first saw it was not installed. These plug I had in box en are V2 powerplugs. It thing with those plugs the app should not ask the dsk because there is non. The new motion sensor I can stil not add. He puts it in as a simple zwave device. Maybe this one is not setup in the app? Can I send you some date in a way?

**Comment by mruiter** [comment]
Here is the latest test version location

https://homey.app/nl-nl/app/com.neo/NEO-Coolcam/test/

Verstuurd vanaf mijn iPhone

**Comment by clipse2004** [comment]
With me it's the other way around :) 
Power Plug is recognized, it asks for a code, but does not have to enter. Works great.

I just got the info from the seller that there is no code for the PIR sensor :/

**Comment by mruiter** [comment]
Wel there should be a code for the pir
I have 12 of the new pirs and they all have this. But it’s a unique code for every pir 



Verstuurd vanaf mijn iPhone

**Comment by eeckelaertyannick** [comment]
Hi Marco,

The pir is no problem. It has a coded the wall plug’s not. 

Met vriendelijke groet,

Yannick Eeckelaert

**Comment by Rens-H** [comment]
Hi @mruiter  can you add the option tot edit the humidity polling time i think it takes too long to refresh

**Comment by mruiter** [comment]
Plugs should have it on the plug and the box 



Verstuurd vanaf mijn iPhone

**Comment by eeckelaertyannick** [comment]
problem solved, you can close the issue
