### ISSUE TITLE
Water sensor question

### ISSUE THREAD

**Issue by eeckelaertyannick** [mruiter/com.neo#193]
Hi Marco,

I have a question.
I want to use the water sensor to see if my rain barrel is ful ore even megure if ath with level it is. But I’m not shore how to do this. End of the sensor can take it if I put it in the barel as high if possible en use the extension kit to put it lower. The barrel is outside. En is closed but wil stil have some water that wil aeveporate with the sun. Do you have an idea in this question? Watch should I do. 

Thx for answering they’d questions. Pretty new on this

**Comment by eeckelaertyannick** [comment]
?

**Comment by mruiter** [comment]
Creativity support for these kind of mind plays can be discussed at the athom community forums .
I made software support for the device . I never touched one in real life
