### ISSUE TITLE
Neo Coolcam double switch  cannot be added to z-wave network

### ISSUE THREAD

**Issue by xristiaan** [mruiter/com.neo#198]
Hi Marco, 

I currently have version 2.1.10 of the Neo Coolcam app and I am still not able to add part of the Neo Coolcam switches that I have. The difference between the switches is that the ones which I can add have a different version number on the the PCB. I have tried adding the other ones, and they seem to get added as an unknown node.

Hardware version numbers:
.light-control_V9 20170914 (can be added and works without problems)
Light-control_V11 20190107 (cannot be added)

**Comment by mruiter** [comment]
Please supply device/product and manufacturer ID that can be found in setting of the generic device.

**Comment by xristiaan** [comment]
The problem is that it only shows up as an unknown node; can I get the settings of an unknown device as well?

**Comment by mruiter** [comment]
Ofc 
Just open settings 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Or does the node not create a generic device in the homey device list ?

Verstuurd vanaf mijn iPhone

**Comment by xristiaan** [comment]
No it doesn't I only see an unknown device which I can reach

**Comment by xristiaan** [comment]
To be clear, I am using the developer tools

**Comment by mruiter** [comment]
Then this is something for athom since I can only work with devices that are added to homey os

When the device only gets into the zwave chip (only unknown node) I can’t reach it with the app and points to a bug : issue in the homey os 

You should contact atom support for this issue .

I guess the problem is with the s2 security on the newer devices . There where already a lot more devices that didn’t work ok 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Generic device should be in normal honey app . If it isn’t then the devices is only added to the zwave chip inside honey and not further 

You could try a reset to default on the device and try again but the Ids I need if the device gets added as generic devices in the homey app are in the settings on the generic device

Verstuurd vanaf mijn iPhone

**Comment by xristiaan** [comment]
OK, I'll forward it to Homey, thanks for getting back to me

**Comment by xristiaan** [comment]
I have replaced the wall switches with a model that does work.
