### ISSUE TITLE
Not able to add Z-wave repeater

### ISSUE THREAD

**Issue by mpunktnuSupport** [mruiter/com.neo#206]
Hi,

It seems the Z-wave repeater has gotten a hardware update and now has a new ID.

Ordered these in April and got them delivered now in June so they should be latest model. The new ones just get added as a generic z-wave device. Could you update the app so that the new version is able to add?

If you need a physical unit we can ship one free of charge.

Unit ID: 11
Manufacturer ID: 600
Product type ID: 16
Product ID: 1826
Firmware version: 3
Firmware part version: 4
Firmware ID: 5922
Hardware version: 4
Base: BASIC_TYPE_ROUTING_SLAVE
Generic: GENERIC_TYPE_REPEATER_SLAVE
Specific: SPECIFIC_TYPE_REPEATER_SLAVE

**Comment by jonorland** [comment]
I just got this one to with the same ID. On the box it’s written NAS-RP01.

**Comment by mpunktnuSupport** [comment]
Hi,

Is this something that can be fixed. It now applies to the PIR sensors as well.

**Comment by mruiter** [comment]
Added in .16
