### ISSUE TITLE
Neo plugs all data displays 0

### ISSUE THREAD

**Issue by qvc444** [mruiter/com.neo#207]
two Neo Plugs, do not show any energy, power, current and voltage (0 ...)
Probably  V1 and  V2

Best Regards

RST

**Comment by mruiter** [comment]
Remove and rejoin to homey since there are no issues Verstuurd vanaf mijn iPhoneOp 3 aug. 2022 om 18:23 heeft Ben ***@***.***> het volgende geschreven:﻿
two Neo Plugs, do not show any energy, power, current and voltage (0 ...)
Probably  V1 and  V2
Best Regards
RST

**Comment by qvc444** [comment]
Bedankt Marco.
Een stekker na de 4e de en nieuwe installatie is nu OK. De andere stekker (vergeleken met ID-gegevens) anders dezelfde gegevens geen weergave. Getest met versie 1 en 2.

**Comment by mruiter** [comment]
Goed om te horen , soms lijkt homey problemen te hebben als het zwave bereik niet helemaal top is om alle mogelijkheden van de plug (of ander apparaat) goed door te krijgen Verstuurd vanaf mijn iPhoneOp 4 aug. 2022 om 13:22 heeft Ben ***@***.***> het volgende geschreven:﻿
Bedankt Marco.
Een stekker na de 4e de en nieuwe installatie is nu OK. De andere stekker (vergeleken met ID-gegevens) anders dezelfde gegevens geen weergave. Getest met versie 1 en 2.

**Comment by qvc444** [comment]
Bedankt, een stekker met een display is voor mij op dit moment voldoende. Ik laat de andere stekker rusten

**Comment by qvc444** [comment]
laatste vraag. Ik gebruik app-versie 2.1.14. De 2.0.8 wordt aangeboden in de community store.
Welke is beter ?

Ik wens je een rustige avond
