### ISSUE TITLE
PIR devices neo coolcam are added as generic devices, homey says app not found

### ISSUE THREAD

**Issue by CPCremers** [mruiter/com.neo#209]
I have already 4 PIRS from coolcam working perfectly with Homey for almost a year. I bought 3 new PIRS, the same as I already have, but now Homey says that there is no app and the devices are added as generic devices. 

I had installed version 2.1.14 which would not add the devices. I changed it back to 2.1.8, but that also didn't help.

Can this be solved so that the devices can be added and used ? 

![WhatsApp Image 2022-08-13 at 9 33 19 PM](https://user-images.githubusercontent.com/111200142/184508512-7aadd150-1e99-4fc0-9111-66a8c531612e.jpeg)

**Comment by mruiter** [comment]
already issue on github for these new device ids

**Comment by CPCremers** [comment]
Hello,

Thanks for looking into the issue of the Neo Coolcam PIR device ids.

Any idea when this will be solved?

Best regards,

Carl-Peter Cremers



Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
