### ISSUE TITLE
Pro Version does not support Smoke Sensors anymore

### ISSUE THREAD

**Issue by xristiaan** [mruiter/com.neo#211]
Hi Marco,

I just upgraded my app to the Pro Version and saw that I cannot add smoke sensors anymore. The ones I had already installed, are still there, I cannot install new ones.

**Comment by mruiter** [comment]
There are no smoke sensors NEO Z-wave. I think yoy posted on the wrong app github

**Comment by xristiaan** [comment]
Klopt,

dat was een vergissing, excuses

groet
Chris Peters
