### ISSUE TITLE
NAS-WR01B ?

### ISSUE THREAD

**Issue by bergstefan** [mruiter/com.neo#213]
Hi, was looking to buy me some of the cool looking NAS-WR01B Wall plugs, but they are not listed as compatible with your excellent Homey App?

Any plans to add them?

Thanks

**Comment by mruiter** [comment]
Hello Stefan,If I’m not mistaking those are the zigbee versions of they plug .These are rebranded tuya plugs .So you can install the tuya zigbee app from the store . Make sure you are using the latest test version of this app That one supports the zigbee version Verstuurd vanaf mijn iPhoneOp 6 sep. 2022 om 14:56 heeft Stefan Berg ***@***.***> het volgende geschreven:﻿
Hi, was looking to buy me some of the cool looking NAS-WR01B Wall plugs, but they are not listed as compatible with your excellent Homey App?
Any plans to add them?
Thanks

**Comment by bergstefan** [comment]
Aha, gotcha! Thanks.
