### ISSUE TITLE
Fixed power device, but nevertheless no repeater feature

### ISSUE THREAD

**Issue by dxfoxd** [mruiter/com.neo#214]
I currently (and already this entire year have lots of issues with my z-wave network. I have many Neo Coolcam devices, including 7x single wall switch, 2x double wall switch, 9x PIR sensors V2 and V3, 10x Power plugs and 5x door sensors. I have tried to involve the Homey forum and Athom helpdesk, but still no solution. 
The problem is that devices update their status irregularly, but not all status indicators and not every time. Devices (with fixed) are unreachable and cannot be healed. Advanced features of the device cannot be set. For example, I'm able to set the association of a device, but if I try to change the LED setting a network error occurs, hence the setting isn't updated. I also noticed, ant this was a remark from Athom, that a lot of devices are connected without any hub but directly to Homey. As a result, devices are unreachable regularly. Is there any chance that this can be addressed to the app? Home that you can cross out this option, but unfortunately this won't resolve the problems I experience. 

Moreover, can you advise on which app is best to be downloaded, HCS (v2.1.8) or Athom (v2.1.14)? In my opinion HCS always was the repository with the latest app?

Thx. Peter

**Comment by mruiter** [comment]
This cant be adressed in the app. For settings to be applied you need to wake up the device just before you save the settings.
When device report irregular the mess network isnt perfect . There are a lot of possible causes . The forums have many topics about that.
