### ISSUE TITLE
Support for Homey Bridge/Beta

### ISSUE THREAD

**Issue by ramonvanraaij** [mruiter/com.neo#219]
Hello,

will the software/app be updated so that it will support the Homey Bridge/Beta?
At the moment the App-Store shows that the App is not compatible with the new HOMEY Bridge.

Kind Regards,
Rámon

**Comment by mruiter** [comment]
Will not be since a developer needs to pay to get his app available in homey cloud.
Not gonna happen on my side

**Comment by mruiter** [comment]
The app will be updated to sdkv3 for the new homey pro . Maybee athom will make it available for cloud homey 2 then .
