### ISSUE TITLE
Update for the new Homey Pro

### ISSUE THREAD

**Issue by djbakker** [mruiter/com.neo#220]
Hi,

will be there a Version for new HOMEY Pro 2023 in future avaible? At the moment the App-Store shows that the App is not compatible with the new HOMEY Pro.

Kind Regards,
Douwe-Jan

**Comment by pjmpessers** [comment]
I see a v3 in the branch. This one is for the SDKv3. This makes it compatible with the homey pro 2023. Only problem is that it is not working with switches and smart powerplugs, but it seems to work with doorsensors. So it seems he has started with the development with the app making it compatible with homey pro 2023, but neo coolcam made many products.

**Comment by pjmpessers** [comment]
From what i read at the homey 2023 blog https://community.homey.app/t/homey-pro-early-2023-p-review-alpha-testing/75051
 it does work with homey pro 2023. Put we need to to have the homey pro 2023 and sideload the new neo V3 app, if i understood what is working for the homey 2023 pro?

>  The original SOM (System on a Module) is replaced by a complete different Raspberry Pi Compute module and many other internal components are changed.
As it isn’t possible to run the SDK 2 Apps, I needed to install my Own PaperTrails App and a SDK3 fork of the NEO App from CLI to test the devices you see on the table.

>

**Comment by Chopper8** [comment]
Hi! I am using also this app. In the next weeks hope to receive the new Homey Pro. Possible to have a look at the update? Many thanks for your time and effort!

**Comment by djbakker** [comment]
Hi Marco,Dank je voor je melding dat onze vraag is opgelost. Top!Handig om te weten:Probeer jouw testversie 3.0.0 vanuit de homeystore te downloaden maar krijg de melding: er is een onbenkende fout opgetreden  [‘incompatible_app_version’]Vriendelijke groetD-J (Douwe-Jan) BakkerOp 11 mrt. 2023 om 22:22 heeft Marco Ruiter ***@***.***> het volgende geschreven:﻿
Closed #220 as completed.
