### ISSUE TITLE
Homey compatibility >= 10?

### ISSUE THREAD

**Issue by AdyRock** [mruiter/com.neo#226]
Any reason why you have set the "compatibility": ">=10.0.0",?
I have download it and set "compatibility": ">=7.0.0", and it seems to work on my Homey Pro 2018 OK.

**Comment by mruiter** [comment]
Well the app is untested and I have a lot active on older homeys that are using test.Not everything is working yet / is testedDid you have a siren , wallswitches and maybee one of the remotes so you can test for me ?It’s available in the AppStore with >10 so people can test the migration Verstuurd vanaf mijn iPhoneOp 10 feb. 2023 om 12:16 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
Any reason why you have set the "compatibility": ">=10.0.0",?
I have download it and set "compatibility": ">=7.0.0", and it seems to work on my Homey Pro 2018 OK.

**Comment by AdyRock** [comment]
I only have a socket and a motion sensor,  but they are working on my Homey 2018 with the SDK3 version. 
Totally understand your reasoning.
After my Homey 2023 gets another update, I will try to reinstall the backup from my 2018. The last time it was a complete mess, so reset it to factory and switched my 2018 back on. The reason I have installed your SDK3 version on my 2018 is to try and make the next restore a bit less painful 😁
