### ISSUE TITLE
Compatibility Homey 2023

### ISSUE THREAD

**Issue by ChrisGoudt** [mruiter/com.neo#229]
The current version is not compatible with Homey 2023. More information: https://community.homey.app/t/homey-pro-early-2023-app-unsupported-list/70324

**Comment by mruiter** [comment]
Already a H2023 version in test for weeks in the AppStore Verstuurd vanaf mijn iPhoneOp 10 mrt. 2023 om 17:48 heeft Chris ***@***.***> het volgende geschreven:﻿
The current version is not compatible with Homey 2023. More information: https://community.homey.app/t/homey-pro-early-2023-app-unsupported-list/70324

**Comment by ChrisGoudt** [comment]
Thanks, couldn't find that version, installed and tested it, seems to be working fine, thanks!

**Comment by Marcelklim** [comment]
Tried to install the test version, but i do get an error and it won't install. "An unknown error occurred. [incompatible_app_version]. I tried to install on a Homey Pro 2019.

**Comment by mruiter** [comment]
Test version is homey 2023
