### ISSUE TITLE
Neo Siren: When switching modes the melody is incorrect

### ISSUE THREAD

**Issue by Corvo** [mruiter/com.neo#23]
When using the flowcards to switch the Neo Siren's mode: the corresponding melody that was set in the device's config is lost and thus the melody is incorrect.

For now a workaround is to use the "change melody" flowcards before triggering the Siren.
Though this workaround renders the device's config (for melodies) to be unusable.

**Comment by mruiter** [comment]
Hello Corvo,

Yes correct.. And exactly how it should be :)
The flow card pushes a setting change to hardware, the same way you do in the default settings.
So the flow cards are used for changing that default setting that you set on the device.

If you are using the flowcards you can forget those default setting.

**Comment by TedTolboom** [comment]
@Corvo just to clarify... when switching the siren from alarm to doorbell mode, it will also change the tune to the doorbell tune... right? 

Or is the doorbell tune changed?
In the latter case, what happens if you only change the mode within settings? The same should happen...

**Comment by Corvo** [comment]
@TedTolboom  The doorbell tune is different then the one I configured within the device's settings. But switching mode on the device's settings, does work.
