### ISSUE TITLE
Update to 2023 homey Pro 

### ISSUE THREAD

**Issue by Frankenstein2007** [mruiter/com.neo#230]
The motion detector app is not compatible with the new Homey Pro 2023. Can an update be released for this so that the motion detector works again?

**Comment by mruiter** [comment]
Homey 2023 is already available under /test

**Comment by Frankenstein2007** [comment]
![image](https://user-images.githubusercontent.com/127675959/224557220-72391ca9-fdd9-47e2-811b-4d3c04742134.png)

The following screenshot says enough I think. The app cannot be installed in the Homey app either. Is there perhaps another solution that I am overlooking?

**Comment by mruiter** [comment]
The screenshot tells me you didn’t do a search on how to install a test version 🤣Maybee try a community forum search once in a while 🙈But let’s try something freaky . Append /test to the url you get when on the app page 🤫Verstuurd vanaf mijn iPhoneOp 12 mrt. 2023 om 17:09 heeft Frankenstein2007 ***@***.***> het volgende geschreven:﻿

The following screenshot says enough I think. The app cannot be installed in the Homey app either. Is there perhaps another solution that I am overlooking?

**Comment by Frankenstein2007** [comment]
Ah Bedankt!
