### ISSUE TITLE
The app is not compatible / working on the new Homey Pro (Early 2023)

### ISSUE THREAD

**Issue by alexm83** [mruiter/com.neo#231]
Hi MRuiter,
Following the Homey website the Coolcam-app is not compatible / working on a new Homey Pro (Early 2023).
Is it possible to make the app working on it?
Regards, Alex

**Comment by mruiter** [comment]
Already available for moths as most apps under /testVerstuurd vanaf mijn iPhoneOp 13 mrt. 2023 om 17:19 heeft alexm83 ***@***.***> het volgende geschreven:﻿
Hi MRuiter,
Following the Homey website the Coolcam-app is not compatible / working on a new Homey Pro (Early 2023).
Is it possible to make the app working on it?
Regards, Alex

**Comment by alexm83** [comment]
> Already available for moths as most apps under /testVerstuurd vanaf mijn iPhoneOp 13 mrt. 2023 om 17:19 heeft alexm83 ***@***.***> het volgende geschreven:﻿ Hi MRuiter, Following the Homey website the Coolcam-app is not compatible / working on a new Homey Pro (Early 2023). Is it possible to make the app working on it? Regards, Alex —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thanks!
