### ISSUE TITLE
Door Sensor (V1) not working in 2023 (/test) version

### ISSUE THREAD

**Issue by TJWJanssen** [mruiter/com.neo#234]
I can add the sensor with no problem, but there is no data. No alarm and no battery status.
Deleted the sensor (deleting it from Z-wave works well), and then added it. Same problem.

**Comment by mruiter** [comment]
Would it be possible for you to download the lastest verison from github (dont forget to select the v3 branche) and sideload test the app. I switched the command class to a more basic binair and not the notification. Guess something goes wrong in the sdkv3 in catching the notification

**Comment by TJWJanssen** [comment]
Just tested 3.0.1, and it works fine now. Thanks.
The sensor that I removed and added again with version 3.0.0 had to be removed and added again to work in 3.0.1.
The sensor that was automatically converted from homey pro 2019 to 2023 was working fine without removing and adding after the upgrade to 3.0.1.

**Comment by mruiter** [comment]
Thanks for the update
