### ISSUE TITLE
App is not ready for homey pro 2023

### ISSUE THREAD

**Issue by HenkPost** [mruiter/com.neo#235]
Please can you update the homey app Neo coolcam and make ik available for homey pro 2023 (SDK 3)?
I would be very grateful thx Henk

**Comment by mruiter** [comment]
Already available . Please search before creating issues Verstuurd vanaf mijn iPhoneOp 18 mrt. 2023 om 07:05 heeft HenkPost ***@***.***> het volgende geschreven:﻿
Please can you update the homey app Neo coolcam and make ik available for homey pro 2023 (SDK 3)?
I would be very grateful thx Henk

**Comment by mruiter** [comment]
Already available

**Comment by HenkPost** [comment]
Dag Martin,

Als dat zo is, mijn excuses. En… als ik probeer om de app toe te voegen in de AppStore van Homey, wordt daar aangegeven dat de app niet geschikt is voor de pro early 2023, zie bijgaande screenshot.

Of doe ik iets anders fout?

Met vriendelijke groet,

Henk Post
0629560913

Verzonden van mijn iPad, kan een voutje bevatten.
________________________________
Van: Marco Ruiter ***@***.***>
Verzonden: Saturday, March 18, 2023 7:49:47 AM
Aan: mruiter/com.neo ***@***.***>
CC: HenkPost ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mruiter/com.neo] App is not ready for homey pro 2023 (Issue #235)


Already available . Please search before creating issues Verstuurd vanaf mijn iPhoneOp 18 mrt. 2023 om 07:05 heeft HenkPost ***@***.***> het volgende geschreven:﻿
Please can you update the homey app Neo coolcam and make ik available for homey pro 2023 (SDK 3)?
I would be very grateful thx Henk

**Comment by HenkPost** [comment]
Dag Martin,

Nog een foto als ik het toch wil proberen…

Met vriendelijke groet,

Henk Post
0629560913

Verzonden van mijn iPad, kan een voutje bevatten.
________________________________
Van: Marco Ruiter ***@***.***>
Verzonden: Saturday, March 18, 2023 7:50:01 AM
Aan: mruiter/com.neo ***@***.***>
CC: HenkPost ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mruiter/com.neo] App is not ready for homey pro 2023 (Issue #235)


Already available

**Comment by mruiter** [comment]
/test achter de app url toevoegen in de AppStore . Verstuurd vanaf mijn iPhoneOp 18 mrt. 2023 om 07:59 heeft HenkPost ***@***.***> het volgende geschreven:﻿
Dag Martin,

Nog een foto als ik het toch wil proberen…

Met vriendelijke groet,

Henk Post
0629560913

Verzonden van mijn iPad, kan een voutje bevatten.
________________________________
Van: Marco Ruiter ***@***.***>
Verzonden: Saturday, March 18, 2023 7:50:01 AM
Aan: mruiter/com.neo ***@***.***>
CC: HenkPost ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mruiter/com.neo] App is not ready for homey pro 2023 (Issue #235)


Already available

**Comment by HenkPost** [comment]
Top Martin, dank je wel. Dat was het

Fijn weekend

Met vriendelijke groet,

Henk Post
0629560913

Verzonden van mijn iPad, kan een voutje bevatten.
________________________________
Van: Marco Ruiter ***@***.***>
Verzonden: Saturday, March 18, 2023 8:03:21 AM
Aan: mruiter/com.neo ***@***.***>
CC: HenkPost ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mruiter/com.neo] App is not ready for homey pro 2023 (Issue #235)


/test achter de app url toevoegen in de AppStore . Verstuurd vanaf mijn iPhoneOp 18 mrt. 2023 om 07:59 heeft HenkPost ***@***.***> het volgende geschreven:﻿
Dag Martin,

Nog een foto als ik het toch wil proberen…

Met vriendelijke groet,

Henk Post
0629560913

Verzonden van mijn iPad, kan een voutje bevatten.
________________________________
Van: Marco Ruiter ***@***.***>
Verzonden: Saturday, March 18, 2023 7:50:01 AM
Aan: mruiter/com.neo ***@***.***>
CC: HenkPost ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mruiter/com.neo] App is not ready for homey pro 2023 (Issue #235)


Already available
