### ISSUE TITLE
Homey 2023 no support

### ISSUE THREAD

**Issue by StureSture** [mruiter/com.neo#236]
When do you support version 2023 in Homey

**Comment by mruiter** [comment]
As soon as you look further then the top of you’re nose 🤣

It’s already available for weeks as test version

**Comment by StureSture** [comment]
Thanks for the info, but where kan i get it. It is not in the Homey appstore

**Comment by StureSture** [comment]
Hi
Thanks for the info, but where can i get it. It is not in the Homey appstore
Best regards Sture

Den lör 25 mars 2023 14:17Marco Ruiter ***@***.***> skrev:

**Comment by mruiter** [comment]
it is , just add /test to the appstore url .Verstuurd vanaf mijn iPadOp 25 mrt. 2023 om 14:46 heeft StureSture ***@***.***> het volgende geschreven:﻿
Hi
Thanks for the info, but where can i get it. It is not in the Homey appstore
Best regards Sture

Den lör 25 mars 2023 14:17Marco Ruiter ***@***.***> skrev:

**Comment by StureSture** [comment]
Hi
Got an update today. My V2 pluggs dont work now, cant include.
See screendumps
Best regards Sture Johansson
