### ISSUE TITLE
New Firmware for HP23 rc. 73

### ISSUE THREAD

**Issue by Ruediger-P** [mruiter/com.neo#241]
After installing the new rc. 73 today, your app stopped working. The error message is App unavailable or App not installed. I have v. 3.0.7
I only have the powerplugs
Meanwhile I resetted HP23 and now everything works fine again. Sorry for the trouble.

**Comment by mruiter** [comment]
Without any error message supplied I can’t do much about it 🎉Verstuurd vanaf mijn iPhoneOp 6 apr. 2023 om 19:42 heeft Ruediger-P ***@***.***> het volgende geschreven:﻿
After installing the new rc. 73 today, your app stopped working.

**Comment by Ruediger-P** [comment]
Meanwhile I edited the request— Mit nettem GrussRüdiger Prenzel-mobil-Am 06.04.2023 um 20:15 schrieb Marco Ruiter ***@***.***>:﻿
Without any error message supplied I can’t do much about it 🎉Verstuurd vanaf mijn iPhoneOp 6 apr. 2023 om 19:42 heeft Ruediger-P ***@***.***> het volgende geschreven:﻿
After installing the new rc. 73 today, your app stopped working.

**Comment by Ruediger-P** [comment]
Meanwhile I resetted HP23 and now everything works fine again. Sorry for the trouble.

**Comment by JohanvanZanten** [comment]
for me a restart of HP23 did not work, the app is gone and installing the app from the commandline 
✓ Validating app...
Warning: flow.triggers['RC_scene'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_alarm_state'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_siren_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_doorbell_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_alarm_mode'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_alarm_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_doorbell_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['SC01ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['SC02ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['SC03ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
✓ App validated successfully against level `debug`
✓ Packing Homey App...
 — App archive size: 1.78 MB, 267 files
✓ Installing Homey App on `Homey Pro` (xxxxxx)...
× Error

**Comment by mruiter** [comment]
Well the warning are not the problem those cards just don’t have a title format.But then we get a clear error that makes sense …. Not…But are you sideloading it and not from the homey App Store ? Seems more like a homey core issues when sideloading a app Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 15:47 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿
for me a restart of HP23 did not work, the app is gone and installing the app from the commandline
✓ Validating app...
Warning: flow.triggers['RC_scene'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_alarm_state'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_siren_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_doorbell_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_alarm_mode'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_alarm_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_doorbell_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['SC01ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['SC02ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['SC03ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
✓ App validated successfully against level debug
✓ Packing Homey App...
— App archive size: 1.78 MB, 267 files
✓ Installing Homey App on Homey Pro (xxxxxx)...
× Error

**Comment by mruiter** [comment]
A yes you said from command line .Why not install it from the AppStore . Works here ok Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 16:09 heeft Marco Ruiter - Tuxweb ***@***.***> het volgende geschreven:﻿Well the warning are not the problem those cards just don’t have a title format.But then we get a clear error that makes sense …. Not…But are you sideloading it and not from the homey App Store ? Seems more like a homey core issues when sideloading a app Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 15:47 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿
for me a restart of HP23 did not work, the app is gone and installing the app from the commandline
✓ Validating app...
Warning: flow.triggers['RC_scene'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_alarm_state'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_siren_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_doorbell_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_alarm_mode'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_alarm_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_doorbell_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['SC01ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['SC02ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['SC03ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
✓ App validated successfully against level debug
✓ Packing Homey App...
— App archive size: 1.78 MB, 267 files
✓ Installing Homey App on Homey Pro (xxxxxx)...
× Error

**Comment by JohanvanZanten** [comment]
[IMG_0222]

Need I say more?

Sent from my favorite  iDevice

On 7 Apr 2023, at 16:10, Marco Ruiter ***@***.***> wrote:

﻿

A yes you said from command line .Why not install it from the AppStore . Works here ok Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 16:09 heeft Marco Ruiter - Tuxweb ***@***.***> het volgende geschreven:﻿Well the warning are not the problem those cards just don’t have a title format.But then we get a clear error that makes sense …. Not…But are you sideloading it and not from the homey App Store ? Seems more like a homey core issues when sideloading a app Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 15:47 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿
for me a restart of HP23 did not work, the app is gone and installing the app from the commandline
✓ Validating app...
Warning: flow.triggers['RC_scene'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_alarm_state'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_siren_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_doorbell_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_alarm_mode'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_alarm_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['AB01ZE_doorbell_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['SC01ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['SC02ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['SC03ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
✓ App validated successfully against level debug
✓ Packing Homey App...
— App archive size: 1.78 MB, 267 files
✓ Installing Homey App on Homey Pro (xxxxxx)...
× Error

**Comment by mruiter** [comment]
Yes please I don’t see a image just a reference text 🤣Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 16:30 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿
[IMG_0222]



Need I say more?



Sent from my favorite  iDevice



On 7 Apr 2023, at 16:10, Marco Ruiter ***@***.***> wrote:



﻿



A yes you said from command line .Why not install it from the AppStore . Works here ok Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 16:09 heeft Marco Ruiter - Tuxweb ***@***.***> het volgende geschreven:﻿Well the warning are not the problem those cards just don’t have a title format.But then we get a clear error that makes sense …. Not…But are you sideloading it and not from the homey App Store ? Seems more like a homey core issues when sideloading a app Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 15:47 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿

for me a restart of HP23 did not work, the app is gone and installing the app from the commandline

✓ Validating app...

Warning: flow.triggers['RC_scene'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['AB01ZE_alarm_state'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['AB01ZE_siren_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['AB01ZE_doorbell_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['AB01ZE_alarm_mode'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['AB01ZE_alarm_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['AB01ZE_doorbell_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['SC01ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['SC02ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['SC03ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

✓ App validated successfully against level debug

✓ Packing Homey App...

— App archive size: 1.78 MB, 267 files

✓ Installing Homey App on Homey Pro (xxxxxx)...

× Error

**Comment by JohanvanZanten** [comment]
sorry 😥my bad


Deze app is niet compatibel met Homey

Pro (Early 2023).

Deze app is verouderd en vereist een update om op Homey Pro (Early 2023) te kunnen werken. Kom in actie door contact op te nemen met de ontwikkelaar hier.

Neo Coolcam Z-Wave device APP for Homey


Sent from my favorite Certis iDevice

On 7 Apr 2023, at 16:42, Marco Ruiter ***@***.***> wrote:

﻿

Yes please I don’t see a image just a reference text 🤣Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 16:30 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿
[IMG_0222]



Need I say more?



Sent from my favorite iDevice



On 7 Apr 2023, at 16:10, Marco Ruiter ***@***.***> wrote:



﻿



A yes you said from command line .Why not install it from the AppStore . Works here ok Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 16:09 heeft Marco Ruiter - Tuxweb ***@***.***> het volgende geschreven:﻿Well the warning are not the problem those cards just don’t have a title format.But then we get a clear error that makes sense …. Not…But are you sideloading it and not from the homey App Store ? Seems more like a homey core issues when sideloading a app Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 15:47 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿

for me a restart of HP23 did not work, the app is gone and installing the app from the commandline

✓ Validating app...

Warning: flow.triggers['RC_scene'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['AB01ZE_alarm_state'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['AB01ZE_siren_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['AB01ZE_doorbell_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['AB01ZE_alarm_mode'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['AB01ZE_alarm_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['AB01ZE_doorbell_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['SC01ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['SC02ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

Warning: flow.actions['SC03ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.

✓ App validated successfully against level debug

✓ Packing Homey App...

— App archive size: 1.78 MB, 267 files

✓ Installing Homey App on Homey Pro (xxxxxx)...

× Error

**Comment by mruiter** [comment]
Dat komt omdat athom niet in staat is een scheiding te maken tussen een homey pre 2023 en 2023 app . (Zijn ze momenteel net pas mee begonnen )Als je de laatste versie van een app wil wat dus ook nodig is bij de neo app dan vul je achter de url als je op de app pagina zit /test in Dan heb je de aller laatste versie van een app, zo ook de pro 2023 versie 😉Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 17:08 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿
sorry 😥my bad





Deze app is niet compatibel met Homey



Pro (Early 2023).



Deze app is verouderd en vereist een update om op Homey Pro (Early 2023) te kunnen werken. Kom in actie door contact op te nemen met de ontwikkelaar hier.



Neo Coolcam Z-Wave device APP for Homey





Sent from my favorite Certis iDevice



On 7 Apr 2023, at 16:42, Marco Ruiter ***@***.***> wrote:



﻿



Yes please I don’t see a image just a reference text 🤣Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 16:30 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿

[IMG_0222]







Need I say more?







Sent from my favorite iDevice







On 7 Apr 2023, at 16:10, Marco Ruiter ***@***.***> wrote:







﻿







A yes you said from command line .Why not install it from the AppStore . Works here ok Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 16:09 heeft Marco Ruiter - Tuxweb ***@***.***> het volgende geschreven:﻿Well the warning are not the problem those cards just don’t have a title format.But then we get a clear error that makes sense …. Not…But are you sideloading it and not from the homey App Store ? Seems more like a homey core issues when sideloading a app Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 15:47 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿



for me a restart of HP23 did not work, the app is gone and installing the app from the commandline



✓ Validating app...



Warning: flow.triggers['RC_scene'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['AB01ZE_alarm_state'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['AB01ZE_siren_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['AB01ZE_doorbell_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['AB01ZE_alarm_mode'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['AB01ZE_alarm_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['AB01ZE_doorbell_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['SC01ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['SC02ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['SC03ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



✓ App validated successfully against level debug



✓ Packing Homey App...



— App archive size: 1.78 MB, 267 files



✓ Installing Homey App on Homey Pro (xxxxxx)...



× Error

**Comment by JohanvanZanten** [comment]
geweldig, dacht alleen aan de commandline install

maar experimental werkt😝

Sent from my favorite Certis iDevice

On 7 Apr 2023, at 17:41, Marco Ruiter ***@***.***> wrote:

﻿

Dat komt omdat athom niet in staat is een scheiding te maken tussen een homey pre 2023 en 2023 app . (Zijn ze momenteel net pas mee begonnen )Als je de laatste versie van een app wil wat dus ook nodig is bij de neo app dan vul je achter de url als je op de app pagina zit /test in Dan heb je de aller laatste versie van een app, zo ook de pro 2023 versie 😉Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 17:08 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿
sorry 😥my bad





Deze app is niet compatibel met Homey



Pro (Early 2023).



Deze app is verouderd en vereist een update om op Homey Pro (Early 2023) te kunnen werken. Kom in actie door contact op te nemen met de ontwikkelaar hier.



Neo Coolcam Z-Wave device APP for Homey





Sent from my favorite Certis iDevice



On 7 Apr 2023, at 16:42, Marco Ruiter ***@***.***> wrote:



﻿



Yes please I don’t see a image just a reference text 🤣Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 16:30 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿

[IMG_0222]







Need I say more?







Sent from my favorite iDevice







On 7 Apr 2023, at 16:10, Marco Ruiter ***@***.***> wrote:







﻿







A yes you said from command line .Why not install it from the AppStore . Works here ok Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 16:09 heeft Marco Ruiter - Tuxweb ***@***.***> het volgende geschreven:﻿Well the warning are not the problem those cards just don’t have a title format.But then we get a clear error that makes sense …. Not…But are you sideloading it and not from the homey App Store ? Seems more like a homey core issues when sideloading a app Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 15:47 heeft JohanvanZanten ***@***.***> het volgende geschreven:﻿



for me a restart of HP23 did not work, the app is gone and installing the app from the commandline



✓ Validating app...



Warning: flow.triggers['RC_scene'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['AB01ZE_alarm_state'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['AB01ZE_siren_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['AB01ZE_doorbell_volume'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['AB01ZE_alarm_mode'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['AB01ZE_alarm_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['AB01ZE_doorbell_tune'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['SC01ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['SC02ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



Warning: flow.actions['SC03ZE_switch_LED'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.



✓ App validated successfully against level debug



✓ Packing Homey App...



— App archive size: 1.78 MB, 267 files



✓ Installing Homey App on Homey Pro (xxxxxx)...



× Error

**Comment by Dutchman2** [comment]
Bij het installeren van de laatste testversie op mijn Homey Pro 2023 krijg ik helaas ook de volgende foutmelding "Er is een onbekende fout opgetreden [incompatible_app_version]"
Wat kan ik doen om 'm toch geïnstalleerd te krijgen?
Alvast bedankt!
