### ISSUE TITLE
Homey pro 2023 isnt working

### ISSUE THREAD

**Issue by BartBrouwerHOI** [mruiter/com.neo#243]
![IMG_7742](https://user-images.githubusercontent.com/104209973/235340663-149dd12d-da01-4213-8fc0-cef032c31875.png)
I have lots of neo stuff with my old homey.
The new one isnt working with this neo softeware. Will there be an upgrade available ?

**Comment by mruiter** [comment]
2023 version is already out for moths . Some devices such as the remote haven’t been tested by users yet so not released to stable . Just put /test behind te App Store url and you get the 2023 version Verstuurd vanaf mijn iPhoneOp 30 apr. 2023 om 09:15 heeft BartBrouwerHOI ***@***.***> het volgende geschreven:﻿
Closed #243 as completed.

**Comment by BartBrouwerHOI** [comment]
Yeah, iam sorry. I saw it at a later moment. Maybe i could buy a remote for testing? Is it possible to upgrade? Or is it a new app when i install this test version?

**Comment by mruiter** [comment]
I think I will just release it to stable . Guess some peeps with the remote will report then . Or not if it’s working like it should 😜Will release it to stable on Monday Verstuurd vanaf mijn iPhoneOp 30 apr. 2023 om 09:39 heeft BartBrouwerHOI ***@***.***> het volgende geschreven:﻿
Yeah, iam sorry. I saw it at a later moment. Maybe i could buy a remote for testing? Is it possible to upgrade? Or is it a new app when i install this test version?

**Comment by BartBrouwerHOI** [comment]
Oke! Tnx :) i will wait 1 day ;)
Enjoy the sun!

**Comment by mruiter** [comment]
You can just install test and it will update to newer stables automatically Verstuurd vanaf mijn iPhoneOp 30 apr. 2023 om 09:45 heeft BartBrouwerHOI ***@***.***> het volgende geschreven:﻿
Oke! Tnx :) i will wait 1 day ;)
Enjoy the sun!
