### ISSUE TITLE
Please add Support for homey pro 2023

### ISSUE THREAD

**Issue by gooooba** [mruiter/com.neo#244]

**Comment by mruiter** [comment]
Already there for months . See test version since athom does not support homey 2023 only apps Verstuurd vanaf mijn iPhoneOp 5 mei 2023 om 21:43 heeft gooooba ***@***.***> het volgende geschreven:﻿

**Comment by gooooba** [comment]
Thx

**Comment by cj514477** [comment]
In deze Threat wordt gesproken over een app die al beschikbaar is voor de Homey-pro 2023, waar kan ik die vinden?

**Comment by gooooba** [comment]
> In deze Threat wordt gesproken over een app die al beschikbaar is voor de Homey-pro 2023, waar kan ik die vinden?

https://homey.app/en-gb/app/com.neo/NEO-Coolcam/test

**Comment by cj514477** [comment]
Bedankt, de Neo-Coolcam schakelaars werken weer

**Comment by liksvette** [comment]
Had Homey Pro for two days. Could someone explain how to do this:  "See test version since athom does not support homey 2023 only apps" ? I find the NEO coolcam app,  but I get "Invalid SDK: 2" whenver I try to add something.
Thanks.

**Comment by locksen-nl** [comment]
with the latest update  my plugs and PIR sensor  won't update the status anymore only if I reboot the app

**Comment by mruiter** [comment]
Nothing changed for that on the latest update . Guess it’s a homey core , latest update the change log said zwave enhancements. We all know how that goes on homey . Report on slack I see you’re not the only one Verstuurd vanaf mijn iPhoneOp 8 mei 2023 om 17:34 heeft locksen-nl ***@***.***> het volgende geschreven:﻿
with the latest update  my plugs and PIR sensor  won't update the status anymore only if I reboot the app

**Comment by PierreMc** [comment]
@liksvette I'm new to Homey as well (received it today), so just had to try and understand that same thing. 
The developper (mruiter) meant you need to install the test version of the app, which I now know you can only find by accessing the following URL directly (and not by searching for the app): 
https://homey.app/en-gb/app/com.neo/NEO-Coolcam/test

Hope this helps (of course, remember both Homey Pro 2023 and this test app are pre-release versions).

**Comment by W-illi4m** [comment]
+1 Please add Support for homey pro 2023!

**Comment by mruiter** [comment]
If you read the issue you are commenting on you would have seen it’s already there for months 🤣Verstuurd vanaf mijn iPhoneOp 20 jun. 2023 om 12:40 heeft W-illi4m ***@***.***> het volgende geschreven:﻿
+1 Please add Support for homey pro 2023!
