### ISSUE TITLE
Neo Coolcam 

### ISSUE THREAD

**Issue by fvanbeenen** [mruiter/com.neo#246]
Hello 

Neo Coolcam does not seem to work. I downloaded the previous version but also no luck.  Please update.  I can’t use Homey this way. To many things on Neo. Also wall plugs. 

Thanks. 
Freek

**Comment by Ruediger-P** [comment]
I have Version 3.0.7 and everything is working fine.

**Comment by fvanbeenen** [comment]
On the new homey pro 2023?

**Comment by fvanbeenen** [comment]
> I have Version 3.0.7 and everything is working fine.

On the Homey pro 2023?

**Comment by Ruediger-P** [comment]
Yes

**Comment by mruiter** [comment]
Thx for the detailed info . I will go and fix it straight away 🤣🤣🤣🤣

**Comment by pawelwicq** [comment]
Same problem. On Homey Pro Early 2023 there is no option to install the app :(

**Comment by mruiter** [comment]
Just put /test behind the url like mentioned everywhere Verstuurd vanaf mijn iPhoneOp 5 jun. 2023 om 17:21 heeft Paweł Wickowski ***@***.***> het volgende geschreven:﻿
Same problem. On Homey Pro Early 2023 there is no option to install the app :(

**Comment by fvanbeenen** [comment]
I did find the right app to install. Although it doesn’t work.

**Comment by mruiter** [comment]
Well I can’t fix is doesn’t work .What’s the error Verstuurd vanaf mijn iPhoneOp 5 jun. 2023 om 18:34 heeft fvanbeenen ***@***.***> het volgende geschreven:﻿
I did find the right app to install. Although it doesn’t work.

**Comment by fvanbeenen** [comment]
![Uploading IMG_6843.png…]()

**Comment by fvanbeenen** [comment]
Etimedout (5:write)

**Comment by mruiter** [comment]
Image is missing

**Comment by mruiter** [comment]
Etimedout (5:write) Is a internal homey error I can’t fix

**Comment by mruiter** [comment]
That’s a start , and did you ptp the homey already ?Verstuurd vanaf mijn iPhoneOp 5 jun. 2023 om 19:34 heeft fvanbeenen ***@***.***> het volgende geschreven:﻿
You can’t,  but what can I do. Do the installation again?

**Comment by fvanbeenen** [comment]
I don’t know what ptp means, can you explain to me otherwise I’m going to find out. Thank you

**Comment by fvanbeenen** [comment]
Ptp worked. Thank you very much. 😊
