### ISSUE TITLE
Test version

### ISSUE THREAD

**Issue by Xybertecnic** [mruiter/com.neo#247]
Hoi, ik heb de test versie geinstalleerd op mijn homey 2023, en in eerste instantie leek alles ok, maar ik hoorde steeds zomaar een muurstekker schakelen als ik ergens binnen liep, maar daar zit een HUE sensor die enkel het licht in die ruimte schakelt, dus ik snap niet waarom de stekker daarmee even uit en inschakelt. Die stekker zit maar in 1 handmatige flow (alles uit).
Ik heb de stekker even verwijderd in homey, echter nu probeer ik hem toe te voegen, de 1e stap gaat goed (3xindrukken etc), maar daarna krijg ik nu een venster dat ik de pincode moet invoeren van het apparaat (en dan een heel lang nummer eronder), maar er staat helemaal nergens een nummer op? Of doe ik iets fout?

**Comment by mruiter** [comment]
Stekkers gaan alleen maar spontaan uit aan uit aan als ze stuk zijn (defect relais) . Als dat niet het geval is dat is het homey die door een flow het activeert . Lijkt meer op als zone actief wordt apparaten aan of uit achtige flows . Dus dan niet het device zelf ik de flow maar de hele zone waar hij in zit . Dan zie je het device zelf geen flow hebben . Is iig niet iets dat de app voor je doet uit zichzelf Verstuurd vanaf mijn iPhoneOp 8 jun. 2023 om 18:04 heeft Xybertecnic ***@***.***> het volgende geschreven:﻿
Hoi, ik heb de test versie geinstalleerd op mijn homey 2023, en in eerste instantie leek alles ok, maar ik hoorde steeds zomaar een muurstekker schakelen als ik ergens binnen liep, maar daar zit een HUE sensor die enkel het licht in die ruimte schakelt, dus ik snap niet waarom de stekker daarmee even uit en inschakelt. Die stekker zit maar in 1 handmatige flow (alles uit).
Ik heb de stekker even verwijderd in homey, echter nu probeer ik hem toe te voegen, de 1e stap gaat goed (3xindrukken etc), maar daarna krijg ik nu een venster dat ik de pincode moet invoeren van het apparaat (en dan een heel lang nummer eronder), maar er staat helemaal nergens een nummer op? Of doe ik iets fout?

**Comment by Xybertecnic** [comment]
thanks, dat is ook eigenlijk de reden dat ik hem even verwijderd heb, maar vreemde is dat ik gewoon een backup van de oude homey op de nieuwe heb gezet, en voorheen deed hij dat niet. pincode ga ik proberen
