### ISSUE TITLE
Neo Coolcam on Homey Pro Early 2023 Access...

### ISSUE THREAD

**Issue by ketscher1070** [mruiter/com.neo#250]
Hi, 

i want to ask, if you have a schedule to release a compatible app for Homey Pro 2023 Early Access? 

thanks, Markus

**Comment by mruiter** [comment]
Yes about 4 months ago . Available under test is App Store . Athom does not support 2023 only apps since it’s still beta Verstuurd vanaf mijn iPhoneOp 4 jul. 2023 om 10:26 heeft ketscher1070 ***@***.***> het volgende geschreven:﻿
Hi,
i want to ask, if you have a schedule to release a compatible app for Homey Pro 2023 Early Access?
thanks, Markus

**Comment by stef1984** [comment]
Hello… i’m interesting to test the beta app… Please send me link…. Thanks

**Comment by C4mth4** [comment]
Hello… i’m interesting too to test the beta app… Can you send me link? Thanks

**Comment by kristianlauritzen** [comment]
Hello… i’m interesting too to test the beta app… Can you send me link? Thanks

**Comment by MMeuleman** [comment]
Hello Marco,
Any idea when it becomes available in the app store voor Homey Pro Early 2023? Is there a workaround in the meanwhile?
Thanks, Martin

**Comment by mruiter** [comment]
Yes just put /test behind the url in the AppStore Until firmware v10 becomes stable athom does not support the 2023 only app is the store Verstuurd vanaf mijn iPhoneOp 7 aug 2023 om 12:44 heeft MMeuleman ***@***.***> het volgende geschreven:﻿
Hello Marco,
Any idea when it becomes available in the app store voor Homey Pro Early 2023? Is there a workaround in the meanwhile?
Thanks, Martin

**Comment by elflorduk** [comment]
I am adding a request for the app to be updated for honey pro please asap

**Comment by mruiter** [comment]
And the first small asap package is available at a starting price of 1000 euros . It will get you 5 minutes of asap 🤣Verstuurd vanaf mijn iPhoneOp 11 aug 2023 om 23:00 heeft Marco Ruiter - Tuxweb ***@***.***> het volgende geschreven:﻿Already there for almost a year . Read GitHub before making a new post .Verstuurd vanaf mijn iPhoneOp 11 aug 2023 om 22:26 heeft elflorduk ***@***.***> het volgende geschreven:﻿
I am adding a request for the app to be updated for honey pro please asap

**Comment by elflorduk** [comment]
If it is already there, why does it say the app is unsupported and and when you try to use it it says invalid SDK.

**Comment by mruiter** [comment]
Read the topic you posted in 🤪Verstuurd vanaf mijn iPhoneOp 12 aug 2023 om 07:29 heeft elflorduk ***@***.***> het volgende geschreven:﻿
If it is already there, why does it say the app is unsupported and and when you try to use it it says invalid SDK.

**Comment by elflorduk** [comment]
I think you misinterpret the notion of asap.

**Comment by liorstp** [comment]
Hi. I want to be a beta tester. Could you please send me a link?

**Comment by mruiter** [comment]
Read a few post above for the link Verstuurd vanaf mijn iPhoneOp 19 aug 2023 om 10:48 heeft liorstp ***@***.***> het volgende geschreven:﻿
Hi. I want to be a beta tester. Could you please send me a link?

**Comment by wayupnorthguy** [comment]
I have a Homey Pro early 2023 and have several NEO devices.  Door sensors, smart plugs and sirens that I would be interested in beta testing.  Please send a link
