### ISSUE TITLE
Please add Support for Homey pro 2023

### ISSUE THREAD

**Issue by ekeskog** [mruiter/com.neo#254]
Please add Support for Homey pro 2023

**Comment by chrisboer** [comment]
+1

**Comment by mruiter** [comment]
Just read the thread you’re posting I’m .Paying some attention would easy your life 🤣👋Verstuurd vanaf mijn iPhoneOp 22 aug 2023 om 22:23 heeft Chris Boer ***@***.***> het volgende geschreven:﻿
+1

**Comment by chrisboer** [comment]
Sorry, I have read your post and found the test version, it is working thanks @mruiter
