### ISSUE TITLE
Install test version on 2019 pro

### ISSUE THREAD

**Issue by rpkbs** [mruiter/com.neo#259]
Hi,

I have a homey 2019 pro and am considering buying the 2023.

Can I just install the test version over the normal version and will all the neo coolcam plugs work?
Or do I have to newly install all plugs for the test version?

Kind regards,

Robin

**Comment by rpkbs** [comment]
Nobody can answer my question?

Kind regards

**Comment by mruiter** [comment]
gues i missed the mail but yesVerstuurd vanaf mijn iPadOp 2 okt 2023 om 18:43 heeft rpkbs ***@***.***> het volgende geschreven:﻿
Nobody can answer my question?
Kind regards
