### ISSUE TITLE
WiFi

### ISSUE THREAD

**Issue by elflorduk** [mruiter/com.neo#260]
will you be adding support for WiFi devices for Homey Pro 2023?

**Comment by mruiter** [comment]
Wifi devices are supported in another app. This is zwave only .If I’m not mistaken it’s the tuya local connection appVerstuurd vanaf mijn iPhoneOp 18 sep 2023 om 11:24 heeft elflorduk ***@***.***> het volgende geschreven:﻿
will you be adding support for WiFi devices for Homey Pro 2023?
