### ISSUE TITLE
PLEASE make an update for the Neo cool cam app for homey pro

### ISSUE THREAD

**Issue by Titoheld** [mruiter/com.neo#262]

**Comment by mruiter** [comment]
Already there read GitHub issues you created a new one inVerstuurd vanaf mijn iPhoneOp 8 okt 2023 om 08:59 heeft Titoheld ***@***.***> het volgende geschreven:﻿

**Comment by Darekowo** [comment]
Dołączam się do prośby.

**Comment by mruiter** [comment]
bIleghmeH qo' Hoch Dalo'laHbe'
