### ISSUE TITLE
I'd like to get this app on my Homey pro 2023, Best regards 

### ISSUE THREAD

**Issue by GD91a** [mruiter/com.neo#269]
I'd like to get this app on my Homey pro 2023. 
Thank you...

**Comment by Farmands** [comment]
Me too, were much indeed:-)

**Comment by PeterHT** [comment]
So do I!

**Comment by abubashi** [comment]
Hi just bought HomeyPro 2023 and discovered this app doesn't work on it. Please do an update! Thank you in advance.
P.S. Is there a way where I can support your work?

**Comment by mvonrotz** [comment]
Yes, there is a test version that has not been touched, according to the changlog, in 7 month! I have no problems if the developer does not have enough time at the moment, but it should state it clearly in the app description or change log!

**Comment by Showmaand** [comment]
> Hi all, just found out there 's a beta available at https://homey.app/nl-nl/app/com.neo/NEO-Coolcam/test/
> Just installed it, works with HP 2023 and my pir move sensor V2

Thanks PeterHT! I just installed a Coolcam Plug V2 on HomeyPro 2023 via the link you provided. Works OK!
