### ISSUE TITLE
Update for homey pro 2023 

### ISSUE THREAD

**Issue by dd3uk** [mruiter/com.neo#276]
Hi please update this app for homey pro 💪🏻

**Comment by spikehome** [comment]
Yes please waiting for it.
Running the 2019 and te 2023 now:(

**Comment by Leifitaby** [comment]
I have upgraded to Homey Pro 2023. I am very disapointed as I can not use my Neo Coolcam power plugs anymore. Please inform about your plans for an upgrade of the Neo Coolcam app.
Best regards, Leif O.

**Comment by mruiter** [comment]
Disappointment comes with. It looking further then the next tree .Read GitHub 2023 version is already available Verstuurd vanaf mijn iPhoneOp 26 mrt 2024 om 22:33 heeft Leifitaby ***@***.***> het volgende geschreven:﻿
I have upgraded to Homey Pro 2023. I am very disapointed as I can not use my Neo Coolcam power plugs anymore. Please inform about your plans for an upgrade of the Neo Coolcam app.
Best regards, Leif O.

**Comment by spikehome** [comment]
still no update :(

**Comment by mruiter** [comment]
Already there under /test before users got their pro 2023 👋Maybee read some more Verstuurd vanaf mijn iPhoneOp 16 mei 2024 om 14:58 heeft spikehome ***@***.***> het volgende geschreven:﻿
still no update :(
