### ISSUE TITLE
Touch switch not working (does not update state and can't control)

### ISSUE THREAD

**Issue by BLAST3R** [mruiter/com.neo#28]
Hello,

Just received three brand new Touch Switches (2ch EU). Hooked one up to power, and included it in Homey's network. I can update the parameters like enable/disable LED's, but the core functionality (switching through Homey, updating status in Homey when toggled on switch) is not working at all.

In the z-wave log (stuff for geeks) I see the messages coming in;

Eerst linkerschakelaar aan -> uit, daarna rechterschakelaar aan -> uit

[2017-07-29T14:17:17.251Z] Node[2]: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x0d02002503ff
[2017-07-29T14:17:17.307Z] Node[2]: Decapsulated frame from COMMAND_CLASS_MULTI_CHANNEL to COMMAND_CLASS_SWITCH_BINARY, data 0x03ff
[2017-07-29T14:17:33.764Z] Node[2]: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x0d0200250300
[2017-07-29T14:17:33.795Z] Node[2]: Decapsulated frame from COMMAND_CLASS_MULTI_CHANNEL to COMMAND_CLASS_SWITCH_BINARY, data 0x0300
[2017-07-29T14:17:45.859Z] Node[2]: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x0d01002503ff
[2017-07-29T14:17:45.885Z] Node[2]: Decapsulated frame from COMMAND_CLASS_MULTI_CHANNEL to COMMAND_CLASS_SWITCH_BINARY, data 0x03ff
[2017-07-29T14:17:45.887Z] Node[2]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff
[2017-07-29T14:17:49.714Z] Node[2]: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x0d0100250300
[2017-07-29T14:17:49.735Z] Node[2]: Decapsulated frame from COMMAND_CLASS_MULTI_CHANNEL to COMMAND_CLASS_SWITCH_BINARY, data 0x0300
[2017-07-29T14:17:49.748Z] Node[2]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x0300

But nothing happens in the devices overview; switches stay in state they are put in through Homey. Also, when switching them through Homey, it does not change the state on the switch (the relay does not click and the lights do not change), and I see zero entries in the log. I also tried creating cards on "Switch turned on/off" but these also do not work.

Please advise. What can I supply for you to investigate?

Homey v1.3.2
Z-Wave v3.99

**Comment by TedTolboom** [comment]
Hi Blast3r,

I'm looking into the issue. It appears that there are two SW versions shipped by Neo.

This issue is at the top of my list to pick up after I return from Holidays; three weeks from now.

Just before my holidays I received two touch switches; one V1 and one V2... so that should provide the HW to test and solve the issue.

Ted

**Comment by BLAST3R** [comment]
Hi Ted,

Thanks for your reply and work so far. I will be attempting to fix it locally, because this has sparked my interest now. I'll let you guys know as soon as I have a pull request ready with a possible fix.

Have a good vacation!

**Comment by TedTolboom** [comment]
Looking forward to strike through an issue while enjoying my holidays... ;-)

Keep me posted, I might send you my remaining work list...

**Comment by BLAST3R** [comment]
I actually got it working after some tinkering (good old debugging). There seem to be multiple problems preventing it from working with the version I have here (the Zwave Plus dual channel one).

In the device class and properties I get back upon receiving a status report, the value key on the command_report_parser object has to be "Value" instead of "Current Value". Also, when setting the new state through Homey at the command_set_parser, it expects "Switch Value" as key, not "Target Value". When I changed these two properties, it started working flawlessly.

That was, as soon as I commented out the Single Switch driver in the app.json file (because it uses the same product ID, it sadly always detects my dual channel switch as a single channel one). I think the way forward is using only one switch driver (remove the single one). The only problem is then an aesthetic one where it shows a picture of a single switch on left/right devices. But at least then it works properly.

In my fork I have a working version of the plugin for use with the dual channel touch switch now. It should also work for single-channel switches (theoretically), because it also sets the Target Value key with the same value. See https://github.com/BLAST3R/com.neo/commit/34d70c28d8e96ea444269862999f6f406da03714

**Comment by TedTolboom** [comment]
@blast3r

Thanks for the feedback. Greatly appreciated!

The Value / Current Value and Switch Value / Target Value are the differences between the V1 and V2 version of the Switch Binary CC. Once I'm back I will check if the code you changed is working with both versions (V1 and V2); from what I can see it should work.

The single switch has most likely been added (copied from double switch) by @mruiter based on an announcement from Neo. 
It should never have the same product ID. We'll remove the single switch / or change the product ID to non existing in the next update awaiting the actual launch of the single switch.

Thanx!

**Comment by mruiter** [comment]
the single is only on the github version and non functional.
i expect it to arrive this week so i can read out the id's.

You should use the appstore version not the github unless asked 😉

Verstuurd vanaf mijn iPad

> Op 1 aug. 2017 om 23:37 heeft dT <notifications@github.com> het volgende geschreven:
> 
> @blast3r
> 
> Thanks for the feedback. Greatly appreciated!
> 
> The Value / Current Value and Switch Value / Target Value are the differences between the V1 and V2 version of the Switch Binary CC. Once I'm back I will check if the code you changed is working with both versions (V1 and V2); from what I can see it should work.
> 
> The single switch has most likely been added (copied from double switch) by @mruiter based on an announcement from Neo. 
> It should never have the same product ID. We'll remove the single switch / or change the product ID to non existing in the next update awaiting the actual launch of the single switch.
> 
> Thanx!
>

**Comment by BLAST3R** [comment]
That explains why it didn't run the first time I cloned and tried using the GitHub version. At least until I corrected the class/capabilities listing in the app.json file.

Of course I started out with trying the appstore version, but that did not work with my touch switches (Z-Wave Plus). This is why I created this issue. The fix I supplied for the dual touch driver should work for both version numbers, though.

I only own Dual Touch Switches, Door/Window Sensor and Power Socket. The last two seem to work correctly.

**Comment by BLAST3R** [comment]
Ah, found out another issue now. It seems that when you press both buttons shortly after each other, only one of the status changes gets triggered at a time. So this probably needs some more investigating/love to get it to it's full potential (no idea if it's related to Homey or app implementation or the z-wave hardware itself). But that's something else than discussed in this issue.

**Comment by TedTolboom** [comment]
@BLAST3R see #30 PR... 
tested you driver update ok and updated the dual and single touch switch drivers accordingly...

Thanks!

**Comment by mruiter** [comment]
No other reports did show up after ted his pull. closing this issue
