### ISSUE TITLE
Homey Pro 2019 and NEO Coolcam

### ISSUE THREAD

**Issue by per-ast** [mruiter/com.neo#284]
Hi

All my Z-Wave devices stopped working at the same time.
I have 12 NEO Coolcams.
Can no longer get these into Homey Pro 2019.
Works in Athom Homey Bridge Smart home controller.
Have reinstalled the NEO Coolcam app in Homey Pro 2019.

**Comment by mruiter** [comment]
You could try the last test version NEO Coolcamhomey.appVerstuurd vanaf mijn iPhoneOp 9 jul 2024 om 14:46 heeft per-ast ***@***.***> het volgende geschreven:﻿
Hi
All my Z-Wave devices stopped working at the same time.
I have 12 NEO Coolcams.
Can no longer get these into Homey Pro 2019.
Works in Athom Homey Bridge Smart home controller.
Have reinstalled the NEO Coolcam app in Homey Pro 2019.
