### ISSUE TITLE
Support for HPE2023

### ISSUE THREAD

**Issue by Dome0068** [mruiter/com.neo#286]
Hello,
Could you please to give an update for your APP to be compatible with Homey Pro Early 2023?
Please let me know

**Comment by mruiter** [comment]
Already there just append /test to the url in the home App StoreVerstuurd vanaf mijn iPhoneOp 7 aug 2024 om 10:31 heeft Dome0068 ***@***.***> het volgende geschreven:﻿
Hello,
Could you please to give an update for your APP to be compatible with Homey Pro Early 2023?
Please let me know

**Comment by Dome0068** [comment]
Thank you,
I have just installed it and I will test as soon as I receive a NEO coolcam door sensor just bought.
Are you planning to make a stable version in the meantime?
