### ISSUE TITLE
Homey Pro 2023

### ISSUE THREAD

**Issue by Ola1960-june** [mruiter/com.neo#288]
Hi, I have just upgraded from 2019 to 2023, but unfortunately my favorite units are nor working. I have a lot of units from Neo Coolcam, plugs, motion detectors and repeaters and it seems that the App isn't compatible with 2023. Please dont force me to reinstall my 2019 again. 

Regards
Ola

**Comment by mruiter** [comment]
If you look in the GitHub where you made the issue you should find that the 2023 version is available by appending /test behind the homey AppStore url 😉Verstuurd vanaf mijn iPhoneOp 12 aug 2024 om 18:04 heeft Ola1960-june ***@***.***> het volgende geschreven:﻿
Hi, I have just upgraded from 2019 to 2023, but unfortunately my favorite units are nor working. I have a lot of units from Neo Coolcam, plugs, motion detectors and repeaters and it seems that the App isn't compatible with 2023. Please dont force me to reinstall my 2019 again.
Regards
Ola

**Comment by StenOA** [comment]
I Have 20 devices from Neo CoolCam not working now on my new Homey 2023

**Comment by mruiter** [comment]
Its already available, just add /test behind the appstore URL
