### ISSUE TITLE
How can i disable the power meter ?

### ISSUE THREAD

**Issue by Sillec123** [mruiter/com.neo#29]
Hey all of my neo power plugs are flooting the z-wave logs with power measuere values! It seams like it doesn't matter what i changed on the device site.

**Comment by mruiter** [comment]
The reports donget it all the time. bit there so small the zwave network bandwith should be able to handle it easly.
Default values are good enough is most cases.

**Comment by Sillec123** [comment]
Strange, because so many devs say that i should disable the power measure function for better z-wave experience. And why is there a option to disable the function in the device card if it isn't working?

**Comment by mruiter** [comment]
How many devices do you have ? like 150+ like me and still my zwave isnt flooded..
Read the forum.. you would have found info that if you add it as light for example you dont get power reading in homey. But then again. devices report all on the network . even when disabled on the controller . it just doesnt look at the reports.

Take a deep dive , theres a 1000+ pages manual on how zwave works.
Maybee you can send it to those devs 2
