### ISSUE TITLE
Weird text in the tags

### ISSUE THREAD

**Issue by WesRos** [mruiter/com.neo#31]
The trigger card: "When Power is changed" has the tag: Wh. What does it meant?
I think you meant watt (W). Because Energie/Power isn't time based.
![image](https://user-images.githubusercontent.com/8507396/30181183-bdf133b0-9412-11e7-8936-87379b27004c.png)

The tag in the trigger card is different with the tag in the tag-menu. Dutch<--> Englisch. Without the unit name: watt (W)
Then you have the "Stroom" and the "Stroommeter".
It's better to call "Stroommeter" --> Energieverbruik/Energy Usage with the unit name: KWh
![image](https://user-images.githubusercontent.com/8507396/30181210-d0ee7e32-9412-11e7-9b14-4cf448f7a019.png)
In another text the Stroommeter is called: Stroomverbruik. Better is: Energieverbruik.
![image](https://user-images.githubusercontent.com/8507396/30182209-51da202a-9416-11e7-91f6-e4df39508a88.png)

Is it for my posible to make a change in the code, so you've only to accept mine changes? Then I could comment why I change something.

**Comment by TedTolboom** [comment]
@wesros,

It's indeed not really consistent... Although energieverbruik and stroomverbruik are commonly interchanged..

The flow cards and tags referred to are default cards linked to the measure_power and meter_power capabilities and originate from a library of Athom. They are not defined within the Neo app... Except for the reset meter card, which is an custom defined action card.

What would be your proposed changes?

**Comment by WesRos** [comment]
I should propose to change the name: 
- "Stroommeter" to "Energieverbruik/Energy usage" or only "Verbruik/Usage". (kWh)
- "Energie" to "Vermogen/Energy" (watt)

Stroom/Current en Voltage/Voltage are clear.

**Comment by mruiter** [comment]
As of sdkv2 version the default core texts are used for these vars.
