### ISSUE TITLE
Issue with door sensor (NEO_DS01Z)

### ISSUE THREAD

**Issue by jjtbsomhorst** [mruiter/com.neo#32]
For some reason my NEO_DS01Z door sensor does not behave as I would expect. When I open the door homey does registrate a 'contact alarm'. But when my door closes that alarm stays on. I can see on the device that when the door opens or closes a red light is blinking. 

Is this a know issue or is there something I'm doing wrong here? 

here is a picture of the sensor [https://photos.app.goo.gl/9NzkQE4rzdbAjU7H3](url)

**Comment by mruiter** [comment]
There are some major bugs in the zwave core of homey.
athoms is already working 8+ weeks on it. eehhh well i guess doing something with it. (waiting ?)

Maybee on 1.5.6 we will see some improvements
