### ISSUE TITLE
Add SOS-Remote

### ISSUE THREAD

**Issue by Lansuper** [mruiter/com.neo#37]
Is it possible to add the Z-Wave SOS-Remote (4 button) to the app? Or is it the one mentioned here in GitHub, but not in the app-list? I'll gladly provide one to you for testing...

**Comment by mruiter** [comment]
working on it as we speak.
See my github beta brach. it has a working button 1,2,3 single and double click

Im making a nice sos icon and the emergency parsers for the red button that arent supported in the default zwave mesh driver yet

Verstuurd vanaf mijn iPad

**Comment by Lansuper** [comment]
Fantastic! Loving your work on the other devices as well, already have over 20 sensors, 6 powerplugs and  6 lightswitches up and running...

**Comment by mruiter** [comment]
Driver is finished . Its in Beta 2.0.1 pending appstore review by athom
