### ISSUE TITLE
No secure connection.

### ISSUE THREAD

**Issue by jprgomet** [mruiter/com.neo#41]
I have Fibaro plug. It connects over secure connection.
Neo plug does not use secure connection.
It states no, under secure info.
Is it me, neo plug or app? :)

**Comment by mruiter** [comment]
Fibaro connect using sha encryption.
This is not allowed in china.

Neo offers just kike some other brands a different type of encryption.
Homey does not support this or shows it as secure. 
Nothing to do about is Neo side
