### ISSUE TITLE
Error when setting motion sensor to low sensitivity

### ISSUE THREAD

**Issue by cbho** [mruiter/com.neo#42]
When trying to change 

sensitivity to "lower" or "lowest" with error messages "failed_to_set_motion_sensor_sensitivity_to_128_size_1" and "failed_to_set_motion_sensor_sensitivity_to_255_size_1", respectively.

Homey Firmware Version: 1.5.6-rc.7
NEO Coolcam app v2.0.3 - 11.12.17

![image](https://user-images.githubusercontent.com/29979509/34072138-0371e106-e282-11e7-87e2-85625d44c21d.png)

**Comment by faahrev** [comment]
Same here...

Homey v 1.5.3
Neo v 2.0.4

**Comment by jghaanstra** [comment]
According to this manual the parameter for sensitivity has allowed values 1-4 instead of 8-255. Not sure what is correct though.

http://www.cd-jackson.com/zwave_device_uploads/401/Manual-for-Motion-sensor-PIR-Zwave-Neo.pdf

**Comment by mruiter** [comment]
Its not 1 to 4 The sensitivity has Always been 8 -255
But something seems to go wrong with signed and usigned values.

I have declared a "signed": false in de json but it seems its not accepting the 128 and up only 0-127

**Comment by mruiter** [comment]
Seems 2 be a bug in the Homey Zwave Mesh Driver. Peeps are already working on the enhancements of the parser.
When the update is out i will post and close this issue

**Comment by mruiter** [comment]
Nevermind.

Added the fix myself to the mesh driver

Fixed in next version

**Comment by Michielvm5** [comment]
Hallo,

Ik heb nog steeds dit probleem, ik kan de gevoeligheid wel omhoog zetten maar niet omlaag.
Krijg de zelfde foutmelding als hierboven.

neo v2.0.9
