### ISSUE TITLE
No trigger card for firing the doorbell

### ISSUE THREAD

**Issue by 2benl** [mruiter/com.neo#43]
I am on V2.03 of the app and Homey experimental 1.5.6 RC7.
When I try to set my neocoolcam alarm there is no trigger card to fire the doorbell or alarm. I can only set the mode, alarm tone, doorbell tone, volume etc.

**Comment by mruiter** [comment]
There should be this card ?

![siren](https://user-images.githubusercontent.com/17739535/34154024-5c4c1dd0-e4b4-11e7-895e-36f4ce62aa07.PNG)

**Comment by 2benl** [comment]
Oeps sorry. Silly me.
