### ISSUE TITLE
[Feature Request] Always On option on wall plug

### ISSUE THREAD

**Issue by vogon1** [mruiter/com.neo#45]
Hi,

I would love to have an Always On option in the wall plug driver.
When using the plug for measuring power consumption of e.g. a refrigerator or computer, it should not be possible to (accidentally) switch it off, unless the Always On option is unchecked first.

It would behave like the FIbaro wall plug 'Aways On' function.

Thanks,
Sietse

**Comment by mruiter** [comment]
This is something that should be implemented in the plug its hardware . fibaro has this. Neo doesnt.
But its just as easy to do in a homey flow.  Evry 5minutes when plug is of turn on.
And you made youre own always on function
