### ISSUE TITLE
[Feature request] Support for motion sensor with temperature (ET version) 

### ISSUE THREAD

**Issue by Lansuper** [mruiter/com.neo#46]
SInce a couple of months there is a motion sensor with temperature sensing available. With the current drivers it's not possible to read the values and act on them. Please implement this.

**Comment by mruiter** [comment]
The real V2's of the NEO Pirs has been added. Old V1's in a V2 casing dont report Temp and have a V1 firmware.
Temp only gets reported when you have a real V2 version and homey adds it with the V2 icon

**Comment by Lansuper** [comment]
Is it possible that PIR's with the ET label are still V1 firmware? Even when adding them with v.2.0.7 through the V2 pictogram, they are added as V1...

**Comment by mruiter** [comment]
hou can click the v2 icon in pairing as much as you like. its there for show.
 and doesnt do a thing.
if youre hardware and firmware in the pir reports itself as a v1 in a v2 case it will be added as a v1 
if you have a real v2 with v2 firmware and devices ids then you will get v2 icon and temp

**Comment by mruiter** [comment]
if youre v2 reports as v1 and adds as v1 then go bug neo for a firmware update that has the fix and the real devices ids of the v2
