### ISSUE TITLE
Joining V2 motion sensors shows up as V1

### ISSUE THREAD

**Issue by rnldnkp** [mruiter/com.neo#47]
Bought some Neo Motion sensors as Fibaro keeps giving me issues. Choose the V2 from Neo, with the metal/magnetic base. 

When joining them to the Z-wave network using the app (MacOS), I click on Motion V2. When it's joined it shows up as V1, both name and image.

Not sure what the technical difference is, but it sure is confusing.
Is some code mixed up here, or did someone put a V1 sensor in my V2 housing? ;)

Homey 1.5.6
Neo App 2.0.6

**Comment by mruiter** [comment]
There is no difference . That’s why you will always get the same icon .


Verstuurd vanaf mijn iPhone

**Comment by rnldnkp** [comment]
Thanks for the quick response. 

So far the Neo Motion works better already, just got my 'doorbell rang x times when away' working for the first time this week :D 

Wouldn't it be nicer to just show one type when joining with "PIR V1/V2" or "PIR"? Since there's no technical difference, and the icon/name chosen is not used?
