### ISSUE TITLE
[Req] New Flow card: Open OR Closed

### ISSUE THREAD

**Issue by Radiotechniman** [mruiter/com.neo#48]
My request is to include a "Open OR Closed" flow card 
This would allow us to use the "Else" part of a flow cutting down the needed flows by 50% 
e.g; 
IF "Door Open" THEN   "Send Notification "Door Open""
IF "Door Closed" THEN  "Send Notification "Door Closed""

Would become: 
IF "Door Open or Closed" AND Door Open THEN  Send Notification "Door Open" ELSE Send Notification "Door Closed"

I had put this initially on the forum, but somoen mentioned the github would be better 

https://forum.athom.com/discussion/4766/req-flow-card-contact-open-or-closed?new=1

**Comment by mruiter** [comment]
Since this is a generic flow card request please make the request in the AThom Github so they can implement this for all door sensors.
It has been requested before so maybee they will implement it in the V2 firmwares if there are enough users that request it.

**Comment by Radiotechniman** [comment]
ok, thanks



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

2018-03-05 16:35 GMT+01:00 Marco Ruiter <notifications@github.com>:
