### ISSUE TITLE
NAS-PD02ZT (Neo Coolcam, Pir V2)

### ISSUE THREAD

**Issue by FirstRebel** [mruiter/com.neo#49]
Hallo, 

Ik heb een NAS-PD02ZT Pir V2 aangeschaft maar deze wordt herkend als een Pir V1
De Pir krijgt van de applicatie de product_Id= 4227 in plaats van product_id = 4237.

Hierdoor werkt de temperatuur meting niet, moet deze nog toegevoegd worden of gaat hier iets fout?

Vast bedankt voor de moeite,

Rob

**Comment by mruiter** [comment]
Je hebt een nep V2 of ze hebben de verkeerde firmware erin gedaan . Kans is groter dat je geen echte V2 hebt maar alleen een mooie V2 casing.  Id 4227 in bij zwave alliance gecertificeerd voor v1 

Verstuurd vanaf mijn iPhone

**Comment by FirstRebel** [comment]
Thx voor de snelle reactie, ga contact opnemen met de leverancier van deze Pir

**Comment by FirstRebel** [comment]
De leverancier stuurd een andere dus het lijkt erop dat de eerste geen V2 was.
