### ISSUE TITLE
brightness is changing not working on PirV2 sensor

### ISSUE THREAD

**Issue by ronald2404** [mruiter/com.neo#50]
Hi Marco,

About a month ago you added the support for the real Pir V2 sensor. At this moment it is not possible to set a paramater brightness is changing value.  I do have the option brightness is changing in my flow but I cant change any values. Can you please fix this? 

Regards

Ronald

**Comment by mruiter** [comment]
Could you provide me with some screenshots and the what the problem is . i dont think i understand you correct with this. 

Verstuurd vanaf mijn iPad

**Comment by mruiter** [comment]
And if you are dutch then in dutch is also ok

Verstuurd vanaf mijn iPad

**Comment by mruiter** [comment]
No response so i guess the biggest bug of all. Human error.
