### ISSUE TITLE
Touch Switch Dual is not shown it's state

### ISSUE THREAD

**Issue by alpol017** [mruiter/com.neo#51]
Hello! Thank you for your app.
Found an issue:

If I turning on the switch via flows (for example if there is a motion, light on).
Switch is turned on phisically but in homey app or web interface it doesn't shows.
But, if you clicking a button on the switch it immediately shows turned on/off state in the app.
If you turn on/off switch via app, everything is OK.

**Comment by mruiter** [comment]
Should be fixed in RC11. Updates ok on mine now.

**Comment by alpol017** [comment]
Right now everything works fine. I’ve seen only once, two weeks ago may be, when I didn’t seen the real state of the switch. I have rebooted homey and it had fixed the issue.
