### ISSUE TITLE
Error when setting motion sensor to low sensitivity 

### ISSUE THREAD

**Issue by Michielvm5** [mruiter/com.neo#52]
Hallo,

Ik heb nog steeds het probleem dat ik de gevoeligheid niet kan aanpassen naar een lagere gevoeligheid. Ik zag dat er al een toppic van was geopend waarin je zei dat het probleem in de volgende update werd gemaakt, alleen is bij mij het probleem er nog.

Gr

**Comment by mruiter** [comment]
Andere bevestigen dat het is opgelost.... Kan het zijn dat de pair ook niet goed gaan is destijds dat hij een error geef ?

Anders zou je een screenshot willen geven met de error die komt als je boven het rode error driehoekje met de mousepointer zweeft ziet ?

**Comment by Michielvm5** [comment]
Ik krijg geen foutcode als ik boven de driehoek zweef met mijn muis. Ik krijg alleen deze melding.
Geld teven ook voor de laagste gevoeligheid alleen is 128 dan 255 geworden.
Heb ook al opnieuw gekoppeld. 

<img width="773" alt="schermafbeelding 2018-05-13 om 21 39 31" src="https://user-images.githubusercontent.com/38228454/39971137-aa668230-56f6-11e8-8bd4-876d6a985b8b.png">

**Comment by mruiter** [comment]
Je hebt zo te zien een echte V2 Pir.   Ik gok dat deze wat setting waardes anders heeft dan de v1.
Heb net een bericht naar neo verzonden maar die moeten het uitzoeken .....

Heb je misschien in het doosje zo'n klein papiertje dat ze handleiding kunnen noemen gehad ?
Als ik daar wat foto shots met bv je telefoon kan ontvangen staan daar hopelijk de V2 versie setting codes in.

**Comment by Michielvm5** [comment]
Hier zijn de foto's van de user manual.

![img_4447](https://user-images.githubusercontent.com/38228454/40115546-26067ca8-5911-11e8-8ab8-7b5ebb1a6a44.JPG)
![img_4448](https://user-images.githubusercontent.com/38228454/40115547-262f60fa-5911-11e8-90e7-9275ffc8e9a2.JPG)
![img_4449](https://user-images.githubusercontent.com/38228454/40115548-266c2954-5911-11e8-92c2-026c24d2f01b.JPG)
![img_4450](https://user-images.githubusercontent.com/38228454/40115551-26a94636-5911-11e8-8d3f-6ebeb1bc97a1.JPG)

**Comment by mruiter** [comment]
Kan je apps installeren buiten de App-Store ? Zo ja zou je dan de laatste versie hier van github eens kunnen testen voor me of het nu weg is ?

**Comment by Michielvm5** [comment]
Nee buiten de appstore downloaden kan ik niet, misschien dat het met uitleg wel lukt.

**Comment by mruiter** [comment]
Ok heb hem al als beta richting de AppStore gezet. Het is even wachten tot Athom hem goedkeurt maar dan zou je de beta kunnen testen

Verstuurd vanaf mijn iPhone

**Comment by Michielvm5** [comment]
oke, dan wacht ik daarop, dank!

**Comment by mruiter** [comment]
The beta 2.0.10 is now available in the appstore.
Let me know if it fixes youre issue

**Comment by Michielvm5** [comment]
Het is gelukt heb de instellingen aan kunnen passen!
Daankjewel!

**Comment by mruiter** [comment]
Nice
