### ISSUE TITLE
Connecting Motion Sensor PIR2 (using version v2.0.10 of the app)

### ISSUE THREAD

**Issue by rakersh** [mruiter/com.neo#55]
I am trying to add a new Neo Coolcam motion sensor PIR2 on the Athom, but that fails all the time. By the way had already successfully added a PIR1 device but PIR2 seems not to be working.

I select add devices from Neo Coolcam : PIR2 
I follow the instructions (press button 3 times and the sensor flashes 5 times
I continue to repeat this step (flash 5 times)
I keep the sensor close to the Athom (less than 20 cm)
After I while I get an error message in Dutch (translated) : No device found

I also rebooted the Athom. But still not working. Any idea? 
Thanks

**Comment by mruiter** [comment]
Nothing I can do. Be sure you have a EU version else it will never pair . Remove the device from homey and before pairing reset the pir to default like stated in the manual .

If something is wrong with the app you would at least get a generic device . 

I guess you got the non Eu version that works on different frequency’s and can’t be paired to a Eu homey . Check the types like stated in the app read me notes in the store 

Verstuurd vanaf mijn iPhone

**Comment by rakersh** [comment]
Thank you for your quick answer! 

But good news - I got it working now! I had to push the button on the sensor for over 15 seconds to reset the device, after that it worked. 

Thanks again, great application.

**Comment by mruiter** [comment]
Good to hear it’s not the EU version problem. A reset to default does magic sometimes . Enjoy 

Verstuurd vanaf mijn iPhone

**Comment by rakersh** [comment]
Bedankt!

Verstuurd vanaf mijn iPhone
