### ISSUE TITLE
Don't work devices on 869 Mhz

### ISSUE THREAD

**Issue by KarasN** [mruiter/com.neo#57]
Now I have only one this device: NAS-WR01ZE, Power Switching Plug. Please add support for them.
ProductID = 8327.
Thanks

**Comment by mruiter** [comment]
Will add iT as soon as i come Home in a few days . Thanks for reporting the 869mhz  id 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
I added it to the app. I'm also awaiting the ID's from someone else that has the PIR.
As soon as i got that one i will push the app update to beta version
