### ISSUE TITLE
NEO Wallplugs 

### ISSUE THREAD

**Issue by jacquesvzijp** [mruiter/com.neo#61]
Hi
I have a number of NEO Wallplugs, all correctly configured to my knowledge. However I experience lot of TX Errors (and probably RX). Seems overall bad Z-wave communication. Distances are all fairly close, not further then 3-4 meters between devices. Fibaro plugs in same network function over at least 10 meters.
Is this a general problem?
Thanks
Jacques

**Comment by mruiter** [comment]
Different brands have different ranges see the community forums for zwave optimizations theres nothing i can do for u in the app .
4 meters is about the max voor zwave in crowded wireless networks like zigbee wireless etc etc . Make sure you mesh good and use the heal procedure on dev tools like you should by the book

Verstuurd vanaf mijn iPhone
