### ISSUE TITLE
Dome by Elexa / (NAS-AB01ZE, Siren / Doorbell speaker) not recognised

### ISSUE THREAD

**Issue by rupe8** [mruiter/com.neo#62]
Hi there,

I'm in Australia and am trying to connect a door bell siren that looks exactly like the NAS-AB01ZE but is branded here as Dome by Elexa. When I try to pair it to Homey using Neo Coolcam it doesn't recognise the device and pairs it as a Basic Z wave device. 
Do you know if it is possible to link this device using your app?

Any help would be greatly appreciated.

Rupe

<img width="713" alt="image" src="https://user-images.githubusercontent.com/44962929/48333378-45d23400-e6ab-11e8-91ec-d43b249b26b5.png">

**Comment by mruiter** [comment]
I have added it to the latest github version . You could sideload it and give it a try or wait until the next beta is in the appstore

**Comment by mruiter** [comment]
Ohh, and let me know if it works ;)

**Comment by mruiter** [comment]
Beta version is in the appstore . You will need to remove and rejoin he device with homey z-wave.
Please report back if it works

**Comment by rupe8** [comment]
Hi mruiter,

Dome branded device seems to be working well.. trying to get it to cooperate with my doorbell still but that's not an issue on your end.
Thanks very much and I'll keep you posted on anything I find that you might find useful.

**Comment by mruiter** [comment]
Great and thx for the feedback. 
If you have other Dome branded zwave like the pir or the the door sensors let me know , they are also rebranded NEO devices and then i can add those ID's to
