### ISSUE TITLE
Homey doesn’t recognise Neo Coolcam SOS button / key fob

### ISSUE THREAD

**Issue by baboonen** [mruiter/com.neo#64]
Hi,

I’ve bought a Neo Coolcam single SOS button but Homey doesn’t recognise it. I get the following message in Dutch: Er is geen geschikte Homey App gevonden voor dit apparaat. In English: There is no suitable Homey App for this device.

I’m running firmware version 1.5.13 and version 2.0.10 of the Neo app.

At the moment it is added as a generic z-wave device but the device doesn't seem to work either when a test 
![schermafbeelding 2018-11-28 om 17 35 06](https://user-images.githubusercontent.com/45432361/49166850-79ac8b00-f334-11e8-83fc-8099cc0a7ed7.png)
flow has been created to adjust lighting when pressed. Please advise.

**Comment by mruiter** [comment]
I have added youre Product ID to the new github build. Hope to have the beta app in the appstore as beta soon. Let me know if it works

**Comment by mruiter** [comment]
Beta version is in the appstore . You will need to remove and rejoin he device with homey z-wave.
Please report back if it works

**Comment by baboonen** [comment]
Hi Marco,

 

At this moment I don’t have the beta app on Homey. What is the impact when switching to it? Can I revert back to the normal app?

 

Kind regards Bobby

**Comment by mruiter** [comment]
This beta will go to stable if you can confirm that it works :) 
Then you will go back to stable again.

**Comment by baboonen** [comment]
Homey now recognises the device so that's good news. Unfortunately pressing
the button doesn't trigger anything. In devices I can see it's working but
when I create a flow with this device as trigger it doesn't work. Any
suggestions?

Regards Bobby

Op vr 7 dec. 2018 13:55 schreef Marco Ruiter <notifications@github.com:

**Comment by mruiter** [comment]
Are you able to run the app with athom cli so we can debug the output of the sos button ?

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
CLosed, no other user has reported a other issue yet
