### ISSUE TITLE
Motion Sensor PIR V2 - Activity LED fresh install

### ISSUE THREAD

**Issue by edwinvdpol** [mruiter/com.neo#65]
I just got myself a new Neo Coolcam Motion Sensor v2.
After installing I checked the LED activity checkbox in the settings, which was off.
It did blink red when motion was detected.

I had to enable the checkbox - Wake up (3x click and save) - remove the checkbox and wake up again to fix this. It looks like the default settings aren't the correct ones?

**Comment by mruiter** [comment]
Homey doesn’t always set the right defaults in the pair. Nothing I can do in the app

Verstuurd vanaf mijn iPhone
