### ISSUE TITLE
Status update not every 300 sec on Homey v2.0.0 RC

### ISSUE THREAD

**Issue by mhoogenbosch** [mruiter/com.neo#67]
The NEO Coolcam power plug has been set to poll every 300 secs. When currently looking at the properties of the plug it reports the values of 2 hours ago (when tapping on the value you can see the last status update time). 
I am using the latest RC of version 2.0.0

**Comment by mhoogenbosch** [comment]
With the sable release of your app it does work.

**Comment by mruiter** [comment]
There is no difference for the plug in beta or stable app. So I guess it’s a homey core bug (as most of the time)

Verstuurd vanaf mijn iPhone

**Comment by mhoogenbosch** [comment]
Right! I'll close the issue.

**Comment by mhoogenbosch** [comment]
Hi Marco,


I've tried it again. Upgraded to the beta app. Removed the coolcam plug and readded. It doesn't report anything with the beta app. I know you are convinced it is homey but still, I think it is good to know, must have something to do with the new mesh drivers?!


Regards,


Martijn

________________________________
Van: Marco Ruiter <notifications@github.com>
Verzonden: maandag 10 december 2018 14:31:38
Aan: mruiter/com.neo
CC: mhoogenbosch; Author
Onderwerp: Re: [mruiter/com.neo] Status update not every 300 sec on Homey v2.0.0 RC (#67)

There is no difference for the plug in beta or stable app. So I guess it’s a homey core bug (as most of the time)

Verstuurd vanaf mijn iPhone
