### ISSUE TITLE
wall plugs

### ISSUE THREAD

**Issue by satbopper** [mruiter/com.neo#68]
Still the wall plugs are not doing their job,providing decent info
homey firmware 2.0 rc3 app 2.0.11
i removed the plug and newly installed it but all info 0 and a freezer connected
comparision a fibaro plug is working well

**Comment by Lansuper** [comment]
After installing version 2, the plugs are still working. Adding a new one is possible, but doesn’t return to a ‘done’ screen. A plug not in use reports 0 (zero) for all values, a plug in use reports random values, but for all metrics of a plug the same. So 0,25 W, 0,25 V etc.

**Comment by satbopper** [comment]
correct,then i am not the only one and i think it is not a homey core fault because my fibaro plug is working great here

**Comment by mruiter** [comment]
Mobile cards have changed and are undocumented . So time for Athom to deliver documentation from there knutselwerkjes 

Verstuurd vanaf mijn iPhone

**Comment by satbopper** [comment]
ok yes documentation is and will be always lousy but now i know more
thanks

**Comment by Lansuper** [comment]
Unfortunately, this problem is not solved with Homey 2.0 rc 3

**Comment by satbopper** [comment]
the problem is that developers can not test their own apps because they are not running v2 themselves and they have only one homey,and they do not want to break it until v2 is stable
and so you are not coming any further on short term,it is a pity

**Comment by jprgomet** [comment]
getting some random numbers ..

+1

**Comment by mruiter** [comment]
People report its working again with the latest V2 firmware out of the blue....
Can you confirm ? Because theres nothing more i can do appside values do get in but just dont get shown right on the cards when it happens

**Comment by Lansuper** [comment]
Nope, with Homey firmware 2.0.0 rc 8, NEO v2.0.12 and app version 0.17.0.237 I still get random values per plug and the same for all values of the pug.

**Comment by mruiter** [comment]
Well i cant resolve this. If it happens to you its best to create github issues in the atom homey issue database. As confirmed by multiple persons this isnt app related but homey core related .
I notified them even with a movie in there testing slack channel. But users need to report it themselfs if you want them to pick it up since i cant reproduce.

**Comment by jprgomet** [comment]
well .. for some unknown reason I now get normal readings

**Comment by mruiter** [comment]
Yes its fixed

Verstuurd vanaf mijn iPhone
