### ISSUE TITLE
Tried 2 differend wallplugs - No power stats

### ISSUE THREAD

**Issue by Stekeltje** [mruiter/com.neo#7]
I've added this app today to the Homey but the plugs only show the switch. No power stats are available in 'Devices' or at 'Insights'

Homey version: 1.0.5
App version: 1.1.4

**Comment by mruiter** [comment]
Then you did not add them as other but as light device I guess. Homey does not show power usage then. 

There's already a custom mobile card in making for the next version. Then this should be possible also when adding as light 

.


Outlook voor Android






On Wed, Dec 28, 2016 at 11:28 PM +0100, "Stekeltje" <notifications@github.com> wrote:












I've added this app today to the Homey but the plugs only show the switch. No power stats are available in 'Devices' or at 'Insights'

**Comment by TedTolboom** [comment]
@Stekeltje did the feedback of @mruiter solve your issue?

**Comment by Stekeltje** [comment]
I'm sorry for the late reply. It did help to choose for Others :), I'm able to see power usage.
