### ISSUE TITLE
Duration time parameter error. 

### ISSUE THREAD

**Issue by kapusticka** [mruiter/com.neo#70]
I’m trying change parameter “duration time” to “Endless until battery drain” in Neo Coolcam siren / doorbell. It ending with error: 
“Settings could not be saved (failed_to_set_doorbellsoundtime_to_255_size_1: An unknown error has occurred [failed_to_set_doorbellsoundtime_to_255_size_1]) 
Can you help me? This error message is showing in Homey 1.5.13 and 2.0 too. :(

**Comment by mruiter** [comment]
Homey core bug in current .13 and V2 firmware

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
This isnt the bug in saving settings , i found a value missing in the config template. I have corrected it and already pushed a new version of the app .13 to the appstore that is awaiting approval by athom.
If you can sideload with atom cli you can already get it from my github
