### ISSUE TITLE
2.0.14 broke all my door sensors

### ISSUE THREAD

**Issue by psiebe** [mruiter/com.neo#71]
all was working fine until 3 days ago, since the update my sensors do not communicate with homey properly. unstalled and reinstalled the app and readding sensors at the moment, which is quite painfull

**Comment by mruiter** [comment]
You can just wake them up with 3 fasts clicks on the button if homey looses connection because of a zwave initialisation failure . I did not have other reports of non functional door sensors yet 

Verstuurd vanaf mijn iPhone

**Comment by psiebe** [comment]
Thanks Marco, they seem to be working fine again after re-adding. good to
know the shortcut

Patrick

Op wo 26 dec. 2018 om 15:51 schreef Marco Ruiter <notifications@github.com>:

**Comment by mruiter** [comment]
Good to hear back from you . Enjoy you’re doorsensors 👌

Verstuurd vanaf mijn iPhone
