### ISSUE TITLE
Single Touch Switch missing since last version

### ISSUE THREAD

**Issue by Sillec123** [mruiter/com.neo#72]
Hi since homey 2.0rc9 the neo Single Touch Switch was transforms in a Basic zwave Device.

**Comment by mruiter** [comment]
That is strange . Could you give me the ids like manufacture device ids in the gear / settings of the basic device ?

A remove from zwave and a re pair still gives a. Unknown device ?

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
And also pull the plug on homey to see if that makes the app load better. There are some troubles right after a update 

Verstuurd vanaf mijn iPhone

**Comment by Sillec123** [comment]
DeviceId:47
Manufacture:600



Diese E-Mail wurde von einem mobilen Gerät gesendet. Ich bitte Tippfehler zu entschuldigen.

This mail was written on a mobile device. Thank you for understanding.

**Comment by mruiter** [comment]
Please also the rest of the ids 

Verstuurd vanaf mijn iPhone

**Comment by Sillec123** [comment]
Sure, here are the rest id‘s
Manufacturer 600
Device 47
Productid 4236
Product type id 3

Diese E-Mail wurde von einem mobilen Gerät gesendet. Ich bitte Tippfehler zu entschuldigen.

This mail was written on a mobile device. Thank you for understanding.

**Comment by Sillec123** [comment]
Now it is working. Repairing was the solution. 

Diese E-Mail wurde von einem mobilen Gerät gesendet. Ich bitte Tippfehler zu entschuldigen.

This mail was written on a mobile device. Thank you for understanding.
