### ISSUE TITLE
'batterijwaarschuwing gaat aan' is listed twice

### ISSUE THREAD

**Issue by Fire69** [mruiter/com.neo#73]
Hi,

When creating a flow, 'batterijwaarschuwing gaat aan' is listed twice.

![image](https://user-images.githubusercontent.com/1757287/50552338-3c1f8280-0c91-11e9-94bb-655ab640b9b4.png)

Homey 2.0rc9
App version 2.0.14

**Comment by mruiter** [comment]
i think thats a homey core problem but not sure i will take a look

Verstuurd vanaf mijn iPad

**Comment by mruiter** [comment]
Nope they added it to the core as also available for generic devices if it has battery. I deleted the custom card so the next version doesnt have the double anymore.
Thanks for reporting

**Comment by TedTolboom** [comment]
@mruiter you still have the custom battery card defined for the Siren: https://github.com/mruiter/com.neo/blob/master/config/flow/triggers/NAS-AB01ZE.json

Which explains the double listing

**Comment by mruiter** [comment]
Thx Ted , but already deleted and closed it ;)
