### ISSUE TITLE
Motion detection LED indication

### ISSUE THREAD

**Issue by volodeev** [mruiter/com.neo#74]
ver.2.0.14 LED motion detection does not turn off. NAS-PD02ZE.
Help me please!

**Comment by mruiter** [comment]
You need to wake up the PIR with 3 fast clicks on its button and then straight away push apply settings in homey app settings. Then it should take it.
Please let me know if this resolves it. It does with others but NEO also seems so have new firmwares in some devices.

**Comment by volodeev** [comment]
> You need to wake up the PIR with 3 fast clicks on its button and then straight away push apply settings in homey app settings. Then it should take it.
> Please let me know if this resolves it. It does with others but NEO also seems so have new firmwares in some devices.

Thanks for the hint how to wake up the PIR. I set the values with different options 
![image](https://user-images.githubusercontent.com/46497923/51692576-07e47b00-201f-11e9-9fd4-bb1d7a1cb397.png)
and
![image](https://user-images.githubusercontent.com/46497923/51692594-159a0080-201f-11e9-802a-8d720a7b0a18.png)
I wake up the PIR with the help of 3 quick taps, I save the settings. It did not help!
Other settings change successfully - for example, "Motion detection function".

**Comment by mruiter** [comment]
Should be fixed in the lastes version . Neo updated the manual with the right info so i could correct the setting
