### ISSUE TITLE
Lux value is not updated in Homey 2.0

### ISSUE THREAD

**Issue by coenboomkamp** [mruiter/com.neo#75]
Hi,

I noticed that the lux value from the movement sensor of Neo Coolcam hasn't been updated since i upgraded to 2.0.

I haven't tried to re-add the device yet, didn't had time yet. 

Just wanted to report it here. Maybe it's a known issue.
I will report back when i have tried to re-add the sensor.
![img_1253](https://user-images.githubusercontent.com/34875500/51239919-e62e2880-197a-11e9-9d79-a1541b23449c.jpeg)

**Comment by mruiter** [comment]
Its not a know issue yet ;)
But my own are still reporting . 
Before a repair just try a wakeup on the devices . Thats done by clicking the button inside 3 times fast .
IT should light up and send in all reports again

Verstuurd vanaf mijn iPhone

**Comment by coenboomkamp** [comment]
Thank you for the quick reply, i will try that first and report back!

**Comment by mruiter** [comment]
and did it fix youre issue ?

**Comment by coenboomkamp** [comment]
Yes it did! Thx for the help! 👍

Verstuurd vanaf mijn iPhone
