### ISSUE TITLE
Neo coolcam powerplug doesnt recognized

### ISSUE THREAD

**Issue by vwoudenberg** [mruiter/com.neo#76]
The powerplug doesnt recognized by the app. Tried the reset and delete z-wave a couple of times. My other plugs worked as a charme. 
Fabrikant ID: 600 
Product type ID: 512
Product ID: 4135

**Comment by vwoudenberg** [comment]
Im running on homey V2 with your app V2.0.14

**Comment by mruiter** [comment]
I see you have a new / for me unseen id .
I Will add them to the app Then all should work 

May i ask which country you live ?

Verstuurd vanaf mijn iPhone

**Comment by vwoudenberg** [comment]
Ive got the product today at the mail. I live in the netherlands. Thank you for the fast reply.

**Comment by mruiter** [comment]
Strange , that they have changed the product and device id both for the eu version 🧐

Do you already owned plugs before and do you see anything different with this one. 
I hope they have improved the pair button . When the plugs age thats the part that seems to fail even when not used much 

Verstuurd vanaf mijn iPhone

**Comment by pkroeze** [comment]
Received also and EU version with 512 today

**Comment by mruiter** [comment]
The ids are added to the app. 
Its awaiting aproval in for publish under beta in the Appstore . 
Please let me know if this solves the issue 

Its also possible to install straight away without waiting for the Appstore if you get the latest master from my github and install iT by Athom cli

Verstuurd vanaf mijn iPhone

**Comment by niels1449** [comment]
I had the same issue and can confirm it's solved with the new 2.0.15 version of the app. 

Home app store insn't updated yet so the athom cli is needed. see link for instruction
https://forum.athom.com/discussion/1448/how-to-cli-install-method
