### ISSUE TITLE
unable to add Neo Coolcam Touch Switch - Homey v2.0.1

### ISSUE THREAD

**Issue by kempet87** [mruiter/com.neo#79]
I'm unable to add the Touch Switch (1 button) to devices, the device get's recognized and then gives message that the device is to far away (it's just 2m away from homey), adding it again results in an "status,already_added" message. Resetting Z-Wave or reinstalling the app does not solve the problem.

**Comment by mruiter** [comment]
just do a remove first from zwave settings homey its still paired even when it doesnt show. the devices has homey its key

Verstuurd vanaf mijn iPad

**Comment by kempet87** [comment]
That did the trick, thanks!
