### ISSUE TITLE
Powerplugs not updating values anymore after update V2.0.16

### ISSUE THREAD

**Issue by canedje** [mruiter/com.neo#81]
Neo app just updated to latest version.
After that the power wallplugs are not updating the values anymore, like watt and current

**Comment by mruiter** [comment]
The new app should be dynamic now in V2 thats why the new meshdriver was used again or are you still on v1 maybee (iT should also work on that but can not test iT myself)
Make wake up the plug with 3 quick pushes on the button ?

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Still work here 🤔



Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
And this is 3 minutes later 



Verstuurd vanaf mijn iPhone

**Comment by canedje** [comment]
I’m using Homey V2.
I did make flows to dim lights after switching on tv by measuring current/watt by the wallplugs
This is not working anymore after update.
The values checked at the devices page is also not updating 
I’m trying an ptp at the moment

**Comment by canedje** [comment]
I think I did find the problem.
The plug is only updating after “meter rapportage interval (s)” and not anymore after a change of 80% of the value

**Comment by mruiter** [comment]
Good to hear , i was already afraid that there again was a problem with the new mesh driver 😝

Verstuurd vanaf mijn iPhone

**Comment by canedje** [comment]
Oké But it is still a problem.
And misfunctioning of the app

**Comment by mruiter** [comment]
If you are on V2 firmware then its a problem of the homey app itself . They are working on iT to make iT more real time . Until then we have to wait. The plug reports like the settings you give iT . They neo app just does the translation of the incomming reports and passes them to homey to do something with iT.

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Depends on the tv , mine only uses 1.2 watt . Not enough for a plug to trigger .  The usage on youre tv i cant tell but again not something the app does anything with . IT just gets the watt value from the communication and passes iT to homey .
But youre watts dropped 10 watt with the version update ?
Can you give me the insights data that has been collected the passed days with the drop in iT so i can pass iT to Athom ?


Verstuurd vanaf mijn iPhone

**Comment by canedje** [comment]
Yes it drops value looks like.
So you are sure it is not the Neo app itself?
The value update looks like random in time and not updating for a long time. Before it changed every 5 minutes because meter rapportage was 5 minutes (300s). I changed meter rapportage time in 60 sec’s and wijziging van vermogen in 20%. Now after a while value changes once at switching of or on tv.
Where can i find insight data to pass to you in V2 ?

**Comment by mruiter** [comment]
insights.athom.com

Verstuurd vanaf mijn iPad

**Comment by canedje** [comment]
Funny. The graph is showing the right values.
But these are different from values showen at the device in the app
![df79148b-7cbf-45d9-a40e-f9a69b808273](https://user-images.githubusercontent.com/23150947/52084078-856d3580-25a1-11e9-92b1-d3746d66b6e0.png)

**Comment by itshows** [comment]
same here, it only updates when powered on or powered off. In the mean time no updates. The config says it should update every minute but nothing happens. The insight of the last hour where the tv is powerdoff at 11.36 and power back on 11.40 is below. I pulled the plug from the wall but after that no difference. My tv is consuming about 100 watts average when powerded on. Now only 17 watts according to the plug. :) and the values are not changing.
![afbeelding](https://user-images.githubusercontent.com/46216331/52119134-72497c80-2618-11e9-8fca-c6d4670f4489.png)

**Comment by mruiter** [comment]
I pushed the old mesh driver again to the .17 version on my GitHub and have already placed in in the AppStore as beta . It’s awaiting approval from athom but if you can try please try my GitHub version and see if it’s working again

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
The 2.17 beta is in the appstore now

**Comment by itshows** [comment]
yes, working again. 👍

**Comment by itshows** [comment]
was about to install the beta via the athom-cli.  this is better ;)

**Comment by mruiter** [comment]
Fixed in 2.17 and already as stable in appstore
