### ISSUE TITLE
Feature Request: Neo coolcam touch switches add toggle card

### ISSUE THREAD

**Issue by Xyclade** [mruiter/com.neo#82]
I am using neo coolcam double touch switches as input to turn on / off my Hue lights.

To do this currently, I have 4 flows:

If switch turned on, and light off, turn on light
If switch turned off, and light off, turn on light
If switch turned on and light on, turn off light
If switch turned off and light on, turn off light

Adding a card in homey that triggers on toggle, rather than explictly on turned on, or explicitly on turned off, would reduce the need of half of my flows.

I hope this can be added, and will gladly donate you a beer (or for charity) for this! ;-)

**Comment by mruiter** [comment]
flips added in sdkv3 version
