### ISSUE TITLE
PIR v2 parameter setting missing

### ISSUE THREAD

**Issue by ThaDuck** [mruiter/com.neo#84]
I had some issues with a PIR v2, I thought motion was not detected correctly. I was wrong, it is detected as expected, but there is a new parameter introduced with v2:
```
11. MotionEventReportOneTimeEnable
"1" - The motion detected event will be sent to controller/gateway only once until the device report motion cleared event.
"0" - The motion detected event will be sent to controller/gateway when device detects motion event.
Function: MotionEventReportOneTimeEnable
ParameterNumber: 11
ParameterSize: 1 Byte
Available settings: 0,1
Default setting: 1
```

This behaviour differs from PIR v1. I want to change parameter 11 setting to 0, but as the parameter setting is missing in Advanced Settings of the PIR v2 I am not able to do so.

Hope you can add this parameter. Thanks.

**Comment by ThaDuck** [comment]
I tried to contribute to this repository, but as this is my first time I was not able to get the new code pushed to a new branch.

For your information, I think this code I created:
```
    {
      "id": "motion_eventreport",
      "zwave": {
        "index": 11,
        "size": 1,
        "signed": false
      },
      "type": "checkbox",
      "_size": 1,
      "label": {
        "en": "Motion detection event report",
        "nl": "Bewegingsdetectie gebeurtenis rapportage"
      },
      "value": true,
      "hint": {
        "en": "Enabled: The motion detected event will be sent to controller/gateway only once until device report motion cleared event. Disabled: The motion detected event will be sent to controller/gateway when device detects motion event. (#11, default: enabled = checked)",
        "nl": "Ingeschakeld: De bewegingsdetectie gebeurtenis wordt eenmalig gerapporteerd aan de controller/gateway. Disabled: de bewegingsdetectie wordt bij elke detectie gerapporteerd aan de controller/gateway. (#11, standaard: ingeschakeld = checked)"
      }
    }
```

Tried to add it to com.neo/config/drivers/NAS-PD02ZE.json and com.neo/app.json

**Comment by mruiter** [comment]
Topper , I will add it when I get to the office later today

Verstuurd vanaf mijn iPhone

**Comment by ThaDuck** [comment]
My pleasure, thanks!

**Comment by mruiter** [comment]
Its added in the latest beta and in the appstore. Please be aware you can only switch back to stable once this version goes to stable . If you install stable from appstore again homey will delete all the neo devices paired. So if you can wait i guess if non of the beta testers report other trouble ( i dont think so with this setting change) it will go stable in the weekend.

**Comment by ThaDuck** [comment]
Unfortunately this did not the trick. The parameter is changed as expected, red LED indicates motion. But the information is not processed correctly on Homey. It still reports motion 1 time.

Is there any other place in the app which should be changed to get this working correctly?
