### ISSUE TITLE
Status led doesn’t disable 

### ISSUE THREAD

**Issue by mhoogenbosch** [mruiter/com.neo#86]
When disabling the status led it doesn’t turn off. It saves the setting just fine and is set but it stays on. Tried both stable and beta app.

**Comment by kvanzoelen** [comment]
I am having the same issue. Quite annoying when its next to your bed.

**Comment by mruiter** [comment]
Update to the latest version t

**Comment by kvanzoelen** [comment]
It has been updated to v2.0.19, removed and installed the plug again but still no joy when trying to switch of the led light.

**Comment by mhoogenbosch** [comment]
Latest version the led still doesn’t work with the off switch. Sorry to say

**Comment by mruiter** [comment]
Since youre issues where so unclear i assumed you where refering to the pirv2 where the led light could not be turned of.

Now is see mentioning of a plug ?? Or do you mean wall switches ?

**Comment by mruiter** [comment]
And what version of the plug do you have, the V2 or a V1 . Post info like whats in the device id etc on the device advanced setting.

**Comment by kvanzoelen** [comment]
It concerns the power plug NAS-WR01ZE V2.

**Comment by mhoogenbosch** [comment]
Apparaat ID 13
Fabrikant ID 600
Product Type ID 512
Product ID 4135

all other stuf works

**Comment by kvanzoelen** [comment]
Hi, I am sorry to bother but the issue still exists although this thread has been closed?
