### ISSUE TITLE
V2 indicated in the button as v1

### ISSUE THREAD

**Issue by Pim65** [mruiter/com.neo#87]
Hi,

I have an v2 motion detector, installing this one gives the button in homey showing v1.
It is also interfearing with my aeotec multisensor 6 (motion alarm) so if neo is detecting a motion alarm, he is showing the motion alarm of the aeotec (in the flow)

**Comment by mruiter** [comment]
Apps cant interfere in a way youre discribing . That would be a first but please attach the log file that this is happening.

For the v1 icon see all other closed issues about it . There are v1 and V2 casings and v1 and V2 firmwares
If you have a temp sensor you have V2 casings can’t be seen until homey gets a eye upgrade ;)

**Comment by itshows** [comment]
same here, bought my first v2 pir and when installed yesterday it shows as a v1 pir. Also i am not able to update any advanced setting. It gives me a time-out after 30 seconds. The only setting that can be changed is the wake-up interval, which is now turned on an the time is set to 1800 seconds. Also the temp sensor is nowhere to be found in flow cards.
@mruiter are you saying that v2 casings are being shipped with v1 hardware inside? The v2 casing has a stong magnet on board to be mouted, where the v1 has not. Mine has definitely a magnet inside.

**Comment by itshows** [comment]
ok, read some v2 issues that have been closed. seems like a fake v2 pir. i am contacting the seller. 
still curious why the advanced settings are not updatable. pir works, but is not in anyway ajustable. If it is a v1, it should be still be usable as a v1 or am i wrong.

**Comment by mruiter** [comment]
Yes that’s what I’m saying
They have a v1 and V2 casing
And a V1 and V2 hardware 
You can mix them as you wish . Only a real V2 hardware has a temp sensor
The timeout on settings is normal do a search and you will find some answers 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
You will have to wake up a zwave device for the settings . So 3 clicks to wake up and click apply settings 

Verstuurd vanaf mijn iPhone

**Comment by itshows** [comment]
That's new to me. All my neo battery devices are updated over the air with no pressing of buttons. This new pir now also accepts updates. I think the zwave mesh has to be rebuilt when the new device is on the new spot (on the ceiling that is). Now it works like a charm. Still mailing with the seller in china about the v1 pir in the v2 casing.

**Comment by itshows** [comment]
ok, no result, seller says it's a v2 housing with v1 hardware. Looked at the order and there was no mentioning of a temp sensor. So be aware when buying a neo V2 pir. It should mention temp sensor otherwise it's a V1.

**Comment by mruiter** [comment]
Most resellers don’t have a clue.
The V2 isn’t even registered as a official zwave device at the zwave alliance 

I hear you have to explicitly order the pirs that have V2 with temperature on the box and noted everywhere 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
The wake up let’s the device pickup pending packets like settings and if no good connection to you’re mesh reroute .

Verstuurd vanaf mijn iPhone
