### ISSUE TITLE
PIR v2 motion not detected correctly

### ISSUE THREAD

**Issue by Drardollan** [mruiter/com.neo#89]
Referring to #84 

The parameter is working as expected, after changing from ON to OFF the red LED on the PIR is telling me that motion is detected. When I look at the PIR v2 in Homey nothing to see.

Is there any other change in the Coolcam App code needed to get this working as expected?

**Comment by ThaDuck** [comment]
I can add some extra info on this, PIR v1 also not working as expected anymore. The red LED is also telling me that there is motion detected, but in Homey no events are recorded.

**Comment by ThaDuck** [comment]
Quick update, after restarting Homey everything looks fine. I will do some final testing later this evening to be sure and let you know the result.
