### ISSUE TITLE
New (secure) coolcam plugs have different parameter id's

### ISSUE THREAD

**Issue by PetervdK65** [mruiter/com.neo#92]
I bought 4 new plugs recently. When adding they automatically show they are "secure" and that is a new feature. However, that is not the only thing that changed. It seems that all parameters ID's have changed in the new models.
I tried to switch off the LED function (parameter 5), but nothing changes with the new plugs. Not by doing it via the standard option under advanced settings but also not by issuing it manual via raw option.
I have searched everywhere, but i can't find anything about this. I contacted my supplier, but didn't get response yet.
Is there a way to find out the new parameter ID's somehow?

**Comment by mruiter** [comment]
Duplicate issue #85

**Comment by mruiter** [comment]
The V2 plug Will split next version from the v1 and the settings Will be available .

**Comment by PetervdK65** [comment]
Great new, thanks!
Regards, Peter(vdK)
