### ISSUE TITLE
Unable to pair

### ISSUE THREAD

**Issue by glasn** [mruiter/com.neo#93]
I’m unable to pair any coolcam device (tried several) anymore. See 1fa656ec-56cb-4aaf-be1d-df4b41c7c782

These devices worked before.

Thanks, Niels

**Comment by mruiter** [comment]
Unable to pair is a honey problem or a plug problem . Remove the device first from settings -> remove device .
Nothing wrong with the app if you can’t pair . If the app is wrong it will also pair but just as a unknown device 

Verstuurd vanaf mijn iPhone

**Comment by glasn** [comment]
I just also tried a fibaro device.... same issue. Sorry to bother you.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mruiter** [comment]
No problem . Did you already try a Pull the plug on homey ? 

Verstuurd vanaf mijn iPhone
