### ISSUE TITLE
Motion detection does not go off

### ISSUE THREAD

**Issue by edwinvdpol** [mruiter/com.neo#94]
My motion detector detection does not go off since yesterday. 

I had this one time earlier, then I had to remove the device and re-add it again. Can you see what is going on? Re-pair, rebooting app, rebooting Homey, all did not help. 

Report ID
57e10183-2efc-4053-8f80-a7ea1e0ca272

**Comment by mruiter** [comment]
I can’t it’s a honey core issue . And I also don’t get the send in reports . They only end up in Athoms mailbox . If you want info why you should contact support@athom.com

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
No further response , issue closed
