### ISSUE TITLE
Advanced settings not send correctly

### ISSUE THREAD

**Issue by fwelvering** [mruiter/com.neo#95]
Hi,

I have an PIR v2 (yes with temparature reading) and i noticed settings are not send correctly.
When trying to change the LED setting it sends a 11,1,1 or 11,1,0 but this should be 10,1,1 to enable or 10,1,0 to disable.
There are more settings that do not work.
When setting them into 'Raw Configuration' it does work.

According to Homey dev it uses the following driver:
homey:app:com.neo — NAS-PD02ZE

In the code i see jou just changed the code for other values.

**Comment by mruiter** [comment]
Changed the settings and  Plublished to github.
The new version is pending review in athoms appstore and will be soon available is the beta branch when athom approves .

Please let me know if it works OK so i can close the issue or close it youreself if all works
