### ISSUE TITLE
869.2 mhz. Russian frequency

### ISSUE THREAD

**Issue by Tuhulka** [mruiter/com.neo#96]
Hi, could you add the Russian frequency of 869.2 mhz? Devices with this frequency are not detected as sensors.

**Comment by Tuhulka** [comment]
Property Value
ID 3d7a54ad-309d-453b-a182-0ef3d3e7a71f
Class socket 
Driver homey:manager:vdevice — zwavebasic
Ready Yes
Available Yes
Warning No
Custom icon No

Settings
Key Value
zw_node_id "6"
zw_manufacturer_id "600"
zw_product_type_id "3"
zw_product_id "8333"
zw_secure "⨯"
zw_battery "✓"
zw_device_class_basic "BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic "GENERIC_TYPE_SENSOR_NOTIFICATION"
zw_device_class_specific "SPECIFIC_TYPE_NOTIFICATION_SENSOR"
zw_firmware_id ""
zw_wakeup_interval 43200
zw_wakeup_enabled false
zw_group_1 ""
zw_group_2 ""
zw_group_3 ""
zw_group_4 ""
zw_configuration_value ""

Capabilities
Capability Type         Value     Edit value     Last Updated
onoff        Boolean     true      true              10 minutes ago

**Comment by Tuhulka** [comment]
Basic Z-Wave Device
Property Value
ID 3d7a54ad-309d-453b-a182-0ef3d3e7a71f
Class socket 
Driver homey:manager:vdevice — zwavebasic
Ready Yes
Available Yes
Warning No
Custom icon No

Settings
Key Value
zw_node_id "6"
zw_manufacturer_id "600"
zw_product_type_id "3"
zw_product_id "8333"
zw_secure "⨯"
zw_battery "✓"
zw_device_class_basic "BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic "GENERIC_TYPE_SENSOR_NOTIFICATION"
zw_device_class_specific "SPECIFIC_TYPE_NOTIFICATION_SENSOR"
zw_firmware_id ""
zw_wakeup_interval 43200
zw_wakeup_enabled false
zw_group_1 ""
zw_group_2 ""
zw_group_3 ""
zw_group_4 ""
zw_configuration_value ""

Capabilities
Capability Type            Value     Edit value Last Updated
onoff         Boolean       true       true         17 minutes ago

**Comment by mruiter** [comment]
Which sensor is this ? Then i can add it.

**Comment by Tuhulka** [comment]
NAS-PD01Z. Motion Sensor.

**Comment by Tuhulka** [comment]
Hey. my motion sensor has been added as Door Sensor.?

**Comment by Tuhulka** [comment]
Hey. Please fix the motion sensor and add the Door Sensor. NAS-DS01Z-RU.
Property Value
ID 8b3b04e9-9002-4d99-8035-5cb43ed22e1c
Class socket 
Driver homey:manager:vdevice — zwavebasic
Ready Yes
Available Yes
Warning No
Custom icon No

Settings
Key Value
zw_node_id "7"
zw_manufacturer_id "600"
zw_product_type_id "3"
zw_product_id "8322"
zw_secure "⨯"
zw_battery "✓"
zw_device_class_basic "BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic "GENERIC_TYPE_SENSOR_NOTIFICATION"
zw_device_class_specific "SPECIFIC_TYPE_NOTIFICATION_SENSOR"
zw_firmware_id ""
zw_wakeup_interval 43200
zw_wakeup_enabled false
zw_group_1 ""
zw_group_2 ""
zw_group_3 ""
zw_group_4 ""
zw_configuration_value ""

Capabilities
Capability   Type           Value   Edit value   Last Updated
onoff           Boolean     null      true            12 minutes ago

**Comment by Tuhulka** [comment]
Advance thanks!

**Comment by mruiter** [comment]
ID's are added. Published to github. 
The new version is pending review in athoms appstore and will be soon available is the beta branch when athom approves .

Please let me know if it works OK so i can close the issue or close it youreself if all works

**Comment by Tuhulka** [comment]
Thank you! 
Everything is perfectly connected. 
In the way NAS WR01Z, NAS SC01Z, NAS and NAS WS02Z-PD02Z. EN frequency. Will it be possible to contact You for help in connecting?

**Comment by Tuhulka** [comment]
No EN frequency. RU frequency

**Comment by mruiter** [comment]
Offcourse you can contact me then . Will add them sonlwt me know the ids when you het them . I Will close this issue . Please create a new issue if you get the other devices 

Verstuurd vanaf mijn iPhone

**Comment by Tuhulka** [comment]
Hey. Good afternoon. Me again. My devices are 869.2 mhz. Russian frequency has arrived. Please add them to the plugin. Thank you in advance for your help.

NAS-WS02Z Flood Water
Settings
Key Value
zw_node_id "13"
zw_manufacturer_id "600"
zw_product_type_id "3"
zw_product_id "8325"

[NAS-PD02Z Z-wave Plus PIR Motion Sensor Detector+Temperature Sensor Z wave Alarm System Motion Sensor https://ru.aliexpress.com/item/32856082375.html?spm=a2g0o.detail.1000016.1.38f943eaG8s3bX&isOrigTitle=true
First the motion sensor was V2 case V1. When connected to RUBETEK it shows the temperature. In Homey the temperature is not showing, because it is added as NAS-PD01Z.
Settings
Key Value
zw_node_id "12"
zw_manufacturer_id "600"
zw_product_type_id "3"
zw_product_id "8333"

Touch Switch Dual
Settings
Key Value
zw_node_id "16"
zw_manufacturer_id "600"
zw_product_type_id "3"
zw_product_id "8331"

NAS-WR01Z connected correctly as Power Plug
Settings
Key Value
zw_node_id "15"
zw_manufacturer_id "600"
zw_product_type_id "3"
zw_product_id "8327"
