### ISSUE TITLE
Support for NAS-DS01ZH AU/NZ 921.4 Mhz 

### ISSUE THREAD

**Issue by PlanetTech** [mruiter/com.neo#97]
Just tried adding a Door Sensor which is being discovered as a Basic Z-Wave device. Checking the supported devices, ANZ region is not listed.

The device model is : NAS-DS01ZH. 
I'm based in NZ region which use the 921.4Mhz frequency.

Is this something which can be added in future releases and what do you require from the logs to help with this. I'm no coder but can read and understand so will also review the current code to better understand myself how these are identified.

Thanks
Gavin

**Comment by PlanetTech** [comment]
Checking the device details, I'm guessing the only difference in the door sensors will be the type_id or product_id.


Key | Value
zw_manufacturer_id | "600"
zw_product_type_id | "3"
zw_product_id | "24706"

Thanks

**Comment by mruiter** [comment]
Thanks thats just what i need to add them to the app. Will be added this week.

**Comment by PlanetTech** [comment]
Thanks heaps and much appreciated.

I donated some money as well for the good cause.

Gavin

Sent from my iPad

On 29/04/2019, at 18:34, Marco Ruiter <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks thats just what i need to add them to the app. Will be added this week.

**Comment by PlanetTech** [comment]
Awesome. Thanks will do so.

Sent from my iPhone

On 7/05/2019, at 9:07 PM, Marco Ruiter <notifications@github.com<mailto:notifications@github.com>> wrote:


ID's are added. Plublished to github.
The new version is pending review in athoms appstore and will be soon available is the beta branch when athom approves .

Please let me know if it works OK so i can close the issue or close it youreself if all works

**Comment by mruiter** [comment]
Can you confirm they work so i can close the issue ?

**Comment by PlanetTech** [comment]
Confirmed working. Thank you.

Sent from my iPhone

On 31/07/2019, at 7:35 AM, Marco Ruiter <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you confirm they work so i can close the issue ?
