### ISSUE TITLE
power plug neo 

### ISSUE THREAD

**Issue by domooytica** [mruiter/com.neo#98]
wie weet oplossing voor volgend probleem?
ik probeer powerplug van neo coolcam te installeren, echter na herhaalde pogingen geeft deze 'status.already_added' echter hij staat niet in de apparatenlijst. Ook herkent app van Marco Ruiter geen apparaat.

**Comment by mruiter** [comment]
Gewoon in setting zwave eerst verwijderen . Ook al zie je hem niet . Daarnaast kan je hem toevoegen . Eerste pair is mislukt . Homey ziet hem niet maar de zwave chip kent hem door de mislukte pair al wel en dus krijg je already added

Verstuurd vanaf mijn iPhone

**Comment by domooytica** [comment]
Ok, goede tip. Na meerdere pogingen connected, maar heeft problemen met
overzetten van aan/uit. Ook geen uitlezing en negatief verbruik

Op za 4 mei 2019 om 10:57 schreef Marco Ruiter <notifications@github.com>
